### ISSUE TITLE
Image wanted

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#1]
We want to selectively add an 'image wanted' graphic to species pages without any record images.

**Comment by johnvanbreda** [comment]
I've changed the styling of the page so if you add an image with a deliberate broken link, then it displays as a white box containing the words "Image wanted". So, you just need to create an Image Link content item linked to the taxon which I've done for Acicula fusca. Here's an example: https://www.naturespot.org.uk/node/230786.

You will need to delete (or de-prioritise) these images once you get real images. 

You should be able to close this issue now if you are happy with this solution @davidnicholls125.

**Comment by davidnicholls125** [comment]
The link opens a comment page with no image box visible...? On the Acicula fusca page the white box just shows as a broken link without any text. We really wanted to use our own graphic, such as that attached. I'm not sure a plain white box would look very good in the galleries?  @johnvanbreda
![Image wanted](https://user-images.githubusercontent.com/80914584/112037901-24669a00-8b3a-11eb-97cb-0e6ff8fbd382.jpg)

**Comment by johnvanbreda** [comment]
Sorry - I didn't make that clear - that's the fake image node's page. If you edit it (https://www.naturespot.org.uk/node/230786/edit) you will see that it has minimal details, as long as there is something in the filename and the taxon is set correctly it will work. Try https://www.naturespot.org.uk/gallery/snails to see the effect. I noticed that Graham had changed the priority to 2 on this image but it will need to be left at 1. 

I've worked out I can apply a background image - it would be better to use a standard font overlay rather than embed the font in the image though. Do you have a background image you'd like me to apply? We can also style the font (using a web-safe font family), colour it, and enlarge the box if you want.

**Comment by davidnicholls125** [comment]
Thanks John, it was me that moved it on the species page - I dragged it from the second tab to the main tab to see if it displayed differently. As well as displaying it on the gallery we will want it on the species page too, though it should do this with a priority 1 tag I think? On the snails gallery, it is still showing as a broken link without text.
![image needed](https://user-images.githubusercontent.com/80914584/112053181-f2f6ca00-8b4b-11eb-8c4e-2441a30098be.JPG)
I've attached 3 files that we could use as a background image. The opacity needs reducing so that the text shows clearly. I'll leave you to see what works best and to select text that you think is clear.
![Background1](https://user-images.githubusercontent.com/80914584/112054244-3b62b780-8b4d-11eb-8cd1-adecda7efa83.jpg)
![Background2](https://user-images.githubusercontent.com/80914584/112054246-3bfb4e00-8b4d-11eb-943f-3f2e8f721db5.JPG)
![Background3](https://user-images.githubusercontent.com/80914584/112054249-3c93e480-8b4d-11eb-9ef7-5ed125286649.JPG)

**Comment by johnvanbreda** [comment]
The solution I'd found didn't work in Firefox. So I've created an image based on the maple leaves and added it to the warehouse. To use this image, create an Image Link with the file name set to naturespot-image-needed-bg.jpg.

**Comment by davidnicholls125** [comment]
Thanks John. Is it possible to add a link to the image? We have an 'image wanted' page which explains the need for photos to have been taken in VC55, otherwise we get sent images we can't use.
https://www.naturespot.org.uk/images_wanted

**Comment by davidnicholls125** [comment]
Also we discussed needing a new image download facility to identify species with/without images. (The current download is slow and limited so an elasticsearch version would be a big improvement). Can we also identify if there is a published image in the gallery section?

**Comment by johnvanbreda** [comment]
@davidnicholls125 please can you create a new issue to cover the image downloads, so we can keep this issue about the single topic of the image wanted icon in galleries. 

I'm trying to avoid having to write significant new code but can't see a perfect solution to the link to the images wanted page without doing so. One possibility would be for me to create an image containing the text on the images wanted page, then when you click on the thumbnail we use that as the full size copy of the image. It would then be a popup rather than a page link, and you would not be able to select text or click the email link (you'd have to type it out). Is that OK?

**Comment by davidnicholls125** [comment]
Also we discussed needing a new image download facility to identify species with/without images. (The current download is slow and limited so an elasticsearch version would be a big improvement). Can we also identify if there is a published image in the gallery section?

**Comment by davidnicholls125** [comment]
OK I've set up a new issue for the image download.
Perhaps just change the text to 'Leicestershire & Rutland image needed' which should avoid the need for a link.

**Comment by johnvanbreda** [comment]
Do you mean the text on the current icon should change from "Image needed" to "Leicestershire & Rutland image needed"?

**Comment by davidnicholls125** [comment]
Yes, is this OK? It seemed the easiest solution.

**Comment by johnvanbreda** [comment]
Do you want to prepare the image with text added exactly as you want it then, and I can replace the files? If you want a small version as shown in the gallery and a larger version shown as a popup when you click on it that is fine.

**Comment by davidnicholls125** [comment]
Please can you replace the existing image wanted graphic with this one? Also, can the image be hyperlinked to https://www.naturespot.org.uk/images_wanted. If this is difficult then perhaps we could use the comment box to create the link with the text 'image wanted info'.

**Comment by davidnicholls125** [comment]
![Image-wanted](https://user-images.githubusercontent.com/80914584/140764503-756a7620-3fe4-404e-b069-32dcd9a0de6d.jpg)
I presume it will get resized automatically?

**Comment by johnvanbreda** [comment]
I've done this. The comment can't be used for the link as it's plaintext, so I added an "Image wanted link" field to the bottom of the image link edit form. If you edit the Acicula fusca image you can see how I did it.

Please close if OK.

**Comment by davidnicholls125** [comment]
Thanks, that works fine. Could you retain the proportions of the image I sent you please. I deliberately kept it relatively tall and slim so it dominated less when we have a few displaying in the gallery.
Also, I added a link this morning and entered 1 in the priority box but it published it on the additional images tab. I could drag it to the gallery section of course but shouldn't it default to this section with priority 1?

**Comment by johnvanbreda** [comment]
I've reset the image dimensions.

The images that appear on the main species account page also need the "Promoted to front page" box ticked under "Promotion options".

**Comment by davidnicholls125** [comment]
Thanks.
