### ISSUE TITLE
collapse text

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#10]
We would like to use collapse text on our FAQ page. The module was already in the folder but not installed. I installed it but can't get it to work. The sparce documentation states:
"As this is an input filter, it will only work where input filters are applied."
However we are not sure what this means. Can you let us know what we need to do please?

**Comment by johnvanbreda** [comment]
As the FAQs page uses the "Full HTML" format, you can find the configuration for this format under Configuration -> Text formats and editors -> Full HTML (i.e. https://www.naturespot.org.uk/admin/config/content/formats/manage/full_html). Under enabled filters, I've enabled "Collapsible text blocks" then save the page. According to the instructions, it can be placed at the end of the list of filters that are applied (in the Filter processing order section).

Having done that, I experimented and found the following example, using the title attribute for the question would work well:

> [collapse collapsed title="1.2 My species isn't listed on the Submit Records species menu, what do I do?"]
> 
> The species list only includes those that has been recorded previously on NatureSpot. Additional species are being found all the time so the list is steadily expanding. If you have found a species that isn’t on the list, type '+' and then select '+ new species' from the drop down menu. You will then be asked to to tell us what species you think it is and what evidence you have - write this in the comments box on the species row. For a new species to be accepted you will either need to send photographic evidence or a recognised expert must have identified it for you. We only add new species that have been identified with 100% certainty.
> 
> [/collapse]

I've reset the content as it was so you can experiment.

**Comment by davidnicholls125** [comment]
Brilliant. Thank you. I wasn't aware of that bit of the configuration - I should explore more!
It seems to be working fine.
