### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#101]
We want to set up a number of milestones for 100 Species participants. On the set up page there is a red error message at the bottom - could you check this please? Also, we need a Group ID for 100 Species participants, how do we set this up?
![image](https://user-images.githubusercontent.com/80914584/159756068-272f83f2-05fd-4073-85ff-e4d4485108ca.png)

**Comment by davidnicholls125** [comment]
John, can you respond please?

**Comment by johnvanbreda** [comment]
Fixed

**Comment by davidnicholls125** [comment]
You didn't let me know the group ID I need to use for 100 species participants...... Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the group ID is 2227.
