### ISSUE TITLE
Records form changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#102]
We have noticed that on iRecord the Identified by field is auto-filled with the recorder's name. Can we adopt this on NS too please?
Also, on the National Moth Recording records form (which is also linked to iRecord) they have a My Places option where the form details for regularly visited sites are stored. Again, can we add this to NS?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've updated the Identified By field to default to the logged in user. 

For the sites change, it's an hour or so's work to copy over the required forms. Also, as this requires a new menu item (My Sites) so that users can edit their list of sites, I'm not sure where in the menu system it should be placed? We don't have much space in the main menu. I suppose a link to the My Sites list could go on My Dashboard?

**Comment by davidnicholls125** [comment]
Thanks, I've amended the help text. Could the link to the My Sites form go on the Submit Records form itself, perhaps alongside 'Site Name'?

**Comment by johnvanbreda** [comment]
Yes that would work. Before I do that - the sites list is available at https://www.naturespot.org.uk/sites/my so would you like to test it? You should be able to add sites then find them using the site name input on the recording form.

**Comment by davidnicholls125** [comment]
I've added a test site (Ratby garden) and it seems to work fine. Can we use the hybrid map though - the same as on the Submit Records form. When I selected Ratby garden on the Submit Records form it showed up as a square on the map but didn't enter the grid ref on the form - can it do this automatically?

**Comment by johnvanbreda** [comment]
I've changed to the hybrid map and made the site selection auto-fill the grid reference. 

Because of the way the form layout works, the easiest way to add a link to my sites would be to add a link just beneath the location control - something like "Manage my sites". Is that OK?

**Comment by davidnicholls125** [comment]
Yes that sounds fine thanks. We've lost the blue 'help' icon for the Site name field, can this be added back? I like the 'remember site' button that appears alongside the control when data has been added.
One thing I've noticed is that my browser no longer 'remembers' my previous entries. This is a really useful feature to avoid retyping names for sites I occasionally visit but wouldn't bother setting up as 'my sites'. Is this something that could be retained?

**Comment by johnvanbreda** [comment]
I've added the Manage My Sites link. Unfortunately because we are now using an auto-complete with drop down search results, that replaces the built in browser behaviour of remembering previous site names. Otherwise the 2 drop down boxes would clash and overlap each other.

**Comment by davidnicholls125** [comment]
Thanks John. I think it is reasonably self-explanatory as to how it works without adding any detailed guidance.
