### ISSUE TITLE
Notifications default

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#103]
As mentioned on the 100 species thread, we would like to have new registrations receive notifications as the default (including milestones). Our terms and conditions, accepted by all users, state that by opening an account they agree to receive communications from us. However in the welcome email it explains that they can change the options at any times by editing My Account. We are particularly keen to get this changed so that 100 Species participants receive the notifications.

**Comment by johnvanbreda** [comment]
This is 2-3 hours work, is it OK to proceed?

**Comment by davidnicholls125** [comment]
Just to be clear, this is a change to the default for all new registrations, not just those signing up to 100 Species. Does this make any difference to the time involved? I had expected it to be a simple switch....

**Comment by johnvanbreda** [comment]
No, that was my expectation. The difficulty stems from the fact that we just don't have any existing code linked to the registration process for setting the user's notification preferences, and it defaults to off until they change the settings on their profile later, for GDPR reasons. So we need a bit of new code to link the setting of notification preferences to the user registration.

**Comment by davidnicholls125** [comment]
OK thanks. In that case go ahead.

**Comment by johnvanbreda** [comment]
Acknowledged

**Comment by johnvanbreda** [comment]
I think I'm going to be working on this area of iRecord in about 1 month, so that's a likely timescale.

**Comment by johnvanbreda** [comment]
Working on this now.

**Comment by johnvanbreda** [comment]
Coding for this is now done, pending an update of the warehouse which will probably be next week.

**Comment by johnvanbreda** [comment]
This change has now been applied to the warehouse.
