### ISSUE TITLE
Wild Places issue

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#104]
Just noticed that the Brocks Hill Country Park Wild Place page says it isn't linking to a unique site on Indicia. This is probably because there are two entries on Indicia for Brocks Hill Country Park - one linked to NatureSpot and one not. I've tried to delete the version not associated but it won't save the change. Can you delete it please?
![image](https://user-images.githubusercontent.com/80914584/169806389-630d96e7-65e4-4359-ba9c-6425d0740968.png)

**Comment by johnvanbreda** [comment]
That's done.

**Comment by davidnicholls125** [comment]
Thanks
