### ISSUE TITLE
Wild Place missing records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#105]
The Wild Place page for Great Bowden Main St verge is showing zero records. However a survey was carried out in June 21 and these records are on the system. I can't work out why they aren't being detected.... the grid ref for these records clearly covers the verge boundary. Any ideas?
![image](https://user-images.githubusercontent.com/80914584/169978083-314beb53-da98-452f-be6e-547f48fc39b6.png)

**Comment by johnvanbreda** [comment]
I can reproduce this on the live server and it seems there is something going on with the Elasticsearch spatial indexing related to the polygon for this wild place specifically. I have also tried in a later version of Elasticsearch and cannot reproduce it. I know that Biren at BRC is looking into upgrading the Elasticsearch server and probably the version, so it may be worth checking with him regarding the likely timescales.

**Comment by davidnicholls125** [comment]
I've come across another Wild Place with same/similar problem, records are listed but the species count says zero.
https://www.naturespot.org.uk/Kirby_Muxloe_Glenfield_Lane_Verge
I emailed Biren but didn't get a response.
This is becoming urgent as we have a contract with the County Council to use the Wild Places as community engagement platforms for the verges project. The URLs are being promoted to residents so it's rather embarrassing if the pages aren't working properly. Is there anything to be done?
Incidentally, I tried to edit the boundary for this site on Indicia but it is impossible with the Open Street map to get it right. Can the hybrid map be added as an option? Thanks

**Comment by johnvanbreda** [comment]
The Kirby verge issue is because the filtering on whether to include a record in the species list, records list and species count blocks differ. 
* Records are included on the records list (bottom of tab 1) and species list (page 2) if they intersect the polygon and are not rejected.
* Records are included in the "Total species seen at this site" if they are verified and if the grid reference is 100m or less.

I suggest making these filters the same, or at least adding an explanation that the species count is verified only. Please confirm which filters to use.

**Comment by davidnicholls125** [comment]
Thanks John, that makes sense now. I agree they should be the same so please make the species count include all records that haven't been rejected.
Is there anything we can do with the Great Bowden Main St verge page mentioned above. Biren has not responded to my email.......

**Comment by johnvanbreda** [comment]
I've made the filters the same for all 3 blocks - exclude rejected and exclude grid refs > 100m precision. I've also emailed Biren.

**Comment by davidnicholls125** [comment]
The problem of the Wild Place page below remains. I've deleted the shp file and recreated it from scratch with a slightly different name which I've paired with WP page title. It recognised the map file but still doesn't show any records or images so it can't be the shp file not being recognised. I've tried setting up a new WP page and linking this to the new shp file but it hasn't made any difference. Every other WP page that I'm aware of is working so why just this page? I've had several emails from Great Bowden Parish Council about this as they have been using the WP page to promote the work on the verge to local residents. Biren didn't seem able to help, is there anything else we can try?
https://www.naturespot.org.uk/Great_Bowden_Main_St_verge

**Comment by johnvanbreda** [comment]
I've tried drawing that polygon in the iRecord Explore page and recreated the problem with no records coming back - so it's not a problem with your SHP file, but a "blind spot" of sorts in the Elasticsearch location indexing. So, I tried enlarging the polygon a little at a time until it worked and the smallest polygon that worked was as follows:
![image](https://user-images.githubusercontent.com/2392594/182793510-0f4a2b03-9d04-4bc3-a394-e1d32d7eb1ee.png)

Is a feasible solution to change to this polygon, at least while we wait for the Elasticsearch upgrade?

**Comment by davidnicholls125** [comment]
Thanks John, that should be OK as an interim measure. Will you do it or should I?

Dave

**Comment by johnvanbreda** [comment]
I've done that.
