### ISSUE TITLE
Species page update monitoring

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#106]
We are looking for a better way to keep track of which species pages have been updated and when. Is it possible to add fields, that we can include in the species page details download, to capture who last edited any text on the page and the date? Similarly we want to do the same for when the image organiser was last accessed and by who.
Text edit: who + when
Image organiser: who + when

**Comment by johnvanbreda** [comment]
I've added a Changed column to the view which gives the date& time of the last edit. Unfortunately Drupal does not store the username of the last edit unless you turn on "node revisions" which means it will turn on a revision history for the species data. You can read more about this at https://www.drupal.org/docs/administering-a-drupal-site/node-revisions - let me know if you would like me to turn it on. Note this will cause additional data to be stored in the database as it keeps a copy of the previous state of each species account when you edit it - this won't impact things much unless there are thousands of edits though.

**Comment by davidnicholls125** [comment]
Thanks. I think the revisions option would be useful so let's turn it on.
A while ago I added a 'last checked' field (as below) but this has to be manually updated (not everyone remembers) and doesn't tell you who made the edit. We could remove this if a better option can replace it. I can't see the 'changed' column you have set up...? Can we have a separate 'updated' fields for the images? The drupal node revisions page says that the revision message to briefly explain what change has been made can be made a mandatory field. This is probably worth doing.
![image](https://user-images.githubusercontent.com/80914584/170208947-573821f6-8cd0-4f3d-9531-a8614f56fe7e.png)

**Comment by davidnicholls125** [comment]
Are you OK to proceed with this?

**Comment by johnvanbreda** [comment]
Revisioning is now turned on for species accounts and images. I've added the latest revision author to the download - this is effectively the person who last saved an edit. It's not so easy to put the last editor of the images into the same download though, but at least the information is available.

Some of the revisioning on Graphopsocus cruciatus is just me testing things.

**Comment by davidnicholls125** [comment]
Thanks. Can we add the date that the species page was created to the download please? (so we can see how long it has been since it was checked).
Also, where do we get the last editor of the images from?

**Comment by johnvanbreda** [comment]
I've added the created date to the species account data download. I've also added a similar download for the raw image data to https://www.naturespot.org.uk/all-species-account-images which includes the create and update metadata.

**Comment by davidnicholls125** [comment]
The csv button on the link above doesn't work... it just brings up a blank page.

**Comment by johnvanbreda** [comment]
I've switched to batch mode with a progress bar as it was running out of memory due to the number of images.

**Comment by davidnicholls125** [comment]
Thanks. It took 5-6 mins but OK now.

**Comment by davidnicholls125** [comment]
Can the format of the 'update on' field be changed to a simple date - the same as used in the 'date' field please. I've tried reformatting in Excel but can't find a way.

**Comment by johnvanbreda** [comment]
Done - I've also updated the created on plus both fields on the species details download view.

**Comment by davidnicholls125** [comment]
Thanks John. When the person last updating the images says 'Anonymous', what does this mean?
Also, the earliest date on the page last updated field is 27th April 2021 which obviously limits its usefulness. The image update field however goes back many years. Is there any way to address this? (I imagine 27th April was a site-wide upload though I can't recall what!).

**Comment by johnvanbreda** [comment]
Anonymous images will be those added by the background process - remember that it used to add all the images so you could organise them, now only those that an editor adds to the species account are actually imported by Drupal.

I've added last updated to the species details view which gets the revision create date, but I don't think that's useful for data that hasn't been updated since the revisioning was turned on. If all the species accounts were amended on the 27th I'm not sure that I can do much about that as it will have overwritten any metadata stored about previous updates. I don't think I was working on the site on the 27th April so I'm not sure why this happened.

**Comment by davidnicholls125** [comment]
OK, thanks.

**Comment by davidnicholls125** [comment]
I've been analysing the species and image updates. Is it possible to just report on the most recent update date rather than all the dates when every image was moved? I've managed to do this in Excel but it's not straightforward.
Re-reading the notes above, you changed the data format in the species page download to a simple date format in July but it has reverted to date + time. I reported this as a new issue yesterday but I'll close that issue and leave it here to be reset again. Do you know why it has changed? We don't want to be having to redo these changes....
Also is it possible to add the taxa to the species page download? At present it only shows title and common name.

**Comment by johnvanbreda** [comment]
I've reset the date format. It's possible this changed as a result of the recent upgrades, if so it is probably a one off due to a change in the Drupal internals, not something I would expect to happen again.

The taxon is already a column in the species page download isn't it? Just to the left of created on/updated on.

Can you explain the request for the most recent update date in the first sentence a bit more please?

**Comment by davidnicholls125** [comment]
Thanks.
The current image update report lists every published image with the date each was moved. We really only want to know the most recent date when any image was moved (ie when the images were last reviewed). Is it therefore possible just to filter the report to show this latest date for each species (plus the person who updated it)? I've also realised that for many species when we review the full list of images the current selection is OK and doesn't need changing - but this review isn't captured on the report. Would it be possible then to log the last date when the organise images page was visited rather than focussing on individual images?

**Comment by johnvanbreda** [comment]
@davidnicholls125 no, unfortunately I don't think it's easy to build a report in Drupal's views that does either of those things unfortunately. Drupal doesn't log visits itself, so you need to go into a web analytics tool like Google Analytics to extract any visit information and I can't find a way to aggregate the report so it only shows the most recently updated image.

**Comment by davidnicholls125** [comment]
OK thanks. With a bit of work I can use Excel to extract the latest update date for each species page so we can make do with this.
