### ISSUE TITLE
Record download

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#108]
Is there any way the elasticsearch record download can include the NS taxon groups rather than those used by iRecord? We often resort to using the old download tool, despite elasticsearch being much quicker. There will be some taxa that don't match to our dictionary so I guess these can stay in the iRecord groups. Thanks.

**Comment by johnvanbreda** [comment]
I've added a NatureSpot group column to the Elasticsearch download. For species that don't match to your dictionary it will show the UKSI group name.
