### ISSUE TITLE
Image download

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#11]
We discussed needing a new image download facility to identify species with/without images. (The current download is slow and limited so an elasticsearch version would be a big improvement). Can we also identify if there is a published image in the gallery section?

**Comment by johnvanbreda** [comment]
Is this a download of the images linked to the Drupal species accounts? I.e. species name, image filename, priority information?

**Comment by davidnicholls125** [comment]
No, a download of all images attached to records. It's to replace the existing image download tool. 
https://www.naturespot.org.uk/content/all-images
Just record ID, species name and image name would be sufficient I think. We want to know which species have images and how many. However it would be useful to get a list of drupal species pages without published images to compare with this (we know some species pages get set up but due to verification delay we forget to add the images).

**Comment by johnvanbreda** [comment]
Does it matter if there is 1 row per record that has images, then a comma separated list of the images attached to that record? Or do you need records with multiple images separated into multiple rows? 
Also for the image name, do you mean the image file name?

**Comment by davidnicholls125** [comment]
Probably OK to have 1 row per record with listed images. Yes image file name please.

**Comment by johnvanbreda** [comment]
Here you go @davidnicholls125 - https://www.naturespot.org.uk/download-images. I left the search facilities in place in case they are useful.
There is a little more info in the media files column. The format is image name, then caption, then licence (if specified), each separated by semi-colons. Multiple images are separated by |.
