### ISSUE TITLE
Wild Places image display order

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#110]
The image display on the Wild Places page appears to be ordered oldest first, rather than latest first. On the page below, the record images from yesterday are appearing last whilst those from last year are on the first page. Please can you reverse the order (assuming this is the problem). Thanks.
https://www.naturespot.org.uk/Houghton_Uppingham_Rd_verge

**Comment by johnvanbreda** [comment]
The sort was specified using the verification date, but as the latest images shows unverified data, the unverified images weren't correctly sorting. I've changed this to sort them on the record creation date, most recent first - is that what you want?

**Comment by davidnicholls125** [comment]
Thanks John, yes that's good.
