### ISSUE TITLE
Record download for Wild Places

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#112]
On the old record download we have a dropdown filter for all the Wild Places. Can this be added to the elasticsearch record download page?

**Comment by johnvanbreda** [comment]
It's do-able but requires some new code - about 3 hours max.

**Comment by davidnicholls125** [comment]
OK, go ahead please.

**Comment by johnvanbreda** [comment]
Done

**Comment by davidnicholls125** [comment]
I've just gone to download the records for one of the wild places but can't see the drop-down menu/filter on the elasticsearch download records page. Has it disappeared or am I missing something?

**Comment by johnvanbreda** [comment]
There is an error about the [locationSelect] control being missing from the code on the page. I think at some point a backup of the code has been restored which overwrote this change (which would tie in with an issue I was working on this morning being a repeat of a previously fixed issue). 

Is it OK if I take the site offline for half an hour or so to do an upgrade to the latest Indicia code tomorrow?

**Comment by davidnicholls125** [comment]
Yes of course.

**Comment by johnvanbreda** [comment]
Done
