### ISSUE TITLE
Attribute field

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#115]
Would it be possible to make Attribute a required field and not accept 'Not recorded'? Probably we would want to change the default entry to 'please select'. We regularly get feedback from County Recorders bemoaning that larvae are not distinguished from adults. I think the attribute field is only set up for insects so it wouldn't affect other taxon groups.

**Comment by johnvanbreda** [comment]
I can make it required just for insects and remove the not recorded option. However making the control show -please select- when nothing is selected is going to take a couple of hours to code. Shall I do that?

**Comment by davidnicholls125** [comment]
Yes go ahead please.

**Comment by johnvanbreda** [comment]
This is now done.
