### ISSUE TITLE
TVK question

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#116]
A number of moths have had name changes and we want to update these (shown below). I know we can easily amend the names but I recall that changing the TVK is more problematic. Please can you clarify if there are any issues with us amending the TVKs as well as the names? Thanks.
![image](https://user-images.githubusercontent.com/80914584/190438130-edf8e66e-2eaa-4cd0-982a-d588facdced5.png)

**Comment by johnvanbreda** [comment]
One issue I can foresee is that the iRecord UKSI copy also needs an update, so if you proceed before iRecord is updated it won't be able to map your names to the UKSI name. This means that things like the higher taxonomy info (ability to filter by a higher taxon, or view the family name etc) may not work.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I'm not sure if you saw the response to this. I've looked again at the data and the first 2 species listed should be OK as the older copy of UKSI contains the TVK as a synonym, so the mapping will work. For the other species the mapping won't work, but this only affects the higher taxonomy associated with the record - the record remains valid so this may not be a major problem.

If you do make any changes, let me know which and I can check that everything has updated in the system as expected by a few hours later.

**Comment by davidnicholls125** [comment]
Sorry if I'm a bit slow on this issue, I know it has been raised before but I'm still not clear. Previously when we have changed the TVK (because for some reason the new synonym has been given a different TVK)  it has sometimes necessitated the redetting of all the records on the old TVK. Are you saying that sometimes it does and sometimes it doesn't? How will we know? And if it does require redetting how best should we do this, especially when there are lots of records?
I've seen this from you on a previous related issue:
_Yes, if you change a species TVK using the warehouse user interface, then the previous records are queued for an update (similar to the way I queued records in https://github.com/johnvanbreda/naturespot-d8/issues/95)._
Does this mean that all changes to TVKs will be updated, albeit with a possible delay whilst queued?

**Comment by johnvanbreda** [comment]
Do you have any correspondence or other info regarding the case when you had to redet the records? I would normally not expect this to be necessary, though it may have been required for a certain circumstance. If you can let me know the details then I'll be able to work out the reason and explain when it will be necessary (and perhaps provide a script or tool to help).

**Comment by davidnicholls125** [comment]
Sorry, I updated my previous comment as you were replying. OK we'll go ahead with the changes and I'll let you know of any that don't get updated. Thanks.

**Comment by davidnicholls125** [comment]
I amended the names and TVKs on the moths listed above on Friday evening and Saturday morning. However none of the records are now listed on the verification page under their new names. Are the in a queue awaiting the update or is it not working?
Another related issue is that the images for Protodeltote pygarga (was Deltote pygarna), Marbled White Spot, have disappeared from the species page, except for four images (there are lots more with records for this species). I recall that when I went to change the name in the drupal taxonomy there was a duplicate entry, which I deleted so now I'm thinking that the other images were linked to this. Could you relink all images please?

**Comment by johnvanbreda** [comment]
I did find a problem in the warehouse where the name updates would apply to accepted names, not synonyms or common names - which I've fixed. That may have explained some of the issues you've observed, also it may have been catching up slowly.

A name is looked up in UKSI (using the name TVK) and if found, the taxonomy for that TVK is used in Elasticsearch. So, although your list has Callistege mi as the accepted name for Euclidia mi, it will be treated using the old UKSI interpretation, hence the accepted name shown won't update. This is the case for the first 2 names on the list but the others are now correctly updated I think.

The Marbled White Spot species page now has quite a few images on the organise images page so let me know if that's not roughly the number you'd expect.

**Comment by davidnicholls125** [comment]
Presumably this is because Euclidia mi and Deltote pygarna haven't been updated on the UKSI? The problem for us is that if you want to bring up the records for a given species on the verification page you won't be able to find them. Will they update automatically in the future when the UKSI is updated?

**Comment by johnvanbreda** [comment]
They will indeed be updated when UKSI is updated. Searching by common name (e.g. "Mother Shipton") is one possibility as it gets around the name change, though I appreciate the verifiers may not think of this.

**Comment by davidnicholls125** [comment]
Thanks.
