### ISSUE TITLE
Submit records form problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#119]
It isn't possible to type '+' into the species box on the records form (+ new species). All other symbols seem to be OK, just not + or -.

**Comment by johnvanbreda** [comment]
I'm not able to reproduce this:
![image](https://user-images.githubusercontent.com/2392594/193461634-e8c127f8-643b-4032-8c0f-0363fad34561.png)

**Comment by davidnicholls125** [comment]
I've just tried and it is working now. Very odd. Thanks for checking.
