### ISSUE TITLE
new account applications

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#12]
We are receiving around 20 spam account registration applications every day which is becoming a burden to filter out and cancel. They are easily recognised in most cases as the first and last name entries are identical. This is despite have recaptcha installed on the form. Would it be possible to automatically cancel any application if the first and last name entries are the same? It might be better to do this post-submission rather than make different entries a requirement on completion as I fear this would lead to a new wave of spam applications with different first and last names.

**Comment by johnvanbreda** [comment]
A more traditional way to try and sort this would be to use alternative or additional spam blocking approaches on the user registration. I've just enabled a module called honeypot on this form (it was enabled as a module, but not enabled for the user registration form for some reason). That module is not perfect but does provide an additional layer so may work well in combination with reCaptcha. Shall we give this a go before trying any custom solutions?

**Comment by davidnicholls125** [comment]
Of course! We hadn't realised there was more protection on offer beyond the recaptacha inclusion. It will be easy to monitor as I'm doing all the daily approvals.

**Comment by davidnicholls125** [comment]
Did you enable honeypot? We are still getting a lot of spam applications!

**Comment by johnvanbreda** [comment]
Yes.

A bit more investigation - the Recaptcha module has this issue: https://www.drupal.org/project/recaptcha/issues/3074204. Also the link from it to a duplicate issue, indicating that Google Recaptcha v2 is no longer effective as spammers are now able to bypass it. 

So, I think the options are - either install additional https://www.drupal.org/project/recaptcha_v3 as suggested at the bottom of the thread, or we can revert to a standard Maths type challenge which might be more effective.

Let me know.

**Comment by davidnicholls125** [comment]
I've installed and enabled recaptcha v3 but can't see how to set it up, could you do this please?

**Comment by johnvanbreda** [comment]
The module wasn't enabled - now done. I've set up an "action" for the register form with a score of 0.5 - I think we can tweak this if it still doesn't work (higher would be stricter).

So - we now need to see what happens....

**Comment by davidnicholls125** [comment]
Thanks John, I ticked the box but maybe I didn't save it? I'll let you know how it goes.
