### ISSUE TITLE
Record data analysis - estimate

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#120]
We are working on a grant application to add an analysis of the record data to each species page so would appreciate an estimate for this, ideally broken down so we can, if needed, phase the work. 
1. List records at bottom of species page as on Parish/Wild Places pages
2. Create a new section above the images: 'Species Data Profile'
a) No. of records on NatureSpot: XX (Also no. on ORCA – updated annually from spreadsheet)
b) Last record: Date, Recorder
c) Bar chart: records by month
d) Bar chart: % species records within its taxon group by year (last 10 years?)
e) Bar chart: no. of 10km squares with species records by year (last 10 years?)

In due course we would like to add a conclusion regarding whether the species is increasing/decreasing + expanding/contracting, but this will need more thought.

**Comment by johnvanbreda** [comment]
Estimate sent

**Comment by davidnicholls125** [comment]
Thanks.

**Comment by davidnicholls125** [comment]
We'd like to go ahead with this. The record list at the bottom of the page has already been actioned so just the additions listed in number 2 please.

**Comment by johnvanbreda** [comment]
Should the data profile contain all records excluding not accepted, or just accepted (verified) records?

Here's a mockup of what I've achieved so far, showing the data for Great Crested Grebe. Please let me have any comments so that I can complete the work:

![image](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/ecd3b56e-08b9-4efc-9e3b-ef14c3fc2e00)

**Comment by davidnicholls125** [comment]
Thanks John, it looks pretty good. I've sent it to Alan to get his thoughts as he has now taken over as chair. I think we should only include accepted records.
Will the scale of the bar charts adapt automatically if there are very different figures emerging? Might be worth looking at how it works for say Common Earwig (very small group) and Blue Tit (very many squares).
Can we also add First record: date + recorder.

**Comment by davidnicholls125** [comment]
Can we call it 'Species Profile' rather than 'Profile Summary'.
We are not sure if it would be best as a collapsible section, though on balance I think it is better displayed as the default. Could it be a collapsible section? If so leave it displayed as a default but with the option to contract perhaps.

**Comment by johnvanbreda** [comment]
I've coded it now and embedded it on the species pages, but it's hidden until you've confirmed Alan is happy with it. Clicking on the Species data profile will collapse the block.
The Earwig report and Blue Tit reports are below - the scales are dynamic but I wonder if I should set the percentage bar to 100% always?:

![image](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/6f09dbd7-9624-44a4-b8a7-1185b5f4313c)

![image](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/5feae8a8-6916-43c4-ada0-c3b5bb4318d6)

**Comment by davidnicholls125** [comment]
Thanks John. I'm confused by the records by month graph - for Blue Tit is suggests there are no records in July and August but this isn't the case..... 
Is it possible to display First record: 14/11/1993 (Ian Retson)
then the same for last record?
Perhaps leave the percentage axis dynamic for now?

**Comment by davidnicholls125** [comment]
A couple of other minor things. The UK map needs to be aligned at the bottom (it was until I moved the block explaining the verification status of the images and records). Also, I think we need to have an explanatory page for the new data analysis section so could you add a question-mark icon and link it to this page please: https://www.naturespot.org.uk/species-data-analysis

**Comment by johnvanbreda** [comment]
I've fixed the missing months - I hadn't realised but the default limit was to load data for up to 10 months.
I've changed the display of first and last record.
I've enlarged the VC map so the alignment is better.

Still to do - a ? help link.

Also - just a thought as the Species profile box is quite sparse now. We could show some other taxonomic info (kingdom, order, family would be very easy, but a whole taxonomic tree is possible). We could add the accepted name and accepted common name, plus list all synonyms and common names from UKSI. Just a thought, you might prefer to keep it simple.

**Comment by davidnicholls125** [comment]
Good idea, yes add kingdom, order and family. We do have a few groups with tribes (eg hoverflies) but this isn't critical. Common names would be good too but leave out synonyms I think. 
In time we have other things we'd like to add (pending more statistical analysis of the data) but we can juggle entries if and when we are ready with this.
We are happy for it to go live as soon as you think it is ready.

**Comment by johnvanbreda** [comment]
I've added the help link, common names and taxonomy. I've now made the species data profile visible so it is live.
