### ISSUE TITLE
Verification page very slow

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#121]
In recent weeks the verification page has been so sluggish at times it almost becomes unusable. In particular, once a record has been verified it does not always disappear from the list, even after a few minutes. The example below is still showing nearly an hour after I verified it. It is confusing then to know which records have been done and which still need review. I've noticed that some records are being verified more than once, presumably as a result of this. Also the query button doesn't always work and it takes quite a while for the filters to return the display. 
A further issue is that when a record has been verified and you click on another record to highlight it, then that record can disappear instead of the one that has been verified.
![image](https://user-images.githubusercontent.com/80914584/194060405-33b9c69c-3773-4f76-a412-75972709af27.png)

**Comment by johnvanbreda** [comment]
Is this for the verification page at https://www.naturespot.org.uk/verification-v2? 

2 things here - if we upgrade the Indicia code, the user interface is improved when a verification is slow in that the record "greys out" and you can continue with other records. That will take me half an hour or thereabouts so let me know when is (or isn't) a good time to take the site offline to do this.

Also, BRC are aware that the Elasticsearch server which drives this page needs an upgrade, I've sent Biren a request for more information on the timescales.

**Comment by davidnicholls125** [comment]
Yes that page. Go ahead whenever it suits. If you can give me a day or two warning I can let the verifiers know.
An elasticsearch upgrade is sorely needed! Lots of pages with elasticsearch functionality are really slow! Thanks.

**Comment by johnvanbreda** [comment]
One tip regarding the verification v2 page in particular - if you use the layers button on the map to turn off any layers you don't need it can help with performance. I can schedule the update for Monday if that suits you?

**Comment by davidnicholls125** [comment]
Thanks John. I've turn off every layer, selected 6 records from the grid and accepted them. 10 minutes later they are all still displaying, even though comments for each record says they have been verified. It's pretty hopeless!

**Comment by johnvanbreda** [comment]
I just masqueraded as you and verified a single record of a Red Admiral with photo, having the grid map of currently selected species still on the map. It took about 1.5 seconds to verify the record and select the next row and the record was removed from the grid. 

Perhaps best to try this again after I get a chance to upgrade it - hopefully tomorrow.

**Comment by davidnicholls125** [comment]
OK will do. Single records were OK, it was when I used the tick boxes for multiple records that it froze (those 6 records are still displaying now....).
