### ISSUE TITLE
100 species list

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#123]
The list of participants signed up to the 100 Species challenge appears incomplete. John Alton is signed up but isn't on the list. I know he has downloaded his certificate, does this make any difference? (it shouldn't as we need all participants listed).
https://www.naturespot.org.uk/100-species/members-list

**Comment by johnvanbreda** [comment]
He's not on the list because the 100 species member box at the bottom of his profile isn't ticked - do you know why?

**Comment by davidnicholls125** [comment]
Thanks. Probably just an omission. I've been through all of the participants and found a couple of others too so have ticked these.
