### ISSUE TITLE
Downloading parish records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#125]
We want to be able to download all the records for a given parish but I'm not sure how to do this..... We have the recent parish records displaying on the parish pages so presumably the filter exists. Is there a way to pull these off as a csv?

**Comment by johnvanbreda** [comment]
I've added a parish drop down to https://www.naturespot.org.uk/download-data-v2, which acts in the same way as the wild place drop down.
