### ISSUE TITLE
Adding latest images and records to the species pages

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#128]
We would like to add latest images (1-2 rows?) and a list of latest records to the species pages - as we do on Wild Places pages. If this is a relatively simple job (<2 hours) please go ahead, otherwise can you let us know the cost? Thanks.

**Comment by johnvanbreda** [comment]
I think that can be done in < 2hrs. Where would you like it on the page (or on an additional tab)? Does the block need a heading making the separation between the selected species images and the record images clear? Finally - should this be verified records only?

**Comment by davidnicholls125** [comment]
Great, thanks. Add the sections to the bottom of the species page, just as we do on the Wild Places pages. Could you also look at #124 which is linked? Part of this request is to add a symbol to each records indicating its verification status (usual ticks, etc.). We can do the same on the species pages and include all pending and accepted records (excluding rejected or plausible).

**Comment by johnvanbreda** [comment]
Done. The number of image rows is the same as on wild places (about 3 if logged in, or more if not as the pager is removed). Let me know if this needs to be tweaked.
