### ISSUE TITLE
Parish page species count

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#129]
We've received the comment below. Please could you check why there is a mismatch? I've not checked but the species count on the Wild Place page may be similarly set up. Thanks.
The Houghton species list shows 237 hits, but the statistics indicate only 225 species. Looking at bugs, the species list has 4 species, but the statistics show only three. The count for flies also does not match, So it seems as if the species list is correctly updating from the raw data, but the statistics are not updating

**Comment by johnvanbreda** [comment]
The Statistics tab shows only verified records, the species list includes all records except rejected. In the case of the bugs, there are a few plausible records of Notonecta glauca which cause the difference. Shall I make these 2 tabs match in the filter they use and, if so, which filter would you like?

**Comment by davidnicholls125** [comment]
Thanks. Yes I think it would clearer if they matched. Let's just include accepted records (excluding both pending and plausible).

**Comment by johnvanbreda** [comment]
That's done. I also fixed a discrepancy due to the handling of minimum 100m precision records being included. I updated the count on the first tab to use the same filtering but this count is based on distinct species concepts, not distinct taxa, so will be slightly less. For example, an unidentified bat, or a genus, a species aggregate or similar will all get counted on the Species and Statistics tabs but don't get counted on the first tab.
Should we also try to make this consistent (or at least add an explanation somewhere)?

**Comment by davidnicholls125** [comment]
Thanks. It would definitely be good to make all the species counts consistent, ie based on all taxa, not just full species. I think you explained previously that the home page total, and that on the parish/WP main tabs, is generated by elasticsearch which can only count full species. If we changed this to use the same filter would it affect performance greatly? Could this be minimised by only updating once a day?

**Comment by johnvanbreda** [comment]
@davidnicholls125 no, the Elasticsearch reports can count species concepts, or all taxa. It's just the old reports that can't (easily) count species concepts. So I can switch the count on the front tab to count all taxa, as long as you are happy that higher taxa or sub-species mean this won't be an exact species count?

**Comment by davidnicholls125** [comment]
If I download the Indicia list of taxa that we have set up, will this be the list that is counted? If so, I'll have a quick look and check we want this total.

**Comment by johnvanbreda** [comment]
Can you provide the link to the specific download you are referring to please? There have been a few!

**Comment by davidnicholls125** [comment]
[www.naturespot.org.uk/species-list-content](https://www.naturespot.org.uk/species-list-content)
This is an odd report in some ways as all synonyms, common names and scientific names are on separate rows but I think it is a comprehensive list of all taxa we have on Indicia.

**Comment by davidnicholls125** [comment]
This might be easier - the report downloaded just over a month ago with the synonyms and common name entries removed.
[Indicia taxa list 7Nov22.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/10288087/Indicia.taxa.list.7Nov22.xlsx)

**Comment by johnvanbreda** [comment]
As ever, things are more complex when you look into it. A couple of the examples of differences from the Houghton on the Hill data are genus level records of Eupeodes and Sphaeophoria. These both must have been added via the app as the names don't exist at genus level in the NatureSpot list, so they haven't been mapped across. Therefore they don't actually appear in the download. 

Anyway, the count on the first tab is now showing the same count as the other tabs, as it includes all taxa, not just species level concepts.

**Comment by davidnicholls125** [comment]
Thanks. That's fine for the parish and WP pages. I'm just getting the views of the other trustees about the overall species count on the home page so will get back to you on this. Can we pull off a list of all taxa, basically a NS wide total, similar to that available on the parish/WP pages?

**Comment by davidnicholls125** [comment]
The consensus is to go with the same filter as used elsewhere, ie include all taxa in the total. We need to add a ? icon (or something similar), linking to a explanatory page, that appears with al the species totals (home/wild place/parish).

**Comment by johnvanbreda** [comment]
The home page filter was set to count the distinct taxa in your warehouse species list, but I've switched this to use the same logic as on the places pages so it counts the distinct taxa recorded. It is slightly higher because of the odd taxa that don't migrate between the app and NatureSpot properly (aggregates etc).

There is already a ? link to the species counts explanation page so closing.

**Comment by johnvanbreda** [comment]
Re-opening as the count only works first time after a cache refresh due to resource loading. Looking into it...

**Comment by johnvanbreda** [comment]
Have reverted the change as Drupal's library system isn't behaving on the count block, so the idcCustomScript class is only sometimes available. Will revisit...
