### ISSUE TITLE
iRecord species dictionary on the NS app

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#13]
We've received a number of records submitted via the app, but all are listing species entries from the iRecord list and not the NS list. Shouldn't the species get moved onto our species list? 
![image](https://user-images.githubusercontent.com/80914584/113341769-7a4ef500-9325-11eb-9b20-7ab4e0537fac.png)

**Comment by johnvanbreda** [comment]
The automatic names mapping will only map names when it is certain they are correct, and leaves names on UKSI if there is a risk of  changing the meaning of the record. Generally that means it needs a more-or-less exact name match as well as TVK match. 

In the case of Arion (Arion) ater, the NS name is Arion ater sensu stricta. Likewise, there is no equivalent for Arion (Carinarion) circumscriptus silvaticus as your version is Arion silvaticus.

I can make the mapping tool ignore the taxon name if it is different, and just map across on the basis that the TVK is correct, but that does bring risks (e.g. in the case of incorrect TVKs).

**Comment by davidnicholls125** [comment]
Perhaps lets hold fire on this whilst we decide whether to adopt the UKSI on NS as this would eliminate the problem if we do.
