### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#133]
How often should the dashboard stats update? The totals on my dashboard are not including the records I submitted yesterday after nearly 24 hours. Can we set the refresh rate? Hourly perhaps?
FYI - currently the dashboard summary for 2023 states 141 species, the species list download shows 147, the summary says 148 are under review.

**Comment by johnvanbreda** [comment]
Before I look into this, did you try clearing the Indicia cache to ensure that it is the issue? 

The timeout on the cache is only set to 5 minutes, but as mentioned before, once the timeout expires we don't actually automatically update everything - there is also a random element to ensure that everything doesn't update at the same time. So it may take a few page loads to get the figures to update.

**Comment by davidnicholls125** [comment]
I tried adding ?nocache to the URL and reloading - this didn't make any difference. I've just cleared the full Indicia cache and it added 2 species I submitted an hour ago but still doesn't show the correct total.

**Comment by davidnicholls125** [comment]
Just had another look, 24 hours after my last record submission. I've downloaded my 2023 records to compare the actual totals with that shown on the summary tab. The number shown as pending is correct. The total number of records is also correct. The total number of species however should be 163 but only 158 is showing. 
One other thing, when I downloaded my records the status and images columns didn't have any heading title - could you add these please?

**Comment by davidnicholls125** [comment]
I think the disparity in the species total may be due to only counting full species and not all taxa. There is currently a difference of 6 when comparing my 2023 record download with the total shown on the dashboard summary. I've attached the list and highlighted 6 taxa which may not be in the count. We agreed a few weeks ago to standardise all the species counts and base these on all taxa but I think this is still outstanding. Can you go ahead with this please?
Also note the missing column headers mentioned above in the download.
[2023 species total.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/10507375/2023.species.total.xlsx)

**Comment by johnvanbreda** [comment]
I've done that - there were a few reports that counted the species level on this page, so I've changed them all to use the accepted taxon except the 100 species report (as that probably is supposed to be about finding species, not taxa at an level).

There is still a discrepancy of 1 with your 2023 data but that is because the first tab report excludes rejections, whereas My Species includes them.

**Comment by davidnicholls125** [comment]
Thanks. What does the home page total actually count? It currently says 7285 but there are 7230 unique taxa on the Drupal download and 7552 taxa on our Indicia list. I think it should be the Indicia total we use. We do need a link to an explanatory page with the total. Can you add a ? icon (or something similar)?
Is it the download of the My Species tab that includes rejections, I'm not clear? I think it would make more sense to exclude all rejections from the species list.
Can you also add the missing headers on the record download please?
Also exclude the entries below from the species download.
![image](https://user-images.githubusercontent.com/80914584/214857635-8a343b2d-df6d-4a48-8b15-b27a018f2903.png)

**Comment by johnvanbreda** [comment]
The home page was a count of unique species actually from the recorded data. It may also have been distorted by any app records that had not been transferred over to NatureSpot yet. I've switched to a simple count of taxa on the NS species list on the warehouse.

Yes, we could add a ? icon - with a tooltip, or click on it to go to a help page. Let me know.

The species list download now excludes rejected records.

I've added a header to the status column on the records page.

I think the species download already excludes ? and + new species - are you still getting these in downloads? If so which user account can I use to see the problem?

**Comment by davidnicholls125** [comment]
Thanks. Can you add a ? icon and to: https://www.naturespot.org.uk/species_totals
The species download I clipped and sent to you was done yesterday but I've tried now and those two items aren't included.... odd! I'll let you know if they reappear.

**Comment by johnvanbreda** [comment]
That's done

**Comment by davidnicholls125** [comment]
Thanks.
