### ISSUE TITLE
TVK change not updating?

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#135]
A few days ago we changed the name and TVK of the Bromus hordeaceus subsp hordeaceus records to that for Bromus hordeaceus. 50 of the 118 records now appear as the 'new' species but the rest still show as the subspecies. I think you said that records will automatically update when the TVK is changed but it has been stuck on 50 for the last day or two. Do we need to be more patient or is there something else we need to do?

**Comment by davidnicholls125** [comment]
I've just checked again and there has been no further updating. Please can you check why this is?

**Comment by johnvanbreda** [comment]
I've pushed the updates through. I can't see for sure why they didn't in the first place - it seemed that the records recorded against the accepted name worked but not those recorded as common names etc. The code looks like this should be handled though, will revisit if it happens again.
