### ISSUE TITLE
Wild Places boundaries missing from Submit Records map

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#136]
Just noticed this. Could you check please?

**Comment by johnvanbreda** [comment]
The layer is still loading from the server OK, but not showing on the map. I'm trying to work out why...

**Comment by johnvanbreda** [comment]
I'm curious to know when this change occurred as the config was wrong, but I've set the layer up again. I used a red outline to match the Wild Places map.

**Comment by davidnicholls125** [comment]
Thanks. I only noticed it today so I don't think it has been that long since it changed. Maybe when you removed the infill?
