### ISSUE TITLE
Redetermination by national verifiers

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#14]
We have a regular issue with national verifiers redetermining records onto the iRecord species dictionary. Sometimes these species are new to NS but we are unaware of the change. If the record is then verified it won't get set up with a new species page. Is there a way we can receive a notification when a record is redetermined onto the iRecord list?

**Comment by johnvanbreda** [comment]
Yes, we could use the Indicia alerts tool to do this. 1-2 hours work.

**Comment by davidnicholls125** [comment]
Thanks. Please go ahead.

**Comment by davidnicholls125** [comment]
Today we have the latest image on the home page being a species that isn't on our system and not from VC55. 
It was submitted via the app - does this mean that the app is using the iRecord species list? 
Recently we queried a missing image from the species page and you explained that it was because it was just outside VC55. If we can prevent non VC55 images from being added to the species pages can we also prevent them from appearing in Latest Images?
![image](https://user-images.githubusercontent.com/80914584/118260127-d9b62e00-b4a9-11eb-98cd-e208a40cf184.png)

**Comment by davidnicholls125** [comment]
I also noticed that this record can't be found on the elasticsearch verification page but is available on the old NS version.

**Comment by johnvanbreda** [comment]
@davidnicholls125 Yes, the app is using UKSI and we can't change that without building our own app version which would be very costly. The code works in the background by re-assigning app data to the NS list, but this will only work where a mapping exists, so in some cases the original species data get left associated with the record.

I've changed latest images to VC55 only as that was fairly easy.

Note to self - notification for UKSI redeterminations still to do.
