### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#147]
The species/records on My Dashboard is not updating. The last record showing on mine is 25/02/2013 yet there have been numerous records added since then, including 20+ yesterday. I've tried viewing the ?nocache option but this hasn't made any difference.

**Comment by johnvanbreda** [comment]
I think the Elasticsearch feed had stopped - I've restarted it so the records should arrive in an hour or two at most.

**Comment by johnvanbreda** [comment]
Records now appearing so closing...
