### ISSUE TITLE
Gallery images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#148]
We sometimes want to display more than one image in the gallery (eg. adult & nymph) and want to control the order - eg. adult first. I think the order is currently determined alphabetically by image/file name within the same priority category. Is there an easy fix for this where we can determine the order ourselves. For example is is possibly to change the filename on the database as well as on the species page?
Ideally we would also like to be able to show different RAGs (where relevant) for each gallery image. Is there a way to do this? The warning triangle is an OK compromise but it would be much better to show the relevant RAG.

**Comment by johnvanbreda** [comment]
@davidnicholls125 if you output more than one image for a single species, I don't think the gallery view will actually apply any sorting to the images within the species. That means the actual sort order will be whatever the database engine's query planner decides, which might be the filename, or often it would be the creation order or something like that. 

To control the sequence I could force it to sort by file name, but I think perhaps an optional "gallery image weight" field could be added to the image which you can use to control the order. That would be tidier than messing around with file names I think.

The identification difficulty RAG info is currently only attached at the species level. Perhaps an idea would be to replicate this field in the image, which would override the RAG provided for the species if set. You only then need to set it where the image appears in the gallery and shows something that has a different difficulty to the species generally.

That all sounds like 2-3 hours work as a ballpark.

**Comment by davidnicholls125** [comment]
Thanks John. Please go ahead and make the changes.

**Comment by johnvanbreda** [comment]
I've added the Gallery Image Weight field and configured the view so it controls the sort order of species with multiple gallery images.

I've also set up an identification difficulty for individual images which will overlay the species one on the gallery pages if specified.

**Comment by davidnicholls125** [comment]
Thanks. The RAG rating over-ride doesn't work when we already have a RAG with the exclamation mark symbol, eg, below for Trioza remota.
Also, can we make the weight order of multiple gallery images have the same effect on the species page? If we have 2 or 3 gallery images ordered specifically we really want this to be the same on the species page (ie those selected in the gallery section with priority 1).
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/1506db88-16c5-4529-b574-c3cc555a4743)

**Comment by johnvanbreda** [comment]
Both issues now sorted.
