### ISSUE TITLE
Records form - image loading problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#149]
The problem mentioned before continues... on the records form, images won't load at times - I think it is when there is a comment entered before the images are added. I experienced a similar problem earlier today when trying to edit a record.
However it doesn't happen every time! 
![image](https://user-images.githubusercontent.com/80914584/227017799-3b39279b-1b01-484b-8a2a-ad8a1646837b.png)

**Comment by davidnicholls125** [comment]
This problem persists but I can't pin down exactly what the cause is. Here is an example today. When I re-entered the species on a new row the images loaded without a problem. I tried again entering a comment before loading the images and this also worked..... Its not the images that are causing it.... but what??

![image](https://user-images.githubusercontent.com/80914584/233657295-96169efe-ac3f-4a43-b8f9-db20a13e277f.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 to get to the bottom of this, I'll either need a reliable way of reproducing it, or information from the browser developer tools when it happens. If the browser developer tools are running, then the network tab may contain useful information (this can be saved as a *.har file to send to me) and there may also be errors on the Console tab.

**Comment by davidnicholls125** [comment]
I'll reopen this if it becomes an ongoing problem.
