### ISSUE TITLE
Home page slow loading

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#15]
We would like the home page to load much quicker than it currently does. It seems to be loading particularly slowly at present but is generally slow. Could you investigate how best we can achieve this, perhaps by caching?

**Comment by johnvanbreda** [comment]
I think the first step is to conclusively identify which part of the home page causes the issue. I've had a quick look at the Indicia logs and can't see any issues when loading the home page, so the most likely candidate is a Drupal view.
Making a copy of the home page layout, then experimenting with loading different combinations of blocks, should help to narrow down which block or blocks are causing the main issues.

**Comment by davidnicholls125** [comment]
Please go ahead.

**Comment by johnvanbreda** [comment]
I've now spent a while looking at this but I'm struggling to work out what is going on. I've now recreated a page https://www.naturespot.org.uk/perf-test with all the same blocks on it. If you visit this page, then refresh (so all the caching should be applied), then it takes around 1 second for the initial page response. If you do the same on the home page, the response takes about 12 seconds. 

I can't do much more "in situ", so I've taken a backup of the site's files and database and recreated the entire site on my development machine. I've then installed the Drupal Devel module and the web profiler submodule which gives information on what is happening beneath the hood. Using this tool I found that the Masquerade block (which appears on the home page only) generates approx 1/4 of the total number of MySQL queries that happen when the page loads. I've removed this but, although the page's query count has dropped, the total time to load the page is still about 12s. Presumably for users without permissions to masquerade this module didn't load anyway so it can't have been the source of the problem.

The strange thing is, on my local development machine (running Xampp with PHP 7.3.25) the home page is taking about 1 to 1.5 seconds to load and the cloned test page is also taking 1-1.5 seconds to load. I think that's fairly acceptable as unlike the live site  I don't have the opcache module for PHP loaded which does improve performance and my laptop is not a tuned server environment. 

The Web Profiler confirms that both the home page and the cloned test page run the same number of queries. However, on the live server, the cloned test page takes 1 second, whereas the home page (even without Masquerade block) takes 12 seconds. Something is happening to the home page on the live server which I can't get to the bottom of. 

Is it worth asking Clook for more help here? They might be able to tell if any particular MySQL queries are taking a long time when the home page loads (for logged in users).

**Comment by davidnicholls125** [comment]
Clook are investigating... I've given them a test log in, though it doesn't have any additional permissions. David found that the drupal admin menu was adding a couple of seconds to the loading time but only admins would experience this.

**Comment by davidnicholls125** [comment]
I've emailed you Clook's response with an attached text file. Hopefully this will shed light on the issue.

**Comment by johnvanbreda** [comment]
Thanks. I can see the same (or very similar) being run on both my own local copy of the home page, plus the cloned copy. However, although the query does look a bit messy, it only takes 40 milliseconds to run. Are you able to find out how long Clook claim this query is taking to run please?

**Comment by davidnicholls125** [comment]
I've asked Clook if they can explain why the site is running faster on a copy of the database and if there are any lessons for future maintenance. I'll let you know what they say. Otherwise I guess we just monitor performance.
