### ISSUE TITLE
Latest images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#150]
On the Latest Images page, record images from Helen O'Brien are appearing as last name, first name whereas for others it is first name + last name. Do you know why this is? (I've checked her account entry and the name fields are correct). Also the Badger records now display {site} rather than a blank line as used previously - is this intended?
![image](https://user-images.githubusercontent.com/80914584/227474168-828ea22b-d691-4c51-9581-01226046ea6f.png)

**Comment by johnvanbreda** [comment]
I've fixed the {site} value. 

For the recorder name, app records don't include the Drupal username in the record data, so we rely on the stored recorder name which defaults to the surname, firstname grabbed from the user profile. The formatted name gets stored in the reporting cache data for performance reasons, so although it's possible to query for the recorder first name and surname from the raw data in the profile, this adds joins to the report which makes the report slower to load. 

I think there is a task to consider switching the default formatted recorder name to "firstname surname" which will fix this issue, but it's a change that would affect all websites. You could ask BRC (e.g. Martin Harvey) if this change is likely to become a priority in the near future?

**Comment by davidnicholls125** [comment]
Thanks John. The name format isn't really an issue now that we understand why.
