### ISSUE TITLE
Verification query function not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#151]
I'm not sure if this is us or iRecord, but the query function on the verification page isn't working. Firstly the email pop up window takes ages to appear then it won't send. Pressing the Send Email button seems to do nothing.....
![image](https://user-images.githubusercontent.com/80914584/228612456-bb67f4e7-9fb9-4441-9af1-4d76acba3f18.png)

**Comment by johnvanbreda** [comment]
I'm not seeing the performance issue - that may have been temporary, but the Send email button doesn't work in the version of the Indicia code you have running. It does work in the latest code though. @davidnicholls125 please can you confirm if you have a preference for when I should update the NatureSpot copy of the code in the coming week?

**Comment by davidnicholls125** [comment]
Just go ahead when you are ready, assuming we won't be offline for too long?

**Comment by johnvanbreda** [comment]
Done.
