### ISSUE TITLE
Wild Place page images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#153]
Please can you configure the Wild Place and Parish pages so that records and images with a grid ref resolution less than 100m don't display? I think we did this previously but the record below is appearing on a road verge!

![image](https://user-images.githubusercontent.com/80914584/233770357-8cce2258-13c6-4502-b65a-b655269780af.png)

**Comment by johnvanbreda** [comment]
I found that the block of images on the wild place or parish pages was not filtering by grid ref resolution but the other blocks should be OK. I've corrected the images block.

If you are still seeing this on a verge, please can you let me know which?

**Comment by davidnicholls125** [comment]
Seems fine now, thanks.
