### ISSUE TITLE
Submit Records problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#154]
Both yesterday and today I've submitted records and instead of the thank you page have had the 'drupal already installed' error page. As well as this specific problem, is it possible to redirect this error page to something less confusing? We've had a few issues raised about it over the years....

**Comment by johnvanbreda** [comment]
No, I don't think this is possible, as this relates to the system timing out and failing to reach the database, so assuming that it's not installed. We need to look at the logs around the time this happens (potentially both Drupal and Indicia) to see if we can spot what the underlying cause was.

**Comment by davidnicholls125** [comment]
It hasn't happened again in recent submissions so I'll flag it up with times if it reoccurs.
