### ISSUE TITLE
Images not appearing in the gallery

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#155]
The gallery images selected on: https://www.naturespot.org.uk/species/harpocera-thoracica are not showing in the gallery. I can't work out why.... could you have a look please?

**Comment by davidnicholls125** [comment]
As a further clue, there is a record image on the Latest Images page which links to the 'new species' page we set up recently rather than the actual species page.

**Comment by johnvanbreda** [comment]
If you look at the species page Edit tab, you can see that "not published" is shown in the top right. You need to tick the publishing status box near the save button at the bottom and save it.

**Comment by davidnicholls125** [comment]
Obvious now you've pointed it out! Thanks, now fixed.
