### ISSUE TITLE
Dashboard updates

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#156]
The dashboard hasn't updated after 3 hours following record submission. It isn't a caching issue as I've tried loading it with ?nocache added. We have had a few queries raised from users wanting to access/edit a record after submission and not being able to find it on their dashboard, presumably as it hadn't been updated. Is there a way to speed up the updating and even add an UPDATE button to the page to force a refresh?

**Comment by davidnicholls125** [comment]
Just rechecked - still no update after ~7 hours.

**Comment by johnvanbreda** [comment]
This was a service down issue after a minor UKSI update on Friday - fixed on Saturday evening.
