### ISSUE TITLE
LiteSpeed cache missing

### ISSUE THREAD

**Issue by johnvanbreda** [johnvanbreda/naturespot-d8#16]
When viewing pages such as https://www.naturespot.org.uk/gallery/bugs, I would expect that if not logged in and repeatedly loading the page, I would see LiteSpeed Cache: hit in the response headers. However I am seeing that LiteSpeed Cache: miss is being returned, indicating the cache is not working.

@davidnicholls125 please can you ask Clook if they know why?

**Comment by davidnicholls125** [comment]
I've submitted a ticket...

**Comment by davidnicholls125** [comment]
Is the LiteSpeed cache plugin installed on your Drupal site? There are some options within the plugin to switch the cache on has this been done?

There is some documentation on the plugin for Drupal here;

https://www.litespeedtech.com/products/cache-plugins/drupal-acceleration

**Comment by davidnicholls125** [comment]
Thanks - this looks to be similar to the previous ticket where the litespeed cache section is missing from the .htaccess file.

Unfortunately there doesn't appear to be a copy of this section in the backups, so it looks like it's been this way for at least 30 days.

We've added the minimum amount required to get the cache working again, but don't know exactly what was there so it's a very generic piece of code we've added. Please test your site is working as intended.

It may be best to uninstall then reinstall the plugin to see if that helps, as currently the .htaccess rules aren't controlled by the plugin.

**Comment by johnvanbreda** [comment]
I think whatever generic code has been added should be fine as I've never setup anything specific in .htaccess for LiteSpeed cache. I think I know what happened - when Drupal is upgraded, it overwrites .htaccess with a new version. I didn't realise there was LiteSpeed Cache specific code in the file so it would have been lost at that point.
