### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#160]
The Wild Place record download function on the Elasticsearch download page, which you reinstated recently, isn't working. I've tried selecting a parish and this also doesn't work. Please could you have a look?

**Comment by johnvanbreda** [comment]
Note for myself - this is because the location select control is currently designed to only have 1 per page. Needs re-configuring to link the hidden geom input to the specific control.

**Comment by davidnicholls125** [comment]
We need to produce the annual report for the Charnwood Project so I urgently need to download the records (we have a 'super-site' set up for this). Please could you fix the Wild Place record download as a priority?

**Comment by johnvanbreda** [comment]
I've done the code for this already so just need to review and deploy it. I've got a few things on this morning so it will be done by the afternoon.

**Comment by davidnicholls125** [comment]
That's fine. Thanks.

**Comment by johnvanbreda** [comment]
Ok, should be working now. I'll close but re-open if you find any issues.
