### ISSUE TITLE
Species page pagination

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#161]
Both the latest images and latest records at the bottom of the species pages displays from NaN to NaN rather than actual numbers. 
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/c94a79b3-e5a2-445c-b3a4-7bc20fd282ad)

**Comment by davidnicholls125** [comment]
This is also a problem on the Parish and Wild Place pages - clearly something has gone wrong with the pagination.

**Comment by johnvanbreda** [comment]
Fixed.
