### ISSUE TITLE
Rogue recording advice!

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#162]
Can you work out where the second sentence on the recording advice below comes from? It needs removing but I can't find it! It isn't on the species page nor on the family entry.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/74790ad8-49a5-4a83-85e8-f8c38a331cc6)

**Comment by johnvanbreda** [comment]
The recording advice can come from the species account, or one of its parents in the menu hierarchy. E. muscae is on the Gall Fungi menu as well as under Entomophthoraceae according to the edit tab, hence the system works up the menu items to find the gall recording advice.

I am not sure why E. muscae isn't actually appearing under Gall Fungi on the menu - if you want me to look into that let me know.

**Comment by davidnicholls125** [comment]
Thanks, that explains it. I've removed the gall fungi entry from the species page.
