### ISSUE TITLE
New registration form - URGENT

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#163]
I've just noticed that when you open the registration form (for new accounts) it has Kate Strong's name and email address pre-entered. It looks like there might be a default setting for these fields but I can't see it. Please can you check this as a priority as we are working with WWF on a promotion that will direct people to this page.
Thanks.

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/db830a48-0d5a-46f9-b008-30da443e657a)

**Comment by johnvanbreda** [comment]
Have you previously registered an account for Kate using that computer? I'm pretty sure this is just the system trying to be "helpful" and remembering previous form settings from when you last registered. If I try on my own browser, I actually get the details from a test account I recently registered, but if I use a different browser then the form is initially completely empty.

If this is a problem (i.e. multiple people registering via the same computer) then let me know and I think it's possible to turn this off.

**Comment by davidnicholls125** [comment]
I probably did some time ago, though can't remember. It remains even after Ctr+F5, however happy to believe you!
