### ISSUE TITLE
User download

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#165]
We are working with WWF on promoting wildlife recording via social media adverts with clicks leading to the NS registration form. We are getting a lot of new accounts as a result. However we now need to be able to monitor what happens next. Could you add a few additional fields to the download report below please?

http://www.naturespot.org.uk/users

Add:
Registration date
Last access date
Include those who have applied but not completed the full process (ie last access = never)
No. of records submitted (I expect this will have to be a different download that I can use a lookup with to integrate the data)

**Comment by johnvanbreda** [comment]
I've updated the /users page and added a page with a download button for the list of user record counts at https://www.naturespot.org.uk/users/record-counts. This is deliberately minimal as it would be quite slow if I added extra columns, so you need to cross reference the warehouse user ID from the download to the IDs in the users view.

**Comment by davidnicholls125** [comment]
Thanks, that works fine. One thing - is it possible to include those that have registered but never accessed the site - ie not received or responded to the follow up email?

**Comment by johnvanbreda** [comment]
I've done that. They were filtered out because when we originally set this up there was a filter on last login date > 2010, so any that had never logged in were removed. I've removed that filter so it does mean you will get users who haven't logged in since before then.

**Comment by davidnicholls125** [comment]
Thanks
