### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#168]
We have a trustee meeting last night to discuss ways in which we could better support new users and encourage more recording. A few actions resulted that we need your help with. 
On the registration form, can we show the terms and conditions as a link (that opens/closes a pop up perhaps) rather than default to show it in full, with the accept tick box next to the link. On a mobile the form takes forever to scroll down at present.
We also want to replace the 'interests' question on the registration form with a few radio button options. What text field do we need for this? Also, will these automatically be included in the user download or will they need to be added?
I'll add a few other requests later....

**Comment by johnvanbreda** [comment]
I've changed the registration to use a link for the terms of use.

For the replacements for the interests, I just need to know the label, captions for each option within the control, plus any help text. We can replace it with 1 or more groups of radio buttons, or checkbox groups (if multi-select allowed).

Any extras need to be added to the user download but that is a fairly simple task.

**Comment by davidnicholls125** [comment]
Thanks. We want to replace the 'interests' questions with this: (please make it a required field)
Please tell us why you want to join NatureSpot? (click all that are important to you)
•	I’m interested in recording wildlife
•	I’d like help with identification
•	I’d like to explore the full NatureSpot website
As all three could be selected we will need three more fields adding to the download. Can we keep the interests data from previous registrations on the download?
We also want to add some intro text to the top of the registration form and before the terms link. Can this be set up so that we can edit this?

**Comment by davidnicholls125** [comment]
I've just downloaded the list of users and linked this to the number of records submitted. There are a few odd findings which I can't work out. I'm presuming that users who have not completed the registration process, ie not clicked on the email link, are those that have 01/01/1970 in the 'last log in' column? However, some of these have submitted records.....I've attached a list (User anomalies). I recognise a few names as those we have submitted records for via masquerade, eg Adrian Rundle, but I don't think we have done this for all on the list.
Taking Jim Graham's account - Indicia says he has submitted 456 records. However his dashboard only shows 18 as a total, though does also say 456 in the summary??? When I downloaded records for "J. Graham" it only gave me 18 (screen print below). These 18 may have been a bulk upload as the records are for 2014 yet inputted in Feb 2018. But where are the others?

[User anomalies.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/12206778/User.anomalies.xlsx)
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/a26bc6f1-0f02-4a4e-8426-9ffdb12f2220)

**Comment by davidnicholls125** [comment]
I think we need to make the Terms and Conditions a requirement rather than an option when a new user first logs in. Could you change this please (or tell me how).

**Comment by davidnicholls125** [comment]
Closed in error!

**Comment by johnvanbreda** [comment]
Jim Graham's data is mostly before 2014, so as the "records and species by group and year" report is limited to a 10 year span, it only shows those from 2014 and there is nothing in his name since. The report title could be altered to show that this is limited to 10 years ("Records and Species by group and year for the last 10 years" for example). Or we could expand to a wider range of years.

To modify the behaviour for accepting terms and conditions for existing users, you can view the legal document at https://www.naturespot.org.uk/admin/structure/legal/manage/data_protection_and_terms_of_use. Click on the Existing users vertical tab and the options are there.

The last login column does indeed show 01/01/1970 for users that have never logged in. I've looked in detail at 1 example, Tony Richards and everything seems genuine, except that Drupal has not logged the last login date. I can't answer why this would be I'm afraid. Creating the accounts and masquerading as them to enter some records would definitely be a possible explanation.

**Comment by davidnicholls125** [comment]
Thanks. Yes for clarity we should explain the 10 year limit.
I'm still confused re Jim Graham. The dashboard total for J. Graham shows 456. I've downloaded all records for everyone with 'graham' in the name and the relevant ones are shown below. There is only one account showing on drupal and that is for J. Graham (warehouse ID shown). No combination of the totals seems to match the 456. Does this make sense to you?
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/a55f9295-b6cb-4faa-a200-480ee83b3f61)
Thanks for the link - I've changed it.

**Comment by johnvanbreda** [comment]
On the download page (https://www.naturespot.org.uk/download-data-v2) you can download the records using the search term "metadata.created_by_id:38466". This gives 456 records, with a breakdown of given recorder name as follows:
"Jim Graham"	320
"J. Graham"	18
"Jim Graham;M. Smith"	1
"Graham, Jim"	117

**Comment by davidnicholls125** [comment]
OK thanks. I think he has more than one account which is contributing to the confusion. Is there an easy way to merge accounts? (He isn't the only one with multiple accounts).

**Comment by johnvanbreda** [comment]
I've added the new questions about reasons for joining, plus hidden the interests field, from the sign-up form. I've added these to the users view and associated downloads.

Multiple accounts occur when people re-register with different email addresses. Jim seems to have 3 accounts:
https://www.naturespot.org.uk/user/5851/edit
https://www.naturespot.org.uk/user/12909/edit
https://www.naturespot.org.uk/user/6631/edit

Please confirm which account you want to keep and which should be removed - I can merge the records into 1 account.

**Comment by davidnicholls125** [comment]
Thanks. Can we tweak the wording of the form or do we need to ask you?
Checking on Jim's accounts. The middle one (12909) is not Jim but his wife, Sue. The main account for Jim is the bottom one (6631) so the top one (5851) can be merged with this.

**Comment by johnvanbreda** [comment]
This is now done - there was a bit of a mess to sort as Jim and Sue had registered the second account in Jim's name then changed it to Sue. 
Form wording can be tweaked by you if you want to modify the fields at https://www.naturespot.org.uk/admin/config/people/accounts/fields, but feel free to ask if unsure.

**Comment by davidnicholls125** [comment]
Thanks.
