### ISSUE TITLE
VC55 - Leicestershire boundary

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#176]
The VC55 boundary cuts through the centre of Market Harborough, one of the larger towns in the county and we have had a few comments about records for the area within Leicestershire but outside VC55. I've spoken to the Leics Records Office to see what their policy is and they use a hybrid boundary that does include all of Market Harborough. If I get a GIS file of this boundary could we apply it to NS? It would still be useful to include the VC in the download as a few county recorders would want to take a strict view, but we would be more in line with the records office and avoid the frustrations that some recorders have when near the boundary.

**Comment by davidnicholls125** [comment]
Coincidentally, this record has just been added - but how? Is the filter for VC55 still working? From the verification page I tried to open 'edit' but it wouldn't bring up the record.....

**Comment by johnvanbreda** [comment]
@davidnicholls125 what's the record ID?

The boundary for the environmental records centre is already available in the Indicia warehouse - at least the one that was provided by ALERC. 
![image](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/380e5a1a-9d84-4147-a04e-acd8e3d65716)

Here's the Vice County for comparison:
![image](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/7fa11c40-4310-4108-8779-777bf163e7d8)

There are other small differences, mainly a chunk of land near Swadlincote. We can switch to the ERC boundary fairly easily if that helps.

**Comment by davidnicholls125** [comment]
32024887 (sorry, I meant to paste the image below in the previous message.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/97564f90-32eb-4ce5-a9ed-a9098824e881)

**Comment by davidnicholls125** [comment]
Can we swap over the boundary files to use that provided by the records office please? The main difference is the Market Harborough inclusion, though I know there are other smaller variations.

**Comment by johnvanbreda** [comment]
Record 32024887 was added via the app, so not subjected to the location limit.

I've swapped the layer on the data entry page. For the boundary on the wild places map, I do need the boundary in SHP file format - can you obtain this for me please? There should be several files with the same name but different extensions, e.g. *.shp, *.shx, *.prj and possibly others.

**Comment by davidnicholls125** [comment]
Ok thanks.
I've asked for the boundary file. It's easy to convert it in qgis.

**Comment by johnvanbreda** [comment]
Just reviewing to check this can be closed - I think the wild places and submit records maps match and are the same as the SHP file supplied. Please can you close if the boundaries are all now OK?
