### ISSUE TITLE
Main header

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#177]
We want to change the main header on the website - where do go to replace the current version please? What is the optimal size to upload?

**Comment by johnvanbreda** [comment]
The header is currently styled by the theme code and is constructed with a background of solid green (1140px x 96px), then an image of a frog overlaid and aligned to the left, plus an image of the text overlaid and aligned to the right. This approach allows the banner to be a flexible width, and we can hide the frog image and scale the text when shown on a mobile device. So, it's not as simple as a straight swap. If you can provide an idea of the banner you would like to achieve I can have a think about how to make it resizeable.

**Comment by davidnicholls125** [comment]
Thanks John. I have it as a photoshop file where each layer can be separated, would this work? I had forgotten about the solid green background to the frog. I can see this blends into the mottled image we used previously. Can we do the same or do we need to keep it plain throughout?

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/c87ac4fb-0e67-4597-a0c7-d2ef432b0b2b)

**Comment by johnvanbreda** [comment]
Looking at that image, I would suggest we make a single image 1140px wide which includes the frog, NatureSpot and the strapline, but not the "Learn Identify Record" text - just leave a space for that. I can then add these using a standard font scaled to fit. If the screen space is reduced, we can then drop this text and clip the space off the right. As it's reduced further we could then clip the frog off the left so it's just the text, scaled to the space available.

Can you make me a single JPG of the image as shown without the text on the right, 1140px wide please?

**Comment by davidnicholls125** [comment]
![Header_Aug23_1140px](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/8966638d-3840-4ef5-b138-f117a920f4f3)

**Comment by johnvanbreda** [comment]
@davidnicholls125 not sure why but I can't access the image pasted above, can you email it to me please?

**Comment by davidnicholls125** [comment]
Emailed as requested.

**Comment by johnvanbreda** [comment]
Now done.

**Comment by davidnicholls125** [comment]
Thanks. Can the Learn/Identify/Record wording be made a little larger and centred in the space please.

**Comment by johnvanbreda** [comment]
Done
