### ISSUE TITLE
VC status

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#178]
There has been some objections to the boundary change we made from a few County Recorders. They feel we are 'stealing' records from adjacent VCs. A couple of things: firstly can I just check that the records we download will still include the relevant VC entry? Secondly, can we have the VC on the verification screen - or at least the option to ad it. I've looked through the 'spanner' options and can't see it. Thanks.

**Comment by johnvanbreda** [comment]
Yes, you will get the VS info in the download. You may find quite a few of the records in the new boundary area include both as the grid square overlaps - you will see something like the following:

VC number = 55 | 32
Vice County = Leicestershire | Northamptonshire

The vice county fields can be added to data grids but need a special column format - to find the docs for this see https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html and search for "higher_geography" on the page. I've added a column called VC with the format `#higher_geography:Vice County:code#`. You will probably need to use the spanner icon to add it.

**Comment by davidnicholls125** [comment]
That's great, thanks.
