### ISSUE TITLE
RAG icon hyperlinks not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#179]
The red/amber/green camera icons on the species pages should link to the Identification Difficulty page but these are currently not working.
Examples:
https://www.naturespot.org.uk/species/alder - no hyperlink showing
https://www.naturespot.org.uk/species/chromatomyia-centaurii - hyperlinks bring up a page not found error

The page they should be linking to is:
https://www.naturespot.org.uk/content/ID_difficulty

**Comment by johnvanbreda** [comment]
Fixed - I suspect the path of the page had changed at some point.
