### ISSUE TITLE
Submit records form - grid ref problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#18]
Sue Timms (one of our trustees) has been unable to get the Submit Records form map to generate a grid reference. This has persisted for 2-3 days. The rest of the site is loading normally so presumably not a slow connection. She is using Chrome.  Not sure if anyone else has this problem as it is working fine for me and a couple of the other others I have asked. Any ideas?

**Comment by johnvanbreda** [comment]
Are you able to use the developer tools to inspect the page and see if there are any JavaScript errors on the page when this happens?
Is Sue attempting this from a normal, home network, or at a workplace where a firewall may be running?

**Comment by davidnicholls125** [comment]
I don't have the problem so presumably I won't see any errors. She is using her home computer.

**Comment by johnvanbreda** [comment]
I was hoping that someone might be able to help her install the developer tools, but I realise that's a bit of an ask. Please can you find out exactly which Chrome version she is using. Also is she able to try Edge or another browser to see if the same thing happens?

**Comment by davidnicholls125** [comment]
Sue still has the problem but hasn't been able to find out which version of Chrome she has nor load Edge! However Mike has just reported that he has the same problem now:
_I'm also getting this problem now in Chrome on Windows 10. I've tried clearing cookies, refreshing, etc., but it hasn't resolved it. It seems to be working fine in Edge, however._
I've tried it in Chrome (v90 in W10) and it works fine.
I'll ask Mike to use the developer tools as you suggested earlier.

**Comment by davidnicholls125** [comment]
Mike's reply - I'm not seeing any JavaScript errors. I've updated Chrome to Version 90.0.4430.72 (Official Build) (64-bit), and restarted my PC, but it hasn't fixed it.

**Comment by davidnicholls125** [comment]
Sue has found the Chrome version she is using (same as mine) - Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by johnvanbreda** [comment]
I've tested Chrome 90.0.4430.72 on Windows 10 with no problems. Please can you ask Mike to check the Network tab when he clicks on the map. Is there a request to "wkt_to_sref"? If so, what is the response?

**Comment by davidnicholls125** [comment]
Mike says: I don't see any wkt_to_sref in the list.

**Comment by davidnicholls125** [comment]
Mike says: I don't see any wkt_to_sref in the list.

**Comment by davidnicholls125** [comment]
I've sent you an email with an attached report that Mike thinks may be of use.

**Comment by johnvanbreda** [comment]
Unfortunately there was nothing useful in the report from Mike. 

Please can you ask Mike (just to be sure) if he loads the submit records page, then does nothing else except a single click on the map, does the Grid Reference field get filled in?

It will be quite difficult to trace this problem unfortunately unless we can find out how to reliably reproduce it.

**Comment by davidnicholls125** [comment]
As an update, Sue reports that the auto grid ref entry has suddenly started working again for her. For Mike however, the problem remains on Chrome but is fine on Edge.

**Comment by johnvanbreda** [comment]
Is it possible Sue has a new version of Chrome?

**Comment by davidnicholls125** [comment]
No she has the same version as me and I don't have the problem.
