### ISSUE TITLE
Search place not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#181]
The search box above the VC55 map on the species page isn't working.....

**Comment by johnvanbreda** [comment]
This was using the Google Place search API. The proposed solution is to switch to Nominatum place searches as that's still working on the submit records form.

**Comment by davidnicholls125** [comment]
I've not heard of it but please go ahead if you think this is the best solution.

**Comment by johnvanbreda** [comment]
Done. Nominatim is the place search API that goes along with OpenStreetMap.
