### ISSUE TITLE
Media library

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#183]
Can you explain why the image inserted into the ID Aids section of the page below won't display? Thanks.
https://www.naturespot.org.uk/species/dolichopus-griseipennis

**Comment by johnvanbreda** [comment]
It related to my overridden template for the identification aids field, which automatically adds the button and places the content in a collapsed box. Should now be fixed.

**Comment by johnvanbreda** [comment]
Closing as now OK.
