### ISSUE TITLE
Photo of the month

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#185]
We are selecting one image each month that we think shows something interesting and adds to the website coverage. We want to keep it simple for now but would like a way of flagging candidate images. Could you add a tick box field to the image properties that we could quickly tick if we see a good image flowing through Latest Images? We also want these to then appear on a page for the month it was verified in - but only published when we have decided the winner. Does this seem reasonably practical?

**Comment by johnvanbreda** [comment]
I've added a new tickbox at the bottom of the edit page. Also a view at https://www.naturespot.org.uk/image-of-the-month-candidates which allows you to view the images. It can't easily be filtered on verification date though, but uses the last edit date for the image link which should be the same if set when verifying, so the page shows images where this flag was set in the last month. 

Is that everything you need?

**Comment by davidnicholls125** [comment]
Thanks John. A few tweaks:
Add 'edit' links to images on Latest Images (and if possible on the species page latest images).
Include 'comments' with the images on the POTM page.
Can we have four images on each row (as displayed on Latest Images).
Can the sort order state 'Most recent / Oldest' (presumably this is based on published date?)
Page header: 'Photo of the month - candidates and winners'
Is there a way of adding a filter to just display the winners? Each will have a comment 'winner xx' if this helps.

**Comment by johnvanbreda** [comment]
> Add 'edit' links to images on Latest Images (and if possible on the species page latest images).

This is not trivial since the latest images reports come from Indicia and it doesn't know about the image link nodes. It would take an hour or two to implement - let me know if that's OK.

> Include 'comments' with the images on the POTM page.

Done

> Can we have four images on each row (as displayed on Latest Images).

Done

> Can the sort order state 'Most recent / Oldest' (presumably this is based on published date?)

Again, not so easy to change unfortunately, so would take an hour or so. Let me know if that's OK.

> Page header: 'Photo of the month - candidates and winners'

Done

> Is there a way of adding a filter to just display the winners? Each will have a comment 'winner xx' if this helps.

Done, but rather than relying on a comment I've added a separate "winner" tickbox to the edit page which will be tidier and easier for the code to filter on.

**Comment by davidnicholls125** [comment]
Thanks. Go ahead with adding 'edit' links to the Latest Images page. There have been multiple occasions when it would have been convenient to access this apart from the POTM so worth doing I think.
Isn't the 'most recent/oldest' just amending the words on the existing filter? However if it isn't as simple as this leave it for now.
One further thought, could we have a filter for each month, eg 'September 2023'? Given it is a monthly event it would make sense to be able to view all candidate images and the winner for a given month. Can the winner be the first in the display?

**Comment by davidnicholls125** [comment]
We need to add some introductory text explaining the criteria, etc. Can we have a editable intro text box?

**Comment by johnvanbreda** [comment]
You can edit the header of the view at https://www.naturespot.org.uk/admin/structure/views/view/image_of_the_month_candidates/edit/page_1?destination=/image-of-the-month-candidates - click the Global: Text Area link then set the text you require. Make sure you save both the text and the view.

The filter HTML is autogenerated by Drupal, so needs a bit of customisation to change the wording on the date filter order - i.e. not as simple as it should be.

Filter by month is possible, needs a custom filter, about an hour's work if that's OK? (note to self - see https://www.flocondetoile.fr/blog/filter-content-year-views-drupal-8 for ideas).

**Comment by davidnicholls125** [comment]
Thanks. Yes go ahead with the monthly filter but leave the other wording for now.

**Comment by davidnicholls125** [comment]
Sorry John, I may have messed up the display. I changed the path to 'photo-of-the-month' and now the images have reverted to 2 in a row.... I can't see where the configuration is for the image display.....
Also can we remove the 'Filter' heading, it isn't needed.

**Comment by johnvanbreda** [comment]
I've fixed the layout - it was related to the page path being used to apply the CSS styles. I've also removed the filter heading.

I've added the edit links, but having done that I've realised there is an issue with this approach as most of the images don't have an image link - only the ones that have been added to the species account will have one. Therefore the links will normally give an warning that the page is not found.

**Comment by davidnicholls125** [comment]
Ah. None of the latest images will have been published so there isn't any point then. Shame.
Thanks for the other tasks. Just the monthly filter to add?

**Comment by johnvanbreda** [comment]
Monthly filter done. It will automatically generate options for the last 12 months, but will never go before July 2023 as that's the first month you have a photo of the month candidate for. I can change it to September if preferred?

Also currently it's using the date the image link was created (i.e. when you added it to the species account). The other date we could use to determine the month is the sort date, which might be better as it normally matches the record date. It's not always filled in though so it would need to always be filled in for any candidate photos if you want to filter on the sort date.

**Comment by davidnicholls125** [comment]
Thanks John. The date the image link is created won't work as not all will be published, and if they are it may be in a later month (for example if you select Sept 23, the August POTM image is included in the display). We really want to use the verification date as this is when the image appears on Latest Images and can be selected. We don't want the record date as this could be some time ago if verification is delayed. It has to be the month that the image 'appears' publicly, ie on Latest Images. If there is really not automatic solution then maybe we can manually select the month when ticking the candidate box? Obviously this would require another field adding.

**Comment by johnvanbreda** [comment]
An automated solution would involve querying the Indicia data, so more complex and slower. I've added a manual Photo of the month - month box which should be filled in in YYYYMM format, e.g. 202309. I've added one example for September so you can see it working.

**Comment by davidnicholls125** [comment]
Thanks John, that works.
