### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#187]
On the species page below, there is a link to the UK Sawflies website. It looks to be set up correctly yet when I click on it I get an error message and the URL has put the naturespot URL in front of it....
https://www.naturespot.org.uk/species/gilpinia-frutetorum
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/fe12de04-9aa7-408f-83cf-4a8de1fdcce0)

**Comment by johnvanbreda** [comment]
I've added https:// to the href part of the link (viewing the source) which fixes it.
