### ISSUE TITLE
Logging in and notifications

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#188]
Is it possible to allow registered users to enter either their username or their email when logging in? Increasing, websites seem to offer the choice. This is the main problem we find with log in issues where users enter their email instead of their username.

When you set up daily notifications as the default for new registrations recently, I'm just checking that this include receiving milestones?

**Comment by johnvanbreda** [comment]
Yes, but it needs the addition of a new module so I'd like to do that alongside an upgrade of Drupal core plus any other modules that need an update. Let me know when you'd like me to do this (allow for an hour or so offline).

Milestones default to a daily notification.

**Comment by davidnicholls125** [comment]
There is no obvious quiet time that I can think of so just do it when it is convenient to you. If we know 24 hours in advance we can post a warning on the home page.

**Comment by johnvanbreda** [comment]
As you have already posted a message about disruption today, I will use the opportunity to take the site offline and do an upgrade.

**Comment by johnvanbreda** [comment]
The update is done and email login is now enabled.

**Comment by davidnicholls125** [comment]
Thanks John. Could you look at #168, near the top is the original request to add questions to the registration form which I think has been over-looked due to later additions. 
Also, one minor thing - we need to remove the full stop from the log in box where the label says 'username or email."

**Comment by johnvanbreda** [comment]
I've done the change for #168 and fixed the punctuation. The latter is a problem in the module which handles email login itself, so I've raised a bug report: https://www.drupal.org/project/login_emailusername/issues/3410326
