### ISSUE TITLE
All new account applications blocked

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#19]
We've just been told it isn't possible to open an account - an error message is received when you try to submit the registration form. I've just tried and got the same error message. There was no recaptcha on the form.....

**Comment by johnvanbreda** [comment]
Hidden away in the instructions for Google Recaptcha_v3 I found information about installation that hadn't been done correctly. Now done correctly, so should be OK.

**Comment by davidnicholls125** [comment]
Thanks.
