### ISSUE TITLE
Media Library questions

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#190]
I'm still struggling to get to grips with the Media Library....
Why are only 5 of the image styles available when going to edit media on a Media Library inserted image? How do I get others to appear on the menu?
I've created a new image style (Original) but this isn't being made available....
If I change an image style, should all previously inserted images with that style adopt the new settings?
Thanks.

**Comment by johnvanbreda** [comment]
In order for a style to be made available on a media library inserted image, there are a few things required:
1) An image style must be added to this page: https://www.naturespot.org.uk/admin/config/media/image-styles. I can see that you've worked that bit out.
2) On Structure -> Display Modes -> View modes, there needs to be a matching view mode under the Media section. I can also see one called Original.
3) On the Manage Display page for a media image (https://www.naturespot.org.uk/admin/structure/media/manage/image/display) on the Custom display settings tab near the bottom, tick the box for the new view mode and save it.
4) You can now click on the view mode (in the row just under the tabs) and configure how it displays. You will normally want just the image, with the label hidden or visually hidden, and use the Cog icon to change the image style to Original.
5) Now, on the text format's edit tab (https://www.naturespot.org.uk/admin/config/content/formats/manage/basic_html?destination=/admin/config/content/formats), click on the Embed media side-tab near the bottom and turn on your new view mode.

It's a bit complex, but gives a lot of flexibility, as the image style just defines the image itself but the view mode defines the image plus anything else you want, like a caption, figure, description etc.

Let me know if you need more help.

**Comment by johnvanbreda** [comment]
Can this be closed @davidnicholls125 ?
