### ISSUE TITLE
Incorrect TVKs

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#191]
I downloaded the species details yesterday and found that the species on the attached spreadsheet had different TVKs on the drupal species pages to those on Indicia. Do you know why these were missed by the update we did recently? (Note, I've manually corrected the entries).
[Incorrect TVKs 27Sept23.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/12748396/Incorrect.TVKs.27Sept23.xlsx)

**Comment by johnvanbreda** [comment]
The query I run for changed names only picks up a certain scenario and depends on at least one of the names available still being the same. I've managed to alter it to be a bit more "sensitive" so it no longer requires any exact name match and that has picked up a further 17 names to update (file sent by email). There are a few in your list that still remain, e.g. _Euconulus alderi_, but as far as I can see this name is correct in your species account and Indicia database species entry (https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021342624).

**Comment by davidnicholls125** [comment]
Thanks John. I've run the update. It shouldn't pick up Euconulus alderi I think as I amended the TVK a couple of days ago to match the Indicia entry.
