### ISSUE TITLE
Missing images/record

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#193]
I've just noticed that the species page for Glossiphonia heteroclita displays two broken image links. Oddly the record itself appears to have disappeared as well. Can you check what has happened to the record? (Mark Skevingon, Huncote Embankment, 5 June 2022). If the recorder deletes a record after we have published verified images, shouldn't they be unaffected? (assuming published images are drupal copies....)
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/eb608459-1ef6-43d0-8406-b22c7a4fdadb)

**Comment by johnvanbreda** [comment]
That is indeed a deleted record. Note that Drupal copies are only the metadata, not the image file itself (it would make your hosting costs very expensive if we kept images actually on NatureSpot). Some deleted images have indeed been moved on the server but they are still available from a different path and when they were moved I did try to repair the NS image links, but it looks like I may have missed some. I've fixed these 2 but feel free to re-open and let me know if there are more.
