### ISSUE TITLE
New record error

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#194]
I've just submitted a record where the thank you page says it is a 'new record' for me - this isn't true. This was for Birch Polypore  shown below. Do you know why?
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/0355227a-367e-4066-9b6d-604f362890e9)

**Comment by johnvanbreda** [comment]
This is the link to the thank you page you saw: https://www.naturespot.org.uk/content/thank-you-record?table=sample&id=24064359. I could not reproduce the problem - please let me know if it happens again.
