### ISSUE TITLE
Indicia accounts

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#195]
We would like to give two of our trustees access to Indicia in addition to myself. Is it best to create a single generic NS account or is it preferred to have individual accounts?
The new accounts wanted are:
David Gould -  mr.david.gould@gmail.com
Sue Timms - suetimms@clara.co.uk

**Comment by johnvanbreda** [comment]
Probably best to have individual accounts. Is it access to the warehouse that you are after?

**Comment by davidnicholls125** [comment]
Yes, its to be able to add/amend our species entries.

**Comment by johnvanbreda** [comment]
Done - email sent about logins.
