### ISSUE TITLE
Missing VC55 maps

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#196]
Some of the new species recently set up are not displaying the VC55 maps. The UK map is fine. The TVKs are all correct with the entries on NBN, Indicia and the species page all matching. I can't work out the reason.... It's not a caching issue as it has been a few days and I've loaded the page with the ?nocache suffix.
Coccinella undecimpunctata
Bembidion quadripustulatum
Atomaria pulchra
Ahasverus advena
Acalles misellus

**Comment by davidnicholls125** [comment]
Another new species with a map problem....
https://www.naturespot.org.uk/species/macquartia-tenebricosa
The map is appearing but with a pink overlay. It is the NS data layer that is the problem here.

**Comment by johnvanbreda** [comment]
I've had a look at several - they have all either had an extra character of the NBN Key value (e.g. one had a / at the beginning), or there was an unnecessary carriage return in the value after the key - it's important that this field holds the key and nothing else or attempts to look up using it won't work.

**Comment by davidnicholls125** [comment]
Thanks. We have more trustees helping now with the set up so I'll make sure they know.
