### ISSUE TITLE
TVK confusion

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#198]
Some time ago we raised an issue with the NBN having noticed that they appeared to have mixed up two Puccinia species. They  have now resolved this and we have entered the correct TVKs on NatureSpot. However, all our Puccinia distincta records are appearing on the verification page as Puccinia lagenophorae, despite having the correct TVK for P. distincta. I therefore suspect that iRecord may have got caught up in the same TVK confusion that we experienced.
The correct TVKs now on NBN are:
Puccinia distincta - BMSSYS0000015647
Puccinia lagenophorae - NBNSYS0000021917
I redetted all the Daisy Rust records (P. distincta) which were appearing as P. lagenophorae but they are still unchanged.

**Comment by johnvanbreda** [comment]
This is still a problem at the NBN end. P. distincta is down as a synonym of lagenophorae - see the sandbox at https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000021917. If you click the link for distincta it takes you to a broken page https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=BMSSYS0000015647. 

In our database, we also have a redundant taxon P. distincta, but it is marked as no longer available for data entry. The page for this organism key is broken on the sandbox but it may be an organism that was marked as redundant at some point. (https://uksi-sandbox.nhm.ac.uk/taxon.php?orgKey=NBNORG0000004948).

**Comment by davidnicholls125** [comment]
OK thanks John. It seems to be one of those species pairs where there isn't total agreement on the taxonomy. Research indicates that most authors consider them to be different species with different distinct hosts. We will use an invented TVK for P. distincta as we want to retain our entry as a separate species.
