### ISSUE TITLE
Verification page problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#200]
Both Sue and I have had this error message today when trying to send a record using the 'contact an expert' button, however another time it was OK.....
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/90b9e7c8-33d0-4163-8dd1-e63e9b1d048c)

**Comment by johnvanbreda** [comment]
I tested this just now and it worked, so closing on the assumption it was a temporary server glitch. Please re-open if you see it happen again.
