### ISSUE TITLE
Verification Summary

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#201]
Please could you create a report to summarise the total number of pending and queried records in each taxon group, similar to that attached? We are constantly chasing our verifiers, particularly as we need to clear the queue for the year end, so it would save a lot of time to have a summary instantly available! Thanks.

[Verification Summary.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/13440010/Verification.Summary.xlsx)

**Comment by johnvanbreda** [comment]
@davidnicholls125 here you go: https://www.naturespot.org.uk/verifier-summary. There is a download button at the bottom and you can filter by year. Please close if OK.

**Comment by davidnicholls125** [comment]
That's great, thanks John. A few tweaks if possible please, firstly can the default list sort on the pending column - highest at the top. Secondly, could we have a totals row at the top? Lastly, can the year default to the current year?

**Comment by johnvanbreda** [comment]
Sort done and a default to current year also done (though it is a manual edit so will need a tiny tweak each year).
I can't easily add a totals row - this could be done in a separate report, or you can use the sum function in Excel?

**Comment by davidnicholls125** [comment]
Thanks John. The only totals we really want is the pending + queries number as this shows how many more records need to be verified before the year end. Could these be shown prominently at the top of the elasticsearch verification page?

**Comment by davidnicholls125** [comment]
Just noticed that the queried column is showing pending+ queried combined rather than just the query number.

**Comment by johnvanbreda** [comment]
I've managed to add the totals to the top of the summary page. I've also fixed the queried count. Note that on this page, queried is currently queried + answered, whereas on the verification page the queried and answered categories are separated out so you might get slightly different numbers when comparing the 2. To fix this I could add an "Answered" column to the summary? Or we could lump Answered in with Pending (as they are effectively back into Pending review stage).

**Comment by davidnicholls125** [comment]
Great, thanks. Yes I think adding the answered queries to pending makes most sense. Listing the query queue brings up 26 records so it would make most sense if the total box matched this - and the same for the pending queue.

**Comment by johnvanbreda** [comment]
That's done. The Pending queue won't match though as it excludes queries AND answers (though maybe it shouldn't).

**Comment by davidnicholls125** [comment]
Great. Many thanks.

**Comment by davidnicholls125** [comment]
I think the summary is counting records based on the record date rather than the submission date. Could this be amended please? (We aim to verify all records submitted during the year).

**Comment by johnvanbreda** [comment]
Yes, it was indeed. I've changed it to use the submission date.
