### ISSUE TITLE
Verification page problems

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#203]
There are several problems with the verification page, some of which I have emailed you about in recent weeks.

1. We are still getting an 'elasticsearch query failed' error message when redetting or editing a record. The redet does appear to work despite the message but the edit doesn't work. I've tried to remove my name from the 'Identified by' box using edit but it won't save the changes. The tick box to prevent the redeterminer's name being entered doesn't work either.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/713385a7-281d-4562-bb13-e7f2285b2262)

2. The redetermination pop up on the elasticsearch verification page has a corrupted layout so is leading to mistakes being made. We really want the default setting to be to leave the 'identified by' field unchanged rather than the current set up where you have to remember to tick the box (if you can find the right box!!) to prevent this. We had this in the redet pop up used for the non-elasticsearch verification page.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/e2887e3b-c84b-4bd5-b33c-d979f69884b1)

**Comment by johnvanbreda** [comment]
I've fixed the checkbox so it doesn't updated the determiner. I've also fixed the layout of the redetermine popup. Having done those, I've not been able to get the Elasticsearch query failed message so if you are still seeing that please can you let me know exactly what steps you took before it happened?

**Comment by davidnicholls125** [comment]
Thanks, the pop up looks much clearer and the default tick will be a big improvement.
I've just edited a record and got the error message below.
From the elasticsearch verification page I filtered the 'unknown' taxon group
Selected record 34050301 and clicked on the record edit button
On the record I deleted my name from the 'identified by' box and saved it
The thank you page loaded with the error message
The change had saved however
I repeated the above on record 34049947 with the same outcome

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/2b001a02-c969-4f0c-a3f5-5104360cc675)

**Comment by johnvanbreda** [comment]
Ah, got it - it happens when saving a "New - being checked" record which explains why I didn't see the problem. I suspect the new Elasticsearch version on the server fails if searching for a species with an empty key where it tolerated it before. I've fixed this now.

**Comment by davidnicholls125** [comment]
Great, thanks.
