### ISSUE TITLE
Elasticsearch query failed

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#204]
I've just got the error message below when I loaded the species page for Rhyzobius litura. It looks like the latest record list at the bottom of the page that hasn't loaded.

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/9bb6c130-1807-4f9b-b433-3a1309d20ff7)

**Comment by johnvanbreda** [comment]
Seems to have been a broken entry in the Indicia cache which was cleared and fixed by clicking the Clear Indicia Cache button on this page: https://www.naturespot.org.uk/admin/config/iform/cache
