### ISSUE TITLE
Parish boundary update

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#205]
Some weeks ago I emailed you a shp file set of parish boundaries to update the current display (some boundaries have changed). It doesn't appear that these have been added yet so could you update the boundary layer please?

**Comment by johnvanbreda** [comment]
There are currently 307 NatureSpot parish boundaries and 296 in the supplied file. Shall I completely replace the current boundary set, or just update the boundaries where the names match leaving the extra ones in place?

**Comment by davidnicholls125** [comment]
The reason for the change is that some parish boundaries have changed - but I don't know which ones. Wiki says there are 233 Leics parishes and 57 Rutland parishes, which is 290 in total and different to your count. I think we should replace the full set.

**Comment by johnvanbreda** [comment]
I've sent a request to Jim at BRC as I need to update files on the new Geoserver to do this and I don't currently have access.

**Comment by johnvanbreda** [comment]
This is now done.
