### ISSUE TITLE
missing image - Brevicellicium olivascens

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#206]
Record 6475116 was verified and accepted in 2018 with an image. However the image isn't showing on the species page. I've checked the TVK entered on both Indicia and drupal and they are the same. Can you work out why it is missing?
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/a4d911c1-3d8d-434e-a44f-701c1b6fff36)

**Comment by johnvanbreda** [comment]
Have you fixed this? I can see the image on the species page OK.

**Comment by davidnicholls125** [comment]
No - but I'm still not seeing it... I've tried refreshing the browser window.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/5413ba8e-f3dc-49e0-8653-7ae5f4298e65)

**Comment by johnvanbreda** [comment]
Fixed - I was looking in Latest Images. The image had been copied to Drupal the day after the record was input, then the image link file deleted from Drupal. I've flagged the warehouse image so it is no longer considered already copied to Drupal.

**Comment by davidnicholls125** [comment]
When I moved the image to the gallery section, it didn't display on the species page. Checking the image it was missing a taxon entry so I entered the species and saved. It has now disappeared from the organise images page, though is showing in the latest images section. Maybe its a caching delay?

**Comment by johnvanbreda** [comment]
The taxa field on the species account wasn't filled in - hence the species account page wasn't linked to the taxonomy and couldn't show the images. Now fixed.
