### ISSUE TITLE
Gallery family order

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#208]
We've been trying to re-order the families in the Barkflies gallery so that they display in alphabetical order. We've removed the weightings and left the field blank - this didn't work. We tried entering zero for each family and this didn't change the order either. The families in the menu did change to alphabetical but not the gallery itself. Shouldn't it default to A-Z if no weightings are entered?

**Comment by johnvanbreda** [comment]
It's a bit difficult to see if what I've done worked as the families are currently sorted alphabetically (presumably the weights are currently set?), but I think this is now fixed. Please close if OK.

**Comment by davidnicholls125** [comment]
Thanks. I've removed the weightings (I entered 0 as it wouldn't accept an empty field) and the A-Z order has been retained so I presume this is working now.
