### ISSUE TITLE
Indicia log in default

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#209]
Would it be possible for Indicia to default to the page below when we log in?
https://warehouse1.indicia.org.uk/index.php/taxon_list/edit/8
It is tedious to have to filter for NS everytime when we can't access any other species lists anyway.

**Comment by johnvanbreda** [comment]
It would take a bit of work to do that unfortunately. One thought is to bookmark the page?

**Comment by davidnicholls125** [comment]
Good idea, I've done that, thanks.
