### ISSUE TITLE
Organise images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#21]
Please order the display of unpublished images newest to oldest (verification date). ie latest additions at the top.

We don't understand why the occasional image says 'warehouse image'. Here is an example on the Blue Tit organise images page.
![image](https://user-images.githubusercontent.com/80914584/114671422-fff67b80-9cfb-11eb-91b2-5e60ea7c1d22.png)

**Comment by johnvanbreda** [comment]
The ordering is a little more complex as it needs to behave differently for published images (sorted by priority) and unpublished (sorted by addition or verification date). A couple of hours work - please confirm if OK.

Contrary to what I'd thought yesterday, although I'd experimented with disabling the migration of image data from the warehouse to automatically create "links" in the Drupal content, this code is still running. Which is why the "warehouse image" only appears occasionally, these are images which are only on the warehouse. All the other images have an edit toolbutton so they must be Drupal content. 

I propose that we disable the background task that creates the image links, so they only get created when you start using them. Also as a longer term maintenance issue, we could delete all the images that are unpublished (at the same time marking the actual image date on the Indicia warehouse as "not yet copied over"), which will reduce the amount of Drupal content on the site significantly, making backups smaller and easier to manage.

**Comment by davidnicholls125** [comment]
Thanks John. Happy for you to go ahead with all these changes.

**Comment by johnvanbreda** [comment]
I've disabled the background task that automatically copies images into Drupal nodes (links). If this doesn't cause any issues with adding new images to species accounts then I can proceed with the clean-up of all the unpublished images.

**Comment by davidnicholls125** [comment]
I've just published one of the recent images that was displaying as a 'warehouse image' and it all worked OK. Will the clean up just remove the drupal links and leave the unpublished images showing as warehouse images? Can we then order these newest to oldest by verification date?

**Comment by johnvanbreda** [comment]
> Will the clean up just remove the drupal links and leave the unpublished images showing as warehouse images? 
- Yes, that's right
> Can we then order these newest to oldest by verification date?
- Yes, that will be possible once this is done. I'll check when I make these other changes.

Just a note that the clean-up itself will take a few hours as it needs custom code and will have to be done with care. So I'll leave this task until you prioritise it.

**Comment by davidnicholls125** [comment]
Please go ahead. We agreed that the 'approved development' label should be treated as a priority but I've added a priority 2 label so you can fit it in when you can.

**Comment by davidnicholls125** [comment]
New images are appearing as warehouse images but there are still lots of drupal linked images - shouldn't these be replaced by warehouse images?

**Comment by johnvanbreda** [comment]
@davidnicholls125 yes they should, but only once I've done the task of cleaning them all up. As it's a not completely trivial task whcih doesn't affect the end-user experience I've not tackled this yet - I felt other things were higher priority.

**Comment by davidnicholls125** [comment]
Agreed it's not urgent but it would be good to get the order sorted to make selection easier.

**Comment by johnvanbreda** [comment]
The order should now be most recently verified first for the warehouse images.

**Comment by davidnicholls125** [comment]
We need all unpublished images to be in order for this to be useful. Are you able to progress this now?

**Comment by johnvanbreda** [comment]
@davidnicholls125 just to keep you informed - I'm running the cleanup as a background task now, however there are 150,000 or so to delete, so it may take quite a while.

**Comment by davidnicholls125** [comment]
Is this working on a species by species basis - or more randomly? Please can you check the display order of the warehouse images? We want the most recently added to appear at the top but this isn't currently happening. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 it is more random - just working through the unpublished images page by page. 3/4 are done now so as soon as they are complete I'll double check the image order for the warehouse-loaded images which remain.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the image cleanup is now just about complete (it will be in an hour or so). As far as I can see from the code, the images should be sorted with the most recently verified first now. Is this working for you? If not please can I have an example.

**Comment by davidnicholls125** [comment]
The order still doesn't seem correct. Here is a screenshot of Latest Images with 4x Spangle Gall images on the first page. However on the Organise Images page they are well down the order.
![image](https://user-images.githubusercontent.com/80914584/135241729-13eb18aa-c305-4040-8731-218200853bda.png)

**Comment by johnvanbreda** [comment]
Got it - a mistake in my report query. Should now be fixed.
