### ISSUE TITLE
Photo of the month problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#213]
The 'winner' field in the image edit properties won't allow a previous month to be entered. The winner isn't decided until the month has ended so will always be a previous month. Can this restriction be removed please?

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/858d71bc-3862-464d-b6f2-d9988ce70487)

**Comment by johnvanbreda** [comment]
The field settings in Drupal have been set with a minimum value (see https://www.naturespot.org.uk/admin/structure/types/manage/image_link/fields/node.image_link.field_iom_month) which is currently 202401. I don't think I set this limit, maybe one of the team did as it makes data entry quicker?

**Comment by davidnicholls125** [comment]
I don't think I changed it but it is possible! I've removed it now however. Thanks.
