### ISSUE TITLE
Parish page problems

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#214]
The Burbage parish page is not displaying any parish stories. I've tried adding a couple of new ones and used the ?nocache suffix but nothing is showing. Please could you have a look?

**Comment by johnvanbreda** [comment]
On the Edit tab for the Burbage parish, I found the parish wasn't selected: 
![Screenshot 2024-02-14 at 11 45 54](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/d0736cde-1acc-47cf-b1dc-92d86a736ee7)

Now fixed.
