### ISSUE TITLE
iRecord 'activity' not linking

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#215]
I emailed you a week or two ago about the NS activity selected on the app not linking records to NatureSpot. I've just received another query from a different user about the same issue which I'll forward on. Please could you look at this as a priority? Thanks.

**Comment by johnvanbreda** [comment]
It turns out the configuration for this was missed when the server was moved recently. I've notified Biren and provided the files so he can fix it and ran the process manually so app records entered up to this point should now be moved across. The process will be automatic again when Biren puts the files in the correct location which I don't have permission to do.

**Comment by davidnicholls125** [comment]
Thanks John. Will Biren let us know when this is done so I can inform the recorders affected?
There is another Elasticsearch problem at present, I get a 'failed' error message whenever I add or edit a record.

**Comment by johnvanbreda** [comment]
I'll let you know when Biren has resolved the config issue - but note that any records entered so far have been moved already as I ran the process yesterday, it's just not yet automated.

Please let me know if the Elastisearch issue is still happening.

**Comment by davidnicholls125** [comment]
Thanks John, it seems to be fine now.

When the config is fixed, there is the possibility that further submissions will have been made between when you moved the previous batch and the automatic fix – unless these will be picked up by the config?

Dave

**Comment by johnvanbreda** [comment]
Thanks for letting me know. Don’t worry – I already checked that, the config will pick up any records that didn’t transfer, no matter when they were input.

Best wishes

John

 

From: davidnicholls125 ***@***.***>
Reply to: johnvanbreda/naturespot-d8 ***@***.***>
Date: Monday, 12 February 2024 at 09:56
To: johnvanbreda/naturespot-d8 ***@***.***>
Cc: John van Breda ***@***.***>, Comment ***@***.***>
Subject: Re: [johnvanbreda/naturespot-d8] iRecord 'activity' not linking (Issue #215)

 

Thanks John, it seems to be fine now. 

When the config is fixed, there is the possibility that further submissions will have been made between when you moved the previous batch and the automatic fix – unless these will be picked up by the config? 

Dave

**Comment by davidnicholls125** [comment]
Great, thanks.

**Comment by johnvanbreda** [comment]
Config is now fixed - closing
