### ISSUE TITLE
Download records not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#218]
I need to download records for two parishes but there appears to be a problem on the download data page below. 
https://www.naturespot.org.uk/content/download-data
I think the site list should just include parishes and wild places but seems to list every location name entered with records - many appear duplicated. I can't get any of the parishes to load a record list though it does report records for wild places. Also there isn't a download button that I can see.....

**Comment by johnvanbreda** [comment]
To fix this, I had to split the site into wild places and parish parameters so you can select each separately, hope that's OK. The download button is in the bottom right of the grid so requires you to use the browser scrollbar to scrolll over.
