### ISSUE TITLE
Wild Place map not working / private sites being listed

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#219]
Clicking on a Wild Place site on the map no longer brings up the summary and link for that site. This appears to have been lost in recent times.... Please can this be restored.
Also, private sites are listed when using the filters for the relevant parish (eg Woodhouse parish displays Maplewell Farm which is a private Wild Place site and shouldn't be either shown on the maps nor listed in the gazeteer or drop-down menu. (Private site' has been ticked on the drupal page).

**Comment by johnvanbreda** [comment]
It looks like private sites were never filtered out - now fixed.

The other issue relates to the server move to the cloud last autumn so I have raised a query with BRC IT support.

**Comment by johnvanbreda** [comment]
Clicking on a place boundary on the Wild Place map is now fixed.
