### ISSUE TITLE
Record list with links to species pages

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#223]
We want to be able to download a list of records that include links to the relevant species pages. Such links appear on the 'thank you' page but we can't download this list. Ideally we would include the page links in the record download - can this be done?

**Comment by johnvanbreda** [comment]
I can't add the proper URL, but there is a version of the link which looks like this which I've added:
[www.naturespot.org.uk/species_by_key?key=NBNSYS0000002246](http://www.naturespot.org.uk/species_by_key?key=NBNSYS0000002246)

When you follow the link, NatureSpot will redirect you to the correct page URL by automatically looking it up from the key.
