### ISSUE TITLE
RAG and recording advice missing

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#225]
The RAG rating and recording advice have stopped appearing on the records form and on the verification page.

**Comment by johnvanbreda** [comment]
Is that still the case? I've checked just now and I'm seeing both working OK:

![Screenshot 2024-04-17 at 13 43 19](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/a328e00a-0b24-452c-8c0b-004bd1bcd9ce)

And on https://www.naturespot.org.uk/verification-v2:
![Screenshot 2024-04-17 at 13 44 27](https://github.com/johnvanbreda/naturespot-d8/assets/2392594/e22f0eb7-ed00-4069-bddd-91afd1877243)

**Comment by davidnicholls125** [comment]
Still missing on my PC. I've tried refreshing the browser but this hasn't helped. On the verification page the RAG icon is showing in the grid but nothing shows in the right hand panel.

**Comment by johnvanbreda** [comment]
Can you try now please @davidnicholls125? It may have been caused by taxon keys on the page being set to ??????????

**Comment by davidnicholls125** [comment]
Thanks John, it is working fine now. Can you give me an example of a species given a TVK of ????????

**Comment by johnvanbreda** [comment]
Yes, it's actually just the "species" called ?

**Comment by davidnicholls125** [comment]
That entry has been there all along (together with '+ new species) so why has the problem just appeared I wonder?

**Comment by johnvanbreda** [comment]
I think this explains why you saw the problem and I didn't - it just depends whether there was a taxon ? on the page of verification data you were viewing. If there was, it broke the scripts on the page, if not, everything was fine. I don't think anything changed recently code wise as it was NatureSpot specific code where the problem was found.

**Comment by davidnicholls125** [comment]
OK thanks. Presumably you have amended the code to deal with it?

**Comment by johnvanbreda** [comment]
Correct.
