### ISSUE TITLE
Exomias pellucidus - missing dots on the VC55 map

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#226]
Records for this species are not appearing as dots on the map. The TVKs match on both Indicia and the species page. The name has changed from Barypeithes pellucidus to Exomias pellicidus so I've updated our entries but I don't think this explains why the records aren't being mapped. Please could you check?

**Comment by johnvanbreda** [comment]
I don't know why, but the copy of the records kept for reporting had not been updated with a new TVK at some point (the value stored was different). I've fixed this. I've also tested whether I can reproduce this on my own development setup and I can't - if I change a TVK then the associated records in the reporting tables are indeed updated (once the background tasks are given time to run). 

If you spot this problem again let me know exactly what you did in the warehouse user interface when making the change.
