### ISSUE TITLE
Euura fagi

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#228]
Images for Euura fagi were published on the species page (by Graham) but have since disappeared. He has resubmitted the record, verified it and though the images are on Latest Images and link to the correct species page they are not availavle in Organise Images.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/8bc0be12-1519-47c4-a988-d9350bbe52ea)

**Comment by davidnicholls125** [comment]
Another new species set up appears to have suffered the same problem - Aphis urticata.......

**Comment by johnvanbreda** [comment]
As far as I can see there is nothing wrong with the taxonomic information here and the keys are all correct. The images are on the warehouse OK and they have the flag set saying they have been copied to Drupal as expected. It's just that the Image link nodes have been deleted from Drupal somehow. I've searched my code and can't see how it would delete nodes other than if a user saves changes using the image organiser. Is it possible a mistake has been made?

To recover the images, "Show previously discarded warehouse images" on the Image Organiser.

**Comment by davidnicholls125** [comment]
Thanks. Graham set up the pages and moved the images initially. He has done this hundreds of times so it seems unlikely he would have accidentally removed the images but who knows!

**Comment by johnvanbreda** [comment]
If this happens again I'll add some more logging, so we know what happened and when (as long as we spot it before the event drops out of the Drupal logs).
