### ISSUE TITLE
Species count - Wild Places + Parish pages

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#229]
Please can you amend the species count on these pages to sum verified + those being reviewed (rather than just verified). It is causing some confusion given that the image and record list at the bottom includes all submissions. Thanks.

**Comment by johnvanbreda** [comment]
Done. Just to note though that the species list tab is still verified only, so let me know if you want that changed.

**Comment by davidnicholls125** [comment]
Thanks, good point. Can we add a status column and then include all submissions on the species list tab?

**Comment by johnvanbreda** [comment]
I suspect that's possible, though needs me to experiment a bit as there's no immediately obvious way to do that. We could more easily add a filter toggle so that you can show the list with or without unverified records?

**Comment by davidnicholls125** [comment]
OK let's do that for now.

**Comment by johnvanbreda** [comment]
That's done.
