### ISSUE TITLE
missing recorder names

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#23]
Every so often we see images on the Latest Images page that are missing the recorder's name. Checking on the verification page the recorder name is shown so is this an issue in transferring the data to the image link and can we prevent it happening?
![image](https://user-images.githubusercontent.com/80914584/114824250-8b374600-9dbc-11eb-9dfc-530057b65531.png)

**Comment by davidnicholls125** [comment]
Another example today:
![image](https://user-images.githubusercontent.com/80914584/116572814-317a6400-a904-11eb-9798-4272ed473fa0.png)

**Comment by davidnicholls125** [comment]
We are still seeing this problem on a regular basis.....
![image](https://user-images.githubusercontent.com/80914584/121743514-60861700-caf9-11eb-9acd-94bae66b656e.png)

**Comment by johnvanbreda** [comment]
I think this was because the app records handle the recorder name slightly differently. I've updated the report to cope with both approaches so this is hopefully now fixed.
