### ISSUE TITLE
Species page links on Wild Places and Parish pages

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#231]
Please can we add links to the relevant species pages on the 'species' tabs of both Wild Place and Parish pages. Thanks.

**Comment by johnvanbreda** [comment]
Link icon now added to the grid. I didn't make the species names clickable as I'd originally thought as that affects the sort behaviour if you try to sort by species name.

**Comment by davidnicholls125** [comment]
Thanks, that's fine. I've just noticed that the default list only includes verified records, please can we change this to all. Can we add an explanatory comment to the header (or tell me how if I can):
The species list below is based on all records for this site, some of which may be awaiting a verification check. To view just the species from verified records, tick the 'verified' box.

**Comment by johnvanbreda** [comment]
Done
