### ISSUE TITLE
36655709 edit problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#234]
When I tried to open a record in edit mode, the page below appeared saying 'occurrence attribute 17 is not linked to the survey. Do you know what has appeared here? I was puzzled by the long list of recorders that appeared in the grid for this record! The record (via the app) has come from the Wildlife Trust for the Charnwood project which we are a partner in so I'm keen to resolve this before more records are submitted. Thanks.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/6ec474ff-6984-44c3-9923-ca941c94e8d2)

**Comment by johnvanbreda** [comment]
Where did you get the link? The link should be https://www.naturespot.org.uk/edit-app-record?occurrence_id=36655709 which works OK. Also where did you observe the long list of recorders mentioned above?

**Comment by davidnicholls125** [comment]
Both on the verification page where it lists the records. I used the edit button in the right hand panel.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/c78441e5-55fb-453d-8cbd-5a6341c6737d)

**Comment by johnvanbreda** [comment]
This is now fixed - the app submitted records will switch to using the app edit form.
