### ISSUE TITLE
Ambigolimax - missing from Indicia

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#237]
A few weeks ago I amended the Indicia entry for Ambigolimax valentianus to just the genus Ambigolimax. However there is no Ambigolimax entry now listed in Indicia when I search for it, yet Ambigolimax valentianus still appears on the Submit Records species menu..... I'm very confused!

**Comment by johnvanbreda** [comment]
The database implies that Ambigolimax was deleted (maybe by accident?) on the 19th June. I can't search for it or A. valentianus on Submit records so maybe you were seeing data cached somewhere in the system. I've just undeleted it so the name will be back in the system shortly.

Please close once you've checked it's OK.

**Comment by davidnicholls125** [comment]
Thanks.
