### ISSUE TITLE
Parish page problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#239]
I've just created a new parish page for Cottesmore but neither the parish stories nor the Wild Place links are appearing. I think this is our first parish page in Rutland so wondered if this might be the reason? I vaguely recall that we added the Rutland parishes at a later time to the Leicestershire parishes. Please could you look into this. Thanks.

**Comment by johnvanbreda** [comment]
On the Edit tab for the Cottesmore Parish page, the Parish drop down (under the title) was not filled in. This tags the page to the parish and allows the stories that are similarly tagged to be shown, so without it you get no stories. I've corrected this.

**Comment by davidnicholls125** [comment]
Of course... sorry I should have spotted that!
