### ISSUE TITLE
D9 upgrade

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#24]
Following your advice we have decided that we should go ahead with the upgrade to D9. There is no immediate hurry but it is worth planning for. Could you first just confirm your estimate of the time needed?

**Comment by johnvanbreda** [comment]
Notes to self:
* Checked list of modules - 
  * Remove PHPf after checking code and converting to blocks/ 
  * Collapse_text needs v2.0 dev, stable release is due soon
  * IMCE is compatible even though not clear on module page
  * taxonomy_menu requires dev branch (but can't we remove this anyway?)
  * node_clone not available in D9 (but not-essential and we can use Quick Node Clone in future if required).
  * search_api_db is now part of the search_api module
  * ajax_loader - dev is OK for Drupal 9 but could remove this?

NatureSpot blocks to do (40 issues in Upgrade Status, all look easy to resolve)
NatureSpot theme to do.

Given the above, I estimate that if all goes extremely well, it could be done in 1.5 days effort. I would suggest allowing for up to 3  days in case unforeseen problems emerge.

**Comment by davidnicholls125** [comment]
Thanks John. Can you book it in for later in the year, say October/November so we can try to include it in a funding bid.
