### ISSUE TITLE
Mother of Pearl - missing dots

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#242]
The VC55 map for Mother of Pearl isn't displaying any dots for records pre 2020. Can you see why?
https://www.naturespot.org.uk/species/mother-pearl

**Comment by johnvanbreda** [comment]
Fixed - there was a TVK update at some point which had not been applied to the reporting copies of the older records. This was a bug a while back so maybe the change pre-dated the fix.
