### ISSUE TITLE
Species pages missing the search box

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#243]
When a species page is viewed by using the search box, the page doesn't always include the search box that should appear at the top of every species page. Example below. However, sometimes it does....!
![image](https://github.com/user-attachments/assets/3e57663a-1d05-457c-9604-76d613accf9f)

**Comment by johnvanbreda** [comment]
The search block is configured to appear on any page with one of the following patterns in the page URL (you can access these settings by clicking on the pen icon to access the shortcut menu when hovering over the block, then select Configure block - Pages tab):
```
/search/content
/species*
```

The Tachyporus chrysomelinus s.s. page does not have its URL alias set up, so appears at `/node/131071` and therefore the search block is not going to appear. If you edit the species account and set the alias to something like '/species/tachyporus-chrysomelinus-s-s' then it should work.

**Comment by davidnicholls125** [comment]
Thanks John, at least I know now!
