### ISSUE TITLE
Mobile phone log in problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#245]
It has been reported that when logging in on a mobile, selecting the Submit Records link then logs you out. Any ideas?

**Comment by johnvanbreda** [comment]
I can't reproduce this - will need more details, maybe a video if possible? Can you reproduce this?

**Comment by davidnicholls125** [comment]
No I can't reproduce it either. I asked her to retry which she did several times with the same result she says. What details should I ask for? How would she video the sequence?
