### ISSUE TITLE
Maps not updating / name changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#246]
Yesterday we updated the names of several beetles (both on Indicia and in the taxonomy) - list below. The TVKs were unchanged. However the VC55 maps are now not displaying the record dots. I've tried both ?nocache and ?refreshcache on the URLs and this hasn't made any difference so I presume this means it isn't a caching issue?
Also we added a new beetle species, Orchestes betuleti, and verified a record for this. The species isn't on the NBN yet but Chris Raper gave us the TVK which has been added to the entry on Indicia and on the species page. However neither the VC55 map is displaying nor have the images appeared on the species page. Please can you look at both these issues?
Is there a way to automate the updating of species name on drupal to match those on Indicia? Perhaps after we migrate to the UKSI? I guess it would require a change to the drupal species taxonomy and the title entry on the species page if there isn't a common name.
![image](https://github.com/user-attachments/assets/73cf1c6b-b87f-4df6-898d-47a6ff2bbe23)

**Comment by johnvanbreda** [comment]
As a quick fix I've refreshed the records where you had updated the names, as the raw data was correct but the reporting cache had the wrong TVK. I'm not sure why - I'd have to follow the exact steps you took through to see what happened, but the maps are showing OK now.

For the O. betuleti record, there was an errant carriage return in the TVK which I've fixed - the dot appears on the VC55 map now but the NBN map is broken - I'm not sure I can do much about that.

**Comment by davidnicholls125** [comment]
Thanks John. The NBN UK map won’t display because we have had to use a made-up TVK. The correct TVK is on the UKSI but hasn’t yet been added to the NBN.

Best wishes,

Dave

**Comment by johnvanbreda** [comment]
Can this be closed or does it need further investigation?

**Comment by davidnicholls125** [comment]
I think we can close it. I'll let you know if there is anything else that
comes to light.
