### ISSUE TITLE
Species page - default entry

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#25]
I've added a default content entry to the species champion field on the species page (via content types). However this only populates for new species pages that are set up. Is there a way to make it populate this field for all existing species pages? Around 8 have customised entries so we don't want to over-write these - though I could re-enter the text for these if necessary.

**Comment by johnvanbreda** [comment]
I've not done this before but I found this module: https://www.drupal.org/project/field_defaults. Let me know if you need further help.

**Comment by davidnicholls125** [comment]
Thanks, that looks likely to do it. I'll give it a go.
