### ISSUE TITLE
Parish page statistics + download

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#250]
The statistics tab on the parish page is paginated and the download button only includes the first page. Please can we remove the pagination so that all taxon groups are included in the download?

**Comment by johnvanbreda** [comment]
I've removed the limit from the download but left the pagination in place. Closing, but please feel free to re-open if you want the pagination removed from the table as well.

**Comment by davidnicholls125** [comment]
Thanks, but please remove the pagination as well. It isn't going to be a long list so it can easily go on one page.

**Comment by johnvanbreda** [comment]
Done
