### ISSUE TITLE
New species not updating

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#251]
New species added to our Indicia inventory are not appearing on the Submit Records form. (eg Ocys tachysoides and Clauzadea monticola). It usually only takes 10 minutes to appear but this has now been hours. Maybe something has happened following the upgrade?

**Comment by johnvanbreda** [comment]
@davidnicholls125 yes, I'm waiting for IT Support at CEH to fix an issue with email connections on the server which are stopping the background tasks from completing.

**Comment by johnvanbreda** [comment]
This should be catching up now. Will close but please re-open if not working by this afternoon.
