### ISSUE TITLE
switching off iRecord recording advice

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#253]
Can we switch off the yellow triangle recording advice that appears when a species is selected on the recording form (as shown below)? We have had a few recorders report their confusion with this, especially as it isn't always consistent with our own recording advice.

![image](https://github.com/user-attachments/assets/72f71b5c-7184-4571-b4a2-9052f2779e6a)

**Comment by johnvanbreda** [comment]
Done
