### ISSUE TITLE
Indicia log in

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#254]
Please can you create an Indicia account for Helen O'Brien (one of our trustees and chair elect). Also, can you let me know who else has accounts? (It's possible some of our trustees with accounts have since left). Thanks.

**Comment by johnvanbreda** [comment]
There are a few Helen O'Briens on the warehouse-  can you email me the email address of the correct account please?

Other users with admin access:
David Gould
Sue Timms
Alan Cann
and yourself.

**Comment by davidnicholls125** [comment]
Thanks. Helen O'Brien (dr.helenob@gmail.com)

**Comment by johnvanbreda** [comment]
She can log in as Helen_O_Brien_2 with no password - it will ask for a password on first login.
