### ISSUE TITLE
Missing/delayed images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#26]
I'm logging the issue that Graham raised by email yesterday, regarding images not appearing on the species page:
_I verified a record for Dotted Bee-fly (Bombylius discolor) before lunch and the images appeared in 'Latest Images' quite quickly, but 6 hours have passed since then, and I still can't see the images under 'Organise Images'/'Unused Images'._
I've just checked and it still hasn't appeared. This is a fairly regular problem and one that affects more images than we realise - as we only notice the missing images when we want to publish one that has just been verified or seen in Latest Images. Is there a way to resolve this in a more long-lasting way?

**Comment by johnvanbreda** [comment]
In this particular case, the record is outside the VC55 boundary unfortunately. If you can provide other examples I can check.

**Comment by davidnicholls125** [comment]
Thanks John, I didn't think to check the grid ref. I'll close this for now and reopen it if there is another example that we spot. I know Graham has raised similar issues with you a few times in the past and I think there was some kind of blockage on Indicia.
