### ISSUE TITLE
Chaetosphaerella phaeostroma - missing images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#260]
The species page for Chaetosphaerella phaeostroma had an empty 'taxon' field as the species hadn't been added to the taxonomy. We've now done this and amended the species page but no record images are showing. However all the images did appear in Latest Images..... (Can you explain why this happened? You mentioned the other day that images are linked to the species name and not the TVK so I would have expected them to show on the species name when we amended the taxon entry....)

**Comment by johnvanbreda** [comment]
The images are flagged as "copied to Drupal" on the warehouse so the image links have already been created, however they are not linked to C. phaeostroma presumably as they were copied before the species was ready. I had a quick look at setting up a view that could find the images for you but realised it was easier to find them manually:
1. Go to the image organiser for C. phaeostroma.
2. Click "Show previously discarded warehouse images".
3. Right click on an image and copy the path, e.g. 
https://warehouse1.indicia.org.uk/upload/med-o_1ibjeojbkv8b1b821l361dd413okk.jpg.
4. Discard everything up to and including med- to get the file name, in this case it's o_1ibjeojbkv8b1b821l361dd413okk.jpg.
5. Go to the NatureSpot Content admin page and search for this file name (it will be the title of the image link).
6. Edit and set the taxa field correctly.
7. Save and repeat for the other images.

Are you OK to do it this way?

**Comment by davidnicholls125** [comment]
Thanks John. I've just gone to do this and found that the missing four images have now appeared and been published. Clicking on the discarded warehouse images button reveals a four further copies of the same images. These hidden images appear to have the correct name format and taxon entry. Has this been an automatic correction?

**Comment by johnvanbreda** [comment]
The images stored on the warehouse don't contain taxonomic information directly - they are linked to the occurrence which is in turn linked to the taxonomic data. So if a taxon name is corrected, all the images linked to associated occurrences will automatically be "fixed".
