### ISSUE TITLE
Species page additions

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#28]
We have been admiring some of the features on the Netherlands equivalent to iRecord (https://waarneming.nl/) and would like a quote to add the following to our species page. I think these would be best on another tab.

- phenology chart
- record totals by year
- grand total / total recorders
- list of records (paginated)

If any of these are complicated to develop then please flag them up. Thanks.

**Comment by johnvanbreda** [comment]
Approx 5 hours work.

**Comment by davidnicholls125** [comment]
Thanks. I'll build it into a funding bid.
