### ISSUE TITLE
Formatting field headers

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#3]
We have created a new content type - Species Champion Statement. How do we format the headers for each field with CSS styling? We want the headers to have the h2 format.

Three sample statement pages have been set up. Will the format changes apply to these existing pages?

**Comment by davidnicholls125** [comment]
If you get chance, please could you look at this question as we would like to launch the scheme.
https://www.naturespot.org.uk/node/add/species_champion_statement
Thanks.

**Comment by johnvanbreda** [comment]
I've done a couple - here are the steps:
Manage display tab
At the bottom of the page, I changed "Select a layout"  from -None- to Bootstrap One Column. For some reason, I don't think the -None- layout option allows you to control things like label formatting. You won't need to do this step as it only needs to be done once per content type.
Click the Cog icon in the row of the field to change.
Set "Choose a field template" to "Expert"
Tick the Label wrapper checkbox and set the Element to h2. 
Click Update to update the field, then the Save button at the bottom.

**Comment by davidnicholls125** [comment]
Many thanks.
