### ISSUE TITLE
Learning to Identify Wildlife course

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#30]
This is mainly a heads up on a funding submission we have made to set up an online course (with some face to face group training sessions) to help people identify 100 species in their area. The bid had to be turned around in a couple of days so I've just guessed a budget! If it is successful we can discuss the details further. 
There are a couple of things that it would be useful to think about and if possible get an idea of cost. We've already asked you for a quote on setting up an 'activity' tag (its one of the logged issues). This is we can filter out records relating to specific projects/activities (eg records submitted by members of a particular natural history group where they want to be able to collate records from their own members on a monthly basis. This proposed course would be another example I think whereby participants are asked to select the course from the menu of 'activities' on the submit Records form. We will want to use the activity tag (in this case the course) to provide reports and feedback.
The other issue is the milestone set up on Indicia. We would want to set up milestone notifications for records relating to the course specifically, eg 10/25/50 records submitted. (You set up something like this for the Young Recorders scheme so I assume this isn't a problem). On reaching 100 we want to issue a certificate - can this be linked to a milestone?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I think this is all achievable through the activities setup and milestones form on the warehouse which already accepts a group ID as a filter. 
For costing purposes, I would allow a few hours for the activities setup (already mentioned on the other issue) plus another few hours for testing around the milestones page, since I know you had a couple of issues with it recently. So a total of about 1 day.

**Comment by davidnicholls125** [comment]
Thanks John. The funding should cover this so I'll reopen the issue when we hear.
