### ISSUE TITLE
Website problems

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#31]
We seem to have three problems:
1. The sex and attribute boxes on the records form are not working
2. The verification page times out when using the filter boxes when all records are in the grid
3. Another example of a missing name from an image - see below (the recorder emailed to ask why). This seems to happen quite regularly and I've reported similar examples before (there is an issue logged on github). Is it a glitch in creating the image link? Can anything be done to prevent it? 
![image](https://user-images.githubusercontent.com/80914584/116570377-2292b200-a902-11eb-8231-55765d8bad52.png)

**Comment by johnvanbreda** [comment]
I've fixed the first issue. Can we keep the other 2 issues separate please (and attach the info about the missing name to the other issue) as it will be easier to see the priorities that way.

**Comment by davidnicholls125** [comment]
Thanks. I've moved the other two.
