### ISSUE TITLE
TVK / Name updates

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#34]
We have come across a few instances of the TVKs and some names being changed - flagged by the thank you page erroneously showing records as 'new species'. Examples include: Trochulus hispidus, Radix balthica, Cyclops and Whitethroat. should these have been picked up after the last iRecord species update by the software you wrote? I recall that we should receive a list of changes after each update but nothing was received last time. Should these changes have been picked up?

**Comment by davidnicholls125** [comment]
Related to this issue, we have two entries for Tor-grass on the menu but there is no Indicia page for B. rupestre. Why is it showing on the menu?
![image](https://user-images.githubusercontent.com/80914584/126033982-92f6c0d8-affe-427b-b5ec-83c15296bf05.png)

**Comment by davidnicholls125** [comment]
Another oddity. If you type Tor-grass then both Brachypodium rupestre and B. pinnatum agg. are listed, but if you type Brachypodium then only B. pinnatum agg. displays......

**Comment by johnvanbreda** [comment]
B. rupestre had been deleted at some point, but not the associated common name (Tor-grass). That was a bug I think we picked up on a few months ago. So, I've deleted the common name for B. rupestre (not touching the one for B. pinnatum agg.). That should clear up the Brachypodium issue.

I'll take a quick look at the other species you mention above.

**Comment by johnvanbreda** [comment]
P.S. I checked the change metadata on the Brachypodium data and there is no indication it was altered by a UKSI update.

**Comment by johnvanbreda** [comment]
Ok, I think I have got to the bottom of this. It's similar to the deletion issue above - changes being applied to the accepted name via the warehouse user interface were not updating the common names and synonyms for the external key changes, just the accepted name was changing. I've fixed this in the code and also applied the following script to fix NatureSpot data:

```sql
select t.id as taxon_id, cttl.taxon as cached_taxon, cttl.external_key as correct_external_key, t.taxon, t.external_key
into temporary to_fix
from cache_taxa_taxon_lists cttl
join taxa t on t.id=cttl.taxon_id
where cttl.taxon_list_id=8 
and t.external_key<>cttl.external_key;

select * from to_fix;

update taxa t 
set external_key=correct_external_key, updated_on=now(), updated_by_id=3
from to_fix tf where tf.taxon_id=t.id;
```

It will take a few hours to fully update in the system but this should have sorted it. Please close when you've confirmed it's OK.
