### ISSUE TITLE
Latest Images

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#35]
The Latest Images page isn't available to non-logged in users, yet it it used to be I'm sure? I recall that we removed the pagination so non logged in users could only view the first page (which is fine if still necessary with elasticsearch). Could you check why it is no longer available please?

**Comment by johnvanbreda** [comment]
I suspect it had been removed in an attempt to tidy the double menu link issue which administrators will see - explained in email. The logged in version is now restored.

**Comment by davidnicholls125** [comment]
Thanks. I removed the duplicate menu link yesterday but only after you had been working on the problem so this wasn't the initial cause, but it all seems OK now!
