### ISSUE TITLE
Submit records form deleted

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#36]
Alan appears to have deleted the Submit Records form in error!! Not sure how.... Please can you restore it from a backup?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I have a recent backup so should be OK to do this - I'll look now.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I restored the copy I took on 12th April so hopefully OK now.

**Comment by davidnicholls125** [comment]
Thanks John!

**Comment by davidnicholls125** [comment]
Just noticed that the sex and attribute dropdown menus are missing.

**Comment by johnvanbreda** [comment]
@davidnicholls125 - sorted, I missed a checkbox on the configuration form.

**Comment by davidnicholls125** [comment]
Thanks again.

**Comment by davidnicholls125** [comment]
We are getting a lot of reports that the form isn't visible. It is to me but not when I masquerade as a standard user so there must be a permission issue. Please can you check this?

**Comment by johnvanbreda** [comment]
I think this was the old problem with content access permissions needing to be rebuilt but that was a huge task last time, so I changed and saved the permissions a few times and it seems to have worked!

**Comment by davidnicholls125** [comment]
Thanks, it seems OK now.
