### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#37]
I think recaptcha v3 has stopped working, we have been inundated with spam registrations.

**Comment by johnvanbreda** [comment]
I've enabled yet another anti-spam module. If it helps we can uninstall recaptcha V3 and possibly recaptcha.

Can you let me know how that goes please @davidnicholls125?

**Comment by davidnicholls125** [comment]
Will do. It's odd that it worked perfectly until yesterday....

**Comment by davidnicholls125** [comment]
No more spam received so it appears to be working fine now thanks.

**Comment by davidnicholls125** [comment]
It appears the new anti-spam is blocking all genuine registration attempts. 'Anti-bot verification failed' appears as an error message. I've tried and got the same result. When this message appears, the recaptcha box also appears at the bottom of the form. Do you know why recaptcha3 stopped working? It was doing a good job until Wednesday/Thursday so presumably something happened around then....

**Comment by johnvanbreda** [comment]
Actually, I think this message is coming from the Recaptcha-v3 which seems to be behaving unpredictably. See https://www.drupal.org/project/recaptcha_v3/issues/3136745. I've reverted to v2 just for now and I'll look into this further next week when back at work.

**Comment by davidnicholls125** [comment]
Thanks. The error message isn't the same as indicated on the link....

**Comment by johnvanbreda** [comment]
"Antibot verification failed" is mentioned in comment 9 in that thread, also I've confirmed that this message does come from the Recaptcha v3 modules' code.

**Comment by johnvanbreda** [comment]
I've just successfully registered a new account (with a caveat that I'll add another issue for). Also there doesn't seem to be any recent spam so I the anti-spam is OK currently.

**Comment by johnvanbreda** [comment]
There are some new registrations and nothing that looks like spam this morning so I think this is now OK?

**Comment by davidnicholls125** [comment]
Yes it seems to be working OK now, thanks.
