### ISSUE TITLE
Gallery species links not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#38]
I've just received this from one of our verifiers. Could you investigate please?

Within the bees/wasps, some (all?) species are not coming up from the gallery thumbnails. Issue is that there is an extra index.php/ in the hyperlink:

This does not work:

https://www.naturespot.org.uk/index.php/index.php/species/ophion-minutus

This should:

https://www.naturespot.org.uk/index.php/species/ophion-minutus

**Comment by johnvanbreda** [comment]
@davidnicholls125 I can't reproduce this. The links I get are all showing without the /index.php at all.

Please can you provide a link to the page with the broken links on, in case I'm misunderstanding.

**Comment by davidnicholls125** [comment]
I can't either. I'll go back to Mark and see if it is still an issue for him. The link I get for Ophion minutus is: https://www.naturespot.org.uk/species/ophion-minutus
Can you think of any reason why it might occur as a temporary glitch?

**Comment by johnvanbreda** [comment]
Ah - got it. If the species gallery has index.php in the URL (which is valid, although unusual) then it generates broken links as suggested. https://www.naturespot.org.uk/index.php/gallery/bees-wasps-ants for example. 

So, what we really need to know is how the user came to the gallery with index.php in the URL?
