### ISSUE TITLE
Wild Places pagination for non-logged in users

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#39]
Is there any reason why we couldn't include pagination for images and records on the Wild Places and Parish pages for non-logged in users? The number of images is much less than for the Latest Images pages so perhaps it wouldn't cause the same performance issue when crawled by bots? We are promoting these pages with parish councils and councillors viewing the pages casually won't get much of an idea of the species on the sites. Also, sometimes the recent images on display are a bit technical so don't reflect the site/area as we would want. If it's not a problem could you add these? Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I'm not sure that's the right solution - if you look at Bagworth & Thornton, there are several thousand images and records and when combined with various sort orders on the grid, there is an awful lot of combinations a search bot might want to index. Then multiply this across all the parish and wild places...

I think it would be useful to try and think what the typical non-logged in user wants to see when they visit the site's page - as I'm not sure paging through a long list of records is really that helpful. Then design the reporting shown with that in mind. E.g. I could imagine wanting to know:
1. If I visit the site today, what species might I find (i.e. what is typically recorded there at this time of year).
2. What are the best pictures that have been taken of species at this site (i.e. these could be the ones used in the gallery).
3. Are there notable species at this site?
4. Once this technology is availabe (soon I hope!) - what species should be at this site that haven't been found.

I'm sure you can think of others, but my point is that none of these are supported well by adding the pager.

**Comment by davidnicholls125** [comment]
Is it possible to limit the pagination to say 10 pages? The reports you suggest would be interesting to add at some point but aren't really resolving the need. To illustrate this we are currently surveying 50 verges (all with Wild Place pages) on behalf of the relevant parish council. We have promoted the pages as a communication resource so local people, including parish councillors, can see what has been found there. Most won't want to register but would expect to get an idea of the results of the survey from the Wild Place page. If we could limit the pages available it would be a workable compromise.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I think that should indeed be possible, though I'm still slightly uncomfortable that this is a compromise that might still cause issues (e.g. what happens if the 11th page has the interesting record on it?). 
When you say the parish councillor should be able to "see what has been found there" do you think they are interested in the actual records, or are they interested in the species list? Or is it that they want to see the species that have been recorded as part of the recent recording effort in particular? I'm thinking that we could make the species list more accessible/obvious as this is already complete. Or we could put a "last month" filter on the recent records. That might be slightly more logical than just showing 10 pages.

**Comment by davidnicholls125** [comment]
A last month filter sounds like it would do the job. We should also add a note to explain that you need to be logged in to view all the images and records. Parish councils will be sent a full report in due course so it is really to give them a flavour of the findings. Also the relevant Wild Place URL has been promoted to the local community so they can be kept informed and hopefully engaged. I do have on my wishlist the idea of making the tab headers more pronounced (I think they can be easily overlooked at present) so if this is possible to tweak then please do that. Can these changes be applied to both Wild Places and Parish pages please?

**Comment by davidnicholls125** [comment]
Another thought - if we only show records and images from the last month, we wouldn't want the page to show no records and images if nothing has been submitted in the last month. Can we have a filter that selects either the last month's data but displays a minimum of 3-5 pages? Also apply this to Latest Images if possible?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I'm not entirely comfortable with a complex rule for defining the number of records to show, firstly because it means the code will have to run a query first to check if the last month's data encapsulates 3-5 pages, then run it again to find the records to show either filtered by date or by total number of records. As well as the extra performance hit, it may be a bit confusing for the user that the records list operates in 2 different ways.

I could easily make it so that when not logged in, it shows 50 records with a link to suggest they log in to see more. We could probably just list the records without pagination - that would be simpler to code.

**Comment by davidnicholls125** [comment]
That should work as a reasonable compromise for records but what about the images? There are 8 images per page so we would need some pagination here. Would a limit of 5 pages of images work?

**Comment by davidnicholls125** [comment]
John, can we get this resolved please? I've had a couple more emails complaining that parish councillors have tried to see the species found on their verges but can only see a few.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've done the records grid. For the photos, because of the way the total records and the paging interacts its easier for me to increase the number shown to 16 (or higher?) rather than allow multiple, but limited, pages. Is that OK?

**Comment by davidnicholls125** [comment]
Thanks, that should be OK (I'll let you know if we want any more images). You also mentioned adding a message that to see all records and images you need to be logged in. Also, is there a simple way to make the tab headers more prominent?
![image](https://user-images.githubusercontent.com/80914584/122957614-03e8ee80-d37a-11eb-8373-f2dbaa905fa6.png)

**Comment by johnvanbreda** [comment]
I'll add the message.

Would this look OK? 
![Screenshot 2021-06-22 172139](https://user-images.githubusercontent.com/2392594/122963699-6e9c2900-d37e-11eb-8a0e-1f5461543c5c.png)

**Comment by davidnicholls125** [comment]
It's an improvement, let's try it.

**Comment by johnvanbreda** [comment]
Done - I've made some very slight additional tweaks, i.e. strengthen the border around the active tab and changed the tab colours so it's clear that the active tab is joined to the "paper".

**Comment by davidnicholls125** [comment]
Thanks, that looks better. The 'limited' message needs to refer to the images as well as the records. Perhaps amend the text to: "The images above and record list below is limited. To view more you need to log in."

**Comment by johnvanbreda** [comment]
I've done that. It will take a little while to appear everywhere due to caching.

**Comment by davidnicholls125** [comment]
Thanks.
