### ISSUE TITLE
Milestone problems

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#4]
I sent you a couple of emails on 4th March about a problem with setting up new milestones on Indicia. I've copied the text below so it is on this system.

As an output for a grant we want to add a few more milestones, however when I've gone to the Indicia new milestone page I'm getting the error message below.

Are the milestone notifications sent retrospectively? If so, can we prevent this? 

![image](https://user-images.githubusercontent.com/80914584/112359358-198e3f80-8cc9-11eb-993f-d7d4bffa7c4b.png)

Another milestones problem - I've tried to edit the message on an existing milestone but it won't save - giving the message below.

The message in the 'First Record' milestone is entered as html - does this matter?

![image](https://user-images.githubusercontent.com/80914584/112359531-43dffd00-8cc9-11eb-9019-e7b2e0c7d53c.png)

**Comment by johnvanbreda** [comment]
I could not reproduce the website_id warning message - if you can still reproduce it, let me know the date and time so I can check in the logs.
I've fixed the error on save of an existing milestone. 
There is no problem having HTML in the message for the first record milestone.

**Comment by davidnicholls125** [comment]
Just tried to create a new milestone (20.10 29Mar) and got the same error message.
![image](https://user-images.githubusercontent.com/80914584/112887552-395ba400-90cb-11eb-82d0-c626de260fd9.png)

**Comment by johnvanbreda** [comment]
Hi @davidnicholls125 - please can you let me know if this happens immediately when you go to the form for creating a new milestone, or after you've pressed save? Also can you let me know the URL of the page at the point the error appears please?

**Comment by davidnicholls125** [comment]
It is there as soon as I open the form.
http://warehouse1.indicia.org.uk/index.php/milestone/create/?

**Comment by johnvanbreda** [comment]
That URL is incorrect. Are you following this route to the create a milestone form, or something else?
* Admin -> Websites
* Click Edit for NatureSpot.
* Milestones tab
* Click Create Milestone button.

**Comment by davidnicholls125** [comment]
I was using a URL link I'd added to our help pages from previous use. Thanks I'll use this path from now on.
