### ISSUE TITLE
Litespeed cache module issues

### ISSUE THREAD

**Issue by johnvanbreda** [johnvanbreda/naturespot-d8#40]
The Drupal LSCache module is causing a couple of problems. First, if you visit https://www.naturespot.org.uk and you are not logged in, when you log using the home page login form, the page reload after submitting the form gets intercepted sometimes by LSCache and you are shown the cached version of /home, which causes you to get logged out.

Secondly, after registering as a new user, the registration redirects to the home page and LS cache intercepts it again. This time the problem is not that you are logged out (as you are not logged in yet) but it means that the message about your registration email is never shown.

I have tried to work out a way of fixing this but spent an hour on it without success, though I do think there might be a way to do it. It might be also worth asking Clook since they originally suggested LS cache.

**Comment by davidnicholls125** [comment]
Clook say there is an update to the litespeed plug in and can we install this then let them know if the problems persist.

**Comment by johnvanbreda** [comment]
Please can you ask Clook where the update is? I've looked at the Github repository at https://github.com/litespeedtech/lscache-drupal and we have the latest code.

**Comment by davidnicholls125** [comment]
Latest from Clook:
The code in lite_speed_cache/src/Cache/LSCacheTagsInvalidator.php and lite_speed_cache/src/Form/LSCacheForm.php are different in the version on GitHub to the ones on your site.

**Comment by johnvanbreda** [comment]
Thanks - I'm not sure why, but the code we had applied included the very latest code change, but not some of the ones prior to this. I've just applied the very latest and cleared all the caches. At this point in time it seems to work but I think it tends to work for a while after a cache clear anyway so we may not know if it really worked till later.

**Comment by davidnicholls125** [comment]
Thanks. We'll have to monitor it but fingers crossed!
