### ISSUE TITLE
Species menu anomaly

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#42]
We've noticed that Hare's-tail appears on the record form species menu but not the scientific name for this - Lagurus ovatus. There is no Indicia entry for Lagurus and there isn't a search option for common names so we are stuck with regard to investigating it further. We did have an entry for this species some time ago but deleted it last year. It looks like the menu hasn't fully updated following the deletion, or is there still a hidden entry on Indicia?

**Comment by johnvanbreda** [comment]
When the scientific name was deleted, the common name was left so it was effectively "orphaned".

As there is a single record attached to the Hare's tail name, I've undeleted the scientific name, but then marked both names as "allow_data_entry=false" so they won't appear in the recording form species list.

**Comment by davidnicholls125** [comment]
I'm puzzled that there is a record the taxon was deleted because there wasn't one. I've search for it and nothing appears on the verification page nor on Indicia. Where can I find this record?
Was it a glitch that the common name was orphaned when we deleted the taxon, or should we be doing something different?

**Comment by johnvanbreda** [comment]
@davidnicholls125 The record was ID 20588933 - I was looking at the raw data though and didn't spot that it was a deleted record (deleted data stays in the database with a flag set to say it is deleted).
If you let me know the steps you normally take to delete a taxon I can test it here and make sure this was a glitch.

**Comment by davidnicholls125** [comment]
Thanks. Very simple - search for the species in Indicia, go to edit and select 'delete' at the bottom.
![image](https://user-images.githubusercontent.com/80914584/122021774-e6d27f80-cdbd-11eb-8ed2-3274306aae70.png)

**Comment by johnvanbreda** [comment]
There was a problem where the Delete button would leave common names orphaned which I've fixed in the code (not released yet). I've used the following query on the warehouse (which returns nothing) to confirm that this isn't actually a problem in the data:
```sql
select ttl.id
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id and t.deleted=false
join taxa_taxon_lists ttlp on ttlp.taxon_meaning_id=ttl.taxon_meaning_id and ttlp.deleted=true and ttlp.taxon_list_id=8 and ttlp.preferred=true
left join taxa_taxon_lists ttlp2 on ttlp2.taxon_meaning_id=ttl.taxon_meaning_id and ttlp2.deleted=false and ttlp2.taxon_list_id=8 and ttlp2.preferred=true
where ttl.taxon_list_id=8
and ttl.deleted=false
and ttl.taxon_list_id=8
and ttl.preferred=false
and ttlp.id is null
```

**Comment by davidnicholls125** [comment]
I'm told we do have a potential record for Lagurus ovatus. Can I change the code to allow it to show on the submit records form or do you need to do this? 
"allow_data_entry=false"

**Comment by johnvanbreda** [comment]
I've done this for you, though you should be able to do this via the checkbox on the warehouse taxon edit screen.

**Comment by davidnicholls125** [comment]
Thanks. I was looking for the code you mentioned but realised it is a simple check box.
