### ISSUE TITLE
Verification page filters

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#44]
The elasticsearch verification page filters don't work for the + and ? species entries. I've checked on the old page and they are working OK there. Could you fix this please?
![image](https://user-images.githubusercontent.com/80914584/121944052-1e9fdf80-cd4a-11eb-88c7-f846d7d210da.png)

**Comment by johnvanbreda** [comment]
Search for "new species" works (as special characters generally don't work for text searches).
In which case, is a solution for ? to rename it to "? query". Or, I could add a special drop down for filtering to + & ? species in the toolbar.

**Comment by davidnicholls125** [comment]
That's fine now I know thanks (previously + and ? worked on their own). We can just search for 'new' and 'unknown'.
