### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#45]
The record below was verified over 24 hours ago but the image hasn't appeared on the species page. Do you know why this keeps happening and can we do anything to prevent it?
![image](https://user-images.githubusercontent.com/80914584/122574766-ea793700-d047-11eb-867b-66a99ddac74a.png)

**Comment by johnvanbreda** [comment]
There may have been a glitch in the spatial indexer at the moment this record came in as a few records input around the same time also don't have a link to the VC, which underlies the problem. I've re-scheduled them all to be indexed but it will take an hour or two to come through.

**Comment by davidnicholls125** [comment]
Not sure if this is still a work in progress? Simon asked why his images below are appearing on the species page and Kinighton parish page but not on Latest Images (they were verified a couple of days ago). Also I've tried deleting a few images for Libellula depressa and after the usual delay nothing had changed - the bin icons were still highlighted in red. What happens if we delete warehouse images?
![image](https://user-images.githubusercontent.com/80914584/123133972-35c88680-d448-11eb-865b-757711b6705c.png)

**Comment by johnvanbreda** [comment]
I found Simon's images on page 22 of the image organiser so I think there isn't a problem with this record.

When you delete a warehouse image, it should get marked in the warehouse as unwanted, so excluded from the images loaded by the organiser. It's not actually deleted of course. I took the liberty of deleting the very last warehouse image - https://warehouse1.indicia.org.uk/upload/med-o_1f8ak5hftrlidii1bi41b4t1cspb.jpg, then clicking Save. After doing so, the image has disappeared from the organiser so I think it worked OK. Which images did you try to delete?

**Comment by davidnicholls125** [comment]
Thanks, he must have missed it. I had selected 20-30 images which still showed the red bin icon after saving, however I've rechecked and they have now gone so maybe the page hadn't refreshed? I've tried a few more and this time it worked fine.

**Comment by davidnicholls125** [comment]
I've just heard more from Simon and I had misunderstood the issue. It is that images are missing from the gallery on the Wild Places page. This is also true of the Parish pages. Most of the recent records listed on these pages have images but these are not displaying in the gallery above. Could it be a problem with the display order or are they not coming through to the page?

**Comment by johnvanbreda** [comment]
Ah - I see. The latest images report was only including images that were marked "Copied to Drupal" but this is no longer an automated process, so they won't appear unless added to the gallery. I've changed this logic so they are included unless they were deleted (rejected) and Simon's images are now on page 2.
