### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#46]
To log in I need to enter my details twice. The first time it just returns to the non-logged in screen but works fine rentering the details. I've repeated it several times with the same issue.

**Comment by johnvanbreda** [comment]
@davidnicholls125 this is the same old issue with LS Cache showing the cached version of the home page rather than allowing Drupal to receive the login data and log you in. I think we left it that you would ask Clook?

**Comment by davidnicholls125** [comment]
I didn't get a clear response from Clook last time so have raised it again.

**Comment by davidnicholls125** [comment]
I'll close this issue and report back on the existing Litespeed issue.
