### ISSUE TITLE
New parish page not linking to Indicia

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#49]
I have set up a new parish home page for Ashby de la Zouch but it isn't linking to the boundary file on Indicia. 
https://www.naturespot.org.uk/Ashby
The boundary file is entered as Ashby-de-la-Zouch so I wondered if the drop down menu on the set up page needs to match, however when I tried to change the field settings it wouldn't allow it because the entry has already been used for several Wild Places pages. Can you advise please?

**Comment by johnvanbreda** [comment]
The location name on the warehouse (http://warehouse1.indicia.org.uk/index.php/location/edit/337) is "Ashby-de-la-Zouch CP". This needs to match the node title (currently Ashby) with the addition of " CP" on the end, so either changing the node title to Ashby-de-la-Zouch or changing the location name to just Ashby on the warehouse would work.  

Is there any reason not to just change the node title to Ashby-de-la-Zouch?

**Comment by davidnicholls125** [comment]
Thanks. I've changed the title to Ashby de la Zouch and it works (the CP isn't needed). I was thinking the link came from the parish dropdown menu under the title but I think this is actually the link to the related parish stories.
