### ISSUE TITLE
Adding a 'project' grouping to records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#5]
Some local groups/projects would like to encourage their members/participants to record via NatureSpot but need to be able to collate all the data from this grouping. Could we for example add a 'project' field to the records form (or perhaps make use of the existing sample comment field?) that recorders could choose to select when they submit records. If this field was then added to the download we could filter on it. Ideally though we would give permission to certain members to directly download the data for their own project.

**Comment by davidnicholls125** [comment]
This also relates to the 'Learning to Identify Wildlife' course I've just submitted as separate issue.

**Comment by johnvanbreda** [comment]
This is an exact mirror of the "Activities" functionality on iRecord, which could easily be named Projects if you prefer. It would take a few hours to set up.

**Comment by davidnicholls125** [comment]
Great thanks. I'll have a look at the iRecord set up and get back to you.

**Comment by davidnicholls125** [comment]
I think I've found a funding source for this but we would need to have something set up in the next couple of weeks if this is possible. The iRecord version seems more sophisticated than I think we need. Please could you firm up the quote and say if it can be done in the next two weeks? The development I'm thinking of is something like:

1. Add a drop down menu of 'projects' to the recording form. We control which projects to add. The usual blue icon help tip alongside and a default of no project.
2. The project tag is linked to each record on the database and added to the record downloads (admin download, dashboard, etc)
3. Ideally we would have an additional project download page where only those with approved permission for each project can download data for 'their' project.

**Comment by davidnicholls125** [comment]
Thanks John. Just thinking about the joining option, is this something a user can do directly themself or does it need to be approved by an administrator for that project? If we leave out the joining process for now, can it be added later if needed? The attraction of not having to join is that it makes it simpler. Please go ahead with the development.

**Comment by johnvanbreda** [comment]
@davidnicholls125 there are options in the project setup which define whether users can join the projects themselves, or the admin has to set them up, or a half-way house where they can request to join but the admin has to approve it. The advantage of a joining system is that the options shown to the user can they just be the projects they want to be involved in, not the full list. That's probably less important on NatureSpot (where you are likely to have a limited list of currently active projects) compared to iRecord where there are hundreds of projects and most won't be relevant to a user.

For now I'll proceed as discussed with no joining but it can be re-visited in future if you think it useful.

**Comment by johnvanbreda** [comment]
I've now added a page at https://www.naturespot.org.uk/projects which you can set-up a list of projects on. I've created a single project as a quick test so please just overwrite the name and description of this one.

Once you've set up a few projects I can add a select box to the recording form.

**Comment by davidnicholls125** [comment]
Thanks. How do I edit the test project? I can't see how to get to an edit page for this entry.
![image](https://user-images.githubusercontent.com/80914584/125206018-db6b5a80-e27c-11eb-9ddf-16e54a2d0423.png)

**Comment by johnvanbreda** [comment]
There was an edit icon under the "actions" column. There's no need to save space by using icons here so I've changed the link to the words "Edit this project".

**Comment by davidnicholls125** [comment]
I'm not seeing anything in the actions column:
![image](https://user-images.githubusercontent.com/80914584/125206393-f8a12880-e27e-11eb-9916-cf531588e954.png)

**Comment by johnvanbreda** [comment]
Sorry - permissions were wrong, now sorted.

**Comment by johnvanbreda** [comment]
@davidnicholls125 once you've updated the list of projects I can add a control to the data entry page.

**Comment by davidnicholls125** [comment]
I've edited the project so go ahead with adding it to the form. We need a help tip to go with it (blue ? icon).

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've now done that. Please check the help text is OK.

**Comment by davidnicholls125** [comment]
Thanks. Perhaps add ", otherwise ignore." at the end?
How do we enable the project coordinator to access 'their' records?

**Comment by davidnicholls125** [comment]
Can you reply to the question about how project coordinators can access the records please. The Charnwood project are wanting an answer.

**Comment by johnvanbreda** [comment]
On the projects Edit tab you can now add admins to the project. Once someone is an admin, they will be able to view this page: https://www.naturespot.org.uk/projects/explore?group_id=2028&implicit=f

**Comment by davidnicholls125** [comment]
There doesn't appear to be a download button on the records tab (there is on the others).
The project tag doesn't seem to be one of the fields on the full list, can this be added? (If you are an admin for more than one project you need to be able to filter records for each). We would also like it on the main download list.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've added the download button. I've added some extra columns which includes "Group title" for the project name.
Still to do - main download.

**Comment by johnvanbreda** [comment]
Both Elasticsearch and the original download now have a Project column.
