### ISSUE TITLE
cache flushing

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#57]
Is there a way of flushing the cache of the parish pages? The Barkestone page appears to have saved a corrupted view of images.
![image](https://user-images.githubusercontent.com/80914584/129903756-317c20c5-be20-4c33-a435-90f9fa4ea84d.png)

**Comment by johnvanbreda** [comment]
I don't think this is a caching issue, but instead an old record from 2014 was submitted with broken images (1636057). I can remove the broken image links from this record if you like?

**Comment by davidnicholls125** [comment]
I've deleted the broken image links from the species page but the parish page gallery is unchanged. Maybe this is a caching issue? Can you check the default ordering of both records and images please? They should be ordered by latest record date I think and it doesn't appear to be this anymore.

**Comment by davidnicholls125** [comment]
It's refreshed and cleared the broken images now.
