### ISSUE TITLE
Deletion error 38801090

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#59]
I've just recorded Helina reversio and the thank you page said it was a new record. However I recorded it last year and the image is on the species page. Using the record audit trail you recently provided indicates that the record was deleted at the end of last year. I can only think that this was a mistake as the photo shows it was a correct ID. Please could you reinstate this record? Thanks.

**Comment by johnvanbreda** [comment]
I've un-deleted the whole sample which was deleted at the same time. The record IDs are:
18099628
18099629
18099630
18099631
18099632
18099633
18099634
