### ISSUE TITLE
New My Dashboard 

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#6]
Email thread copied below (from my email on 23rd March.

Great thanks we can go ahead with this. I'd prefer you left off the image count to get the other bits as good as we can within the time. Would you have time in the first week of April?

Best wishes,

Dave
On 23/02/2021 12:06, john.vanbreda@biodiverseit.co.uk wrote:
>
> Hi Dave
>
>  
>
> I think 2 days is enough to get something useful working. It might just not be quite so refined and I might have to miss one or two bits out if I run out of time, like the image counts in galleries. If that’s OK with you let me know (but just bear in mind I’m still busy with quite a few projects that need to be completed by end-March).
>
>  
>
> All the best
>
> John
>
>  
>
> From: David Nicholls <davidnicholls125@gmail.com>
> Sent: 14 February 2021 19:13
> To: john.vanbreda@biodiverseit.co.uk
> Subject: Re: My Records development
>
>  
>
> Thanks John, that's helpful. However, it's a bit more than we have to spend at the moment, the grant will only cover one day though we can contribute another day from our own funds. Is there a way to trim things to keep it at two days work? We can leave off the image count and perhaps add this in later as a separate image tab.
>
> Best wishes,
>
> Dave
>
> On 12/02/2021 16:42, john.vanbreda@biodiverseit.co.uk wrote:
>
>     Hi David
>
>      
>
>     I think we should definitely focus on Elasticsearch going forward for the reports – you are going to get much better performance that way, even if we have to iron out some niggles with species naming along the way. A few thoughts:
>
>      
>
>         I should update the Elasticsearch index with the “original taxon group” so we don’t lose that for your data.
>         At the same time, I should update the Elasticsearch index so that the accepted taxon name is taken from your list initially and only gets converted to UKSI’s version if present on UKSI. At the moment, the accepted taxon name is completely skipped unless the species is found on UKSI. That should sort out your issues with species naming.
>         The total records stuff is fairly easy in Elasticsearch.
>         The total images in galleries query will require accessing the Drupal data. This could be quite slow so I will cache it, but even so, on the first load it might take a little while – just a warning.
>         The summary by group/year can be extracted from Elasticsearch and formatted into a table for you.
>         For the species and records lists, they can go on tabs so they only load when accessed.
>
>      
>
>     The new activity summaries on iRecord now use Elasticsearch and can report on huge amounts of data in a few seconds – e.g. SBIF: Activity summary | iRecord (brc.ac.uk). We could recreate the pie chart and map to make it look “pretty”. Also maybe a block of recent photos or similar?
>
>      
>
>     As a ballpark I think there is 2 – 3 days work here – 3 days should allow for a bit of styling to make it look reasonable. That’s £1140 plus VAT. In your calculations you might want to account for the recent support I’ve done which is just under a day at the moment.
>
>      
>
>     Cheers
>
>     John
>
>      
>
>     From: David Nicholls <davidnicholls125@gmail.com>
>     Sent: 11 February 2021 15:12
>     To: John van Breda <john.vanbreda@biodiverseit.co.uk>
>     Subject: My Records development
>
>      
>
>     Hi John,
>
>     We've just heard that we have been successful in securing a small grant to at least make a start on upgrading the My Records page. In time there are additional features we would like to add but I've sketched out below a phase 1 plan which is largely an update on what we have already. There are 4-5 other sections we would like to add in time so perhaps all the sections below the summary should be initially contracted and only expand when clicked?
>
>     We would like the style to look fresh but I'll leave it to you to think about how this might be done.
>
>     It is however important that the page is quick to load so can you think about how best this can be achieved? For instance, would it be possible to use cron to update the figures on a timetable rather than calculate them each time the page is loaded?
>
>     As we have recently discussed, it would make sense to move to Elasticsearch for this job but we really need to resolve the two issues of having NS taxon groups and also to include species that we have had to use invented TVKs for. Is this possible?
>
>     Please could let me know your thoughts on these issues and a rough quote for the work?
>
>     Many thanks.
>
>     Dave
>
>     --

**Comment by johnvanbreda** [comment]
@davidnicholls125 due to delays in another project I've managed to do this - see https://www.naturespot.org.uk/my-records-v2. Let me know if you are OK for it to be swapped over. As discussed, I couldn't do the image gallery counts in the time available, also on the species tab the most recent site name was not possible (at least not in the time available). To save development time, the link from species to the account page is via an icon rather than making the species name a link.

**Comment by davidnicholls125** [comment]
Thanks John, it's looking good and appears much quicker! It will be a huge improvement.
**Summary**
- On the spec I emailed we wanted species numbers as well as record numbers on the year by year summary. Can these be added?

**My records**
- Is there a way for the user (or an administrator) to adjust the column widths? I appreciate there is a lot of detail to squeeze onto the page but it doesn't look good when ID/date/grid ref numbers break onto two rows. Going full screen of course addresses this but is there any way of preventing the wrapping onto the second row on the smaller screen?
- In the old My Records page you can filter by date range which is very useful. Can this be done?
- Can 'verifier comment' be added to the field options?

**My species**
- the sort arrows are missing from some of the headers, can these be added?
- can we have filter boxes as on the My Records tab?
- date range filter option

**Comment by johnvanbreda** [comment]
Hi Dave,

 

I’ve added the species numbers. Just so you know, the colours were chosen using a website called colorbrewer, to make sure they are colour blind safe. 

 

I’ve added a date range filter which also works for the species data. Note that the newer type of date picker used here (which iRecord will shortly switch to) is not yet supported on Mac OS X Safari though the next version will support it. Instead there is a placeholder showing the format to use and a warning is shown if you type it in incorrectly.

 

Column widths – there’s been a recent improvement to the way that column widths are handled in the Elasticsearch reports so when we next update the code this should improve considerably. That’s better than allowing the user to drag column widths I think.

 

I can’t easily add the verifier comment unfortunately as it’s not currently in the Elasticsearch data store.

 

The species tab shows what is known as an “aggregation” and although Elasticsearch has huge benefits regarding performance, it has a few limitations. Whereas a standard relational database like PostgreSQL is designed to allow you to do anything you want even if the resulting query is quite slow, Elasticsearch is designed to only do things which it can do efficiently. So, for example, this type of aggregation (using the species name “term” to aggregate against) allows sorting on the count value columns, but not the text value columns. It also doesn’t fit in with the simple filter row approach on the first tab. But, you can search flexibly using the search box at the top of the page and there is help text for the search format at Using the Elasticsearch search box (DRAFT under development) | iRecord (brc.ac.uk) <https://www.brc.ac.uk/irecord/es-search-box> .

 

If that’s all OK let me know and I’ll swap things over. 

 

Best wishes

John

**Comment by davidnicholls125** [comment]
Thanks John, it's looking good and appears much quicker! It will be a huge improvement.
**Summary**
- On the spec I emailed we wanted species numbers as well as record numbers on the year by year summary. Can these be added?

**My records**
- Is there a way for the user (or an administrator) to adjust the column widths? I appreciate there is a lot of detail to squeeze onto the page but it doesn't look good when ID/date/grid ref numbers break onto two rows. Going full screen of course addresses this but is there any way of preventing the wrapping onto the second row on the smaller screen?
- In the old My Records page you can filter by date range which is very useful. Can this be done?
- Can 'verifier comment' be added to the field options?

**My species**
- the sort arrows are missing from some of the headers, can these be added?
- can we have filter boxes as on the My Records tab?
- date range filter option

**Comment by davidnicholls125** [comment]
Thanks John. The changes all help. On the summary tab can we make the Total rows bold/bigger/background coloured to make them stand out more? We would like to rename it 'My Dashboard' so if you can change the page name I'll amend the menu entry (or you can if it is easier). This will help to highlight that it is a new development.

I've just tried filtering the species tab for 'Birds' this year:
![image](https://user-images.githubusercontent.com/80914584/112981453-212f6780-9153-11eb-9a02-2b61a9297e23.png)
Initially it said the search had failed but when I tried it again it worked in part. Although it is displaying birds it hasn't updated for the date range. Also it says 50/146 entries but there is no pagination to view the second page. I tried to download this report but it says an error occurred and hasn't worked. I've tried the filter with other groups and with species but it won't load anything. The iRecord page you gave me the link to suggests that a simple search word should work, albeit not specific to any field.

**Comment by johnvanbreda** [comment]
There was a problem with the config of the "to" date field that I've fixed - I suspect that was the source of most of the problems.

Note that to view the full list of species you will need to download them, due to the lack of pagination support. Maybe we need to add some extra text to explain this? Or, I can switch to a different type of aggregation with pagination support, but the list will be alphabetical rather than sorted by the species count.

I've disabled the old menu item and added this one to the main menu.

**Comment by davidnicholls125** [comment]
Thanks John, I've just tried the filter and it worked well. Can we add text next to the download button about the lack of pagination?

You haven't made the total row on the summary tab bold - is this not possible? It would look better if the totals could be made to stand out more.

Just to check, will the years update automatically from 1st Jan 2022?

Last thing - where is the code for this new page stored? We don't intend to touch it but do want to build up our knowledge about the overall architecture, as discussed recently.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've updated the visuals to make the totals and row headings stand out separately from the data. 

I've also added some text to explain the species download.

The majority of the configuration for this page is on the Edit tab, in the Form Structure box. This is a combination of Indicia Elasticsearch configuration as described in the documentation at https://indicia-docs.readthedocs.io/en/latest/site-building/iform/prebuilt-forms/dynamic-elasticsearch.html.  You'll also find lots of documentation about how this works at https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html.

Some of the outputs are using the standard [dataGrid] and [download] controls, which just need to be linked to a [source] and they work automatically. There are also some [customScript] outputs on the first tab - so there is a JavaScript file node.230868.js in the files/indicia/js directory which provides some custom handling for the responses from Elasticsearch (parsing the data received and turning it into readable outputs to show on the summary tab). This file also converts the date filter on the toolbar, which is in UK date format, to a date format that Elasticsearch understands (ISO date format).

The JavaScript file mentioned also automatically sets the correct 10 year filter on the data so the year should change automatically.

Finally, there is a small stylesheet in files/indicia/css/node.230868.css which applies some styling, e.g. to the years summary table.

**Comment by davidnicholls125** [comment]
Great, many thanks John, I'm really happy with the final result.

**Comment by davidnicholls125** [comment]
Great, many thanks John, I'm really happy with the final result.

**Comment by davidnicholls125** [comment]
There is a major problem with the new dashboard in that most users are getting an error message when they open the page - 'Elasticsearch query failed'. It's working fine for the trustees so I suspect it is a permission issue. (try Hazel Graves, Ken Charity).

Also, when you type into the filter boxes the text is so pale you can't see it!

**Comment by johnvanbreda** [comment]
@davidnicholls125 it was a permissions issue - now sorted, as well as the font colour in the filter row.

**Comment by davidnicholls125** [comment]
Thanks.

**Comment by davidnicholls125** [comment]
We've had feedback on the new dashboard pointing out that rejected records are missing from the records tab list. Please could you include these and add 'not accepted' as one of the categories in the drop down filter? Thanks

**Comment by johnvanbreda** [comment]
Done
