### ISSUE TITLE
Species links without pages

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#63]
When a national verifier redetermined a record to a taxon not on our inventory it appears in Latest Images (and sometimes the home page) with a link that doesn't work. Could these links go to a landing page explaining that there is no species page set up yet and also trigger an email to us?

**Comment by johnvanbreda** [comment]
@davidnicholls125 doing a landing page redirect is easy - could you add a suitable page with content so I can set that up?

It will take a bit longer to add code for the email so we may as well get the landing page working first.

**Comment by davidnicholls125** [comment]
https://www.naturespot.org.uk/new_species

**Comment by johnvanbreda** [comment]
Next time you get a new species in the latest images, please can you right click and copy and paste the link you get here. I think it will be https://www.naturespot.org.uk/species_by_key?key= but want to check before I make a change and I can't find any new species images at the moment.

**Comment by johnvanbreda** [comment]
I've done this on the basis that the assumption in the comment above is correct, which I think it is having reviewed the code.

**Comment by davidnicholls125** [comment]
Coincidentally, I've just added a species that is on the Indicia inventory but hasn't yet got a species page. The link from the species name on the thank you page is:
https://www.naturespot.org.uk/species_by_key?key=NHMSYS0001717468

**Comment by johnvanbreda** [comment]
Ah - glad I asked, I was thinking this was a link from a species that is still identified as "+ new species". I've now made it so any attempt to load a key that doesn't yet exist will go to the new species page.
