### ISSUE TITLE
Parish page report

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#64]
Could we have a download report for the parish pages which ideally includes the following?

- Parish name
- Date the page was originally set up
- No. species
- No. records
- No. images
- No. recorders
- Description - text
- Parish update - text
- Thanks - text
- Banner selected (Y/N)
- Panorama selected (Y/N)

If it can be set up in an hour or two then go ahead, otherwise can you give us an idea of the time required. Thanks.

**Comment by johnvanbreda** [comment]
Doing an integrated report for the parishes Drupal data and recording data is tricky, as the data are in 2 places. I've created the following report and download through for the Drupal list of parish data: https://www.naturespot.org.uk/parishes-list.

**Comment by davidnicholls125** [comment]
Great thanks. Can you add a report from Indicia with the numbers of records, species and ideally recorders (as on the Wild Places download)? I can then combine them when needed.

**Comment by johnvanbreda** [comment]
Done. The URL for the main parishes list view is now https://www.naturespot.org.uk/parishes-full-details, as this mirrors the wild places.
