### ISSUE TITLE
Incorrect TVK changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#69]
I downloaded the species page details earlier and found that there were numerous duplicated TVKs. These have been changed since the last download on 13th August. All the changed TVKs are also on Indicia. However these changes appear incorrect as NBN is showing the original TVKs for these species. The spreadsheet attached lists all the duplicates and I've added columns to highlight those that have been changed since 13th August. What do you think has happened?

[Drupal duplicate TVKs.xlsx](https://github.com/johnvanbreda/naturespot-d8/files/7449670/Drupal.duplicate.TVKs.xlsx)

**Comment by davidnicholls125** [comment]
Please could you have a look at this?

**Comment by johnvanbreda** [comment]
This seems to be the same problem I described in an email on 26th August - though I'm not sure why my attempts to fix things then didn't pick up these examples. It occurs where there is a junior synonym of a taxon in UKSI which matches another taxon's accepted name, throwing out my scripts. For example, Xanthorae ferrugata is both an accepted name and a synonym of X. spadicearia. 

I suggest next time a UKSI update is applied we should scan the list of changes before they are applied, though I think this particular problem is fixed. Also noting that the way UKSI updates is about to change.
