### ISSUE TITLE
Recorder of the Year

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#7]
edited from the email I sent on 14th January 2021

We are planning to submit an A4A lottery bid. The focus of the bid is to encourage recorders to visit under-recorded areas and also to seek out species that are either uncommon or under-recorded. In essence we will establish an annual award, 'Leics & Rutland Recorder of the Year', which would go to the person who has made the greatest overall contribution. We would therefore like to build a scoring system which ascribes a score to every record according to certain criteria. We will also want to display a map with grid squares to highlight under-recorded areas.

Initially we need to know what is possible so could you let me know if any of the following would be too difficult to achieve? A rough estimate of time would be useful too if possible.

**Scoring system**

- Every record scores 1 point.
- Each record would score additional points based on the number of existing records we already have (eg. four categories 0, 1-3, 4-10, 10-25). Only counting previous records within the last 5 years.
- Records would score additional points where the species is rated amber or red (two categories).
- Records would score additional points when in a monad with no previous records of that species within the last 5 years.
- Records would score additional points when in a tetrad with few previous records of that species within the last 5 years (eg. 3 categories: 0, 1, 2-3).

We would want a way to change the criteria and scores within the categories mentioned above. This shouldn't happen very often but may take some experimentation to get right initially.

We would also need to think about a few 'rules' to prevent cheating or distortions to the scoring. For instance a moth trap recorder may record the same species from the same grid ref a hundred times in a year. Maybe here the basic score is included for each record but the additional points are restricted to the first record? Similarly for the monad/tetrad scores, these should also only be given to the first record.

**Page displays**
To accompany this we would want a few new displays on the website.

- Add the provisional score for each record to the thank you page (provisional as the actual score should only apply if/when the record is accepted).
- A new map page showing VC55 with a monad/tetrad/hectad overlay (toggle option?), and in each square a count of both species and records. As in the Explore page, we would like to be able to select a square and see a list of records and with the option to see a downloadable species list (with last recorded date). Ideally this grid map could be filtered for a selected taxon group. (I've previously asked you about something similar and you seemed confident it was all doable).
- An additional tab to add to the new dashboard page showing the cumulative Recorder of the Year scores (an overall score for each year + option to see the species list with scores behind this).

**Comment by johnvanbreda** [comment]
I see this as 2 separate requirements - the map, plus the record scoring system. Here are my rough thoughts on what's required (technical notes, plus an idea of effort):

**Record scoring system**

Need a nightly process to build lookup tables:
1. Species ID, Amber/red status, count of records.
2. Species ID, monad, count of records.
3. Species ID, tetrad, count of records.

Custom MySQL tables added by module to store these data.

A function to get score data (taking grid ref and species list as parameters)
  Convert grid ref to monad and tetrad
  For each species, calculate score
	Amber/red scoring only given to first record of each species per user/year

Thank you for record page will call this function, display the results, and also store in a custom attribute against the record.

Additional dashboard tab can probably calculate the annual score value for each user/year combination by summing the custom attribute data for accepted records? Or maybe do on nightly process so this value is pre-calculated.

The above is around 5 days work

--

**Map**

Map page, with a toolbar allowing you to select monad or tetrad, species counts or record counts, plus a taxon group filter.

Elasticsearch aggregate request to get record and species counts for tetrad or monad with caching enabled. Approx 2000 monads required for full coverage.

Custom code to add value labels to map. Or maybe easier to show a colour scale, with hover to see exact data values?

Will also need to draw the empty squares that are not returned from Elasticsearch onto the map.

The above is about 2 days work.

**Comment by davidnicholls125** [comment]
Great, thanks John. We might need to phase some of the work depending on how much money we can raise.
