### ISSUE TITLE
Drupal taxonomy term not editable

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#70]
For some reason, the taxonomy entry for Zaraea lonicera can't be edited. It won't allow any change to the name, parent or weight. We need to amend the name, any idea why it won't let this happen?
![image](https://user-images.githubusercontent.com/80914584/140069567-99da2d67-3732-47c2-8843-5443a7923eba.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 I can't see the reason for this - the message comes from deep in the Drupal code so it's difficult to debug. Does it only happen when you save this particular term? Do you know the last time you successfully saved a taxonomy term in this way?

**Comment by davidnicholls125** [comment]
This is the only one we've checked that can't be edited, all others looked at seem fine. Maybe the easiest solution is for us to delete it and set it up afresh. Let me know if you think this is best.

**Comment by davidnicholls125** [comment]
David has managed to resolve it (I don't know how!)

**Comment by johnvanbreda** [comment]
Ok, well done David!
