### ISSUE TITLE
Name edits not updating

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#71]
We have edited Eratigena atrica to Eratigena (genus only) on Indicia and changed the TVK accordingly. However after 24 hours or so the verification page is still displaying records as E. atrica. Is this just a slow update? Shouldn't the records submitted as E. atrica now display as Eratigena?

**Comment by davidnicholls125** [comment]
The records are still showing as Eratigena atrica so it must be that editing the Indicia entry (name change/TVK change) doesn't update the original records - is this correct? Please can you explain what changes we can make to the Indicia entry that do amend the records and what doesn't?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've manually pushed this through. You are correct, we need to manually trigger an update on records if the taxonomic info changes like this.
