### ISSUE TITLE
Trichobelonium kneiffii

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#73]
We have found an old accepted record for Trichobelonium kneiffii but the species wasn't on Indicia nor set up on Drupal. We've now added this but the record doesn't appear on the VC55 map. Oddly, whilst it is shown on the elasticsearch verification page it doesn't appear on the old verification page nor on Explore. Can you explain what is happening? Thanks.
![image](https://user-images.githubusercontent.com/80914584/140931453-08267e90-3e4f-4358-a24b-c12b7fbce644.png)

**Comment by johnvanbreda** [comment]
This was a deleted taxon issue (described elsewhere) - although the species had been added again OK, the occurrences needed re-pointing at the new ID. Now done.
