### ISSUE TITLE
Abia lonicerae/aenea

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#74]
We have redetermined the records for Zaraea lonicerae to Abia lonicerae/aenea. The species page was renamed. The records are showing on the map but the images are not showing, presumably as they have been previously copied as Zaraea lonicerae (except for Andrew Dejardin's record where the three images are in 'organise images'. Is there any way for us to resolve this? If not, please can you 'untick' them so they are copied over? Thanks.
![image](https://user-images.githubusercontent.com/80914584/142731989-f4c483e2-591e-49fa-8493-4e6bfbd2559f.png)

**Comment by davidnicholls125** [comment]
Please could you action this and other priority 1 issues? Thanks

**Comment by johnvanbreda** [comment]
So, all the images which are now linked to a record of Abia lonicerae/aenea that were previously flagged as "copied to drupal" should be reset? There are 19 in total.

For my reference:
```sql
select * from occurrence_images oi
join cache_occurrences_functional o on o.id=oi.occurrence_id and o.website_id=8 and o.taxa_taxon_list_external_key='NHMSYS0021374354'
join cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
```

**Comment by davidnicholls125** [comment]
They still haven't appeared in Organise Images....

**Comment by johnvanbreda** [comment]
Sorry, didn't make that clear - I wasn't entirely confident in what I had to do so I was asking if it sounded like the right thing. I've now done that and the extra images now appear.
