### ISSUE TITLE
100 Species ID Course

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#78]
We have been successful in getting funding to set up a (mainly) online course to help the public learn to identify 100 species. I've started to think through how it should work so thought it useful to get your thoughts and ideas at this early stage. Once we have a plan in place we can then commission you to do the development needed. The support materials should be something we can do but here are the initial proposals on work that will involve you.

1. Signing Up - there is a course fee of £20 though the first 100 participants are paid for by the grant. We can probably use our online giving page to collect the fees. We then need a way of registering these people on the course. Perhaps the easiest way is to add a 'role' to the user profile. We will 'tick' this manually once the funds have been received, this way we can make sure we control who signs up. We can then use the role to determine access to guidance pages for the course.
2. Once this box is ticked, a few things are needed. a) Participants will be able to view a new tab on the 'my dashboard' page that records their progress towards the 100 species target (details below). b) An automatic welcome email is sent with further instructions. c) 
Records from participants are flagged somehow on the verification page so verifiers know to check that the recording advice has been met and to ideally offer good feedback when a record can't be accepted.
3. We need a scoring system to count towards the 100 species target. The caveats are that records must be verified as accepted, species must be from a minimum of 10 taxon groups and with a maximum of 20 from any one group.
4. A new tab on My Dashboard is available only to participants - 'Identify 100 Species'. This summarises their records by taxon group, perhaps with columns for accepted/pending/not accepted. The total 'score' should be highlighted at the top of the page, something like: 'You have successfully  identified X/100 species from Y/10 wildlife groups'. 
5. When the target is reached a further message should appear on the dashboard eg. 'Congratulations............, Click here for your certificate.' Also a milestone email is automatically sent with a similar message.
5. We will get the certificate designed and would like it as a downloadable pdf once the target has been reached. It needs to have the name of the participant inserted automatically. We had something similar years ago with the Young Recorders scheme but it was a bit involved so hopefully there will be a simpler, cleaner way of doing this.

Can you let me know if there is anything here that would be problematic or expensive or you can think of a better solution! Otherwise a rough costing would be useful. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 
1. Yes, I agree, using a role is the simplest way of handling the registration.
2. a) - new progress tab on My Dashboard, needs a little custom code to integrate with the role, but nothing too tricky. b) The Drupal Rules module ought to be able to do this (see https://www.drupal.org/project/rules/issues/2409059) but I just tested it and couldn't find the correct rule type to use. So will require a bit more experimentation or perhaps custom code to send the mail. c) We already have to get RAG info for the verification page, so this could integrate with a role checker.
3. Is this a score that appears on My Dashboard? Or is there a league table of all participants somewhere?
4. OK. 
5. We'll probably need a nightly process that scans the participants to see if anyone has passed since yesterday, as the rules are slightly complex for a quick query.
6. Auto-generating a PDF will be more complex than creating a printable HTML page with their name inserted. PDF generation is certainly possible but would push the cost up.

Rough ballpark costs £1500 plus VAT, plus £500 for PDF.

**Comment by davidnicholls125** [comment]
Thanks. Yes 3 and 4 are really the same need. Just note that the 'score' isn't necessarily the same as the species count as only a maximum of 20 species in any one taxon group can be counted. We will need to have a league table of all participants but this would only be visible to administrators.
If we can create a printable html page that looks like a certificate then this should be fine. Assuming this will work, how much can you do and how much do we need to get a graphic designer to do?

**Comment by johnvanbreda** [comment]
I could roughly copy any certificate template you would like (searching Google shows lots of examples). A graphic designer will be needed either if you want a custom logo, or border pattern, or if you want something a little more bespoke just for NatureSpot.

**Comment by davidnicholls125** [comment]
I've got the go ahead to push on with the development so can you put the dashboard tab together? Also an admin only summary page listing all participants and their scores? Each participant will be invited to two training sessions and we need a way of monitoring who has attended these. Is there a way of having manual check boxes on this summary page? 
I've set up the role and 'joined' a few names so we can pilot everything.
Also can you see if we can set up the automatic welcome email for when a user has joined (ie the '100 species' role has been ticked)?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've setup the dashboard tab code on my local test environment - this is just dummy data but please can you confirm this is the sort of thing you were after. The group names will be the same as NatureSpot:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2392594/152696081-521bdf64-e453-44ab-bbac-ced3bdd99b8a.png">

**Comment by davidnicholls125** [comment]
Thanks. Perhaps we should we add 2 further columns just to make it clearer. '100 species score' would = accepted records but capped at 20, '10 wildlife groups' would = 1 when there is an accepted record for that group. Maybe have a total box above each of these columns? (we wouldn't need to summary text then) Also format the three 'Records' columns above differently to the two 'Score' columns suggested (eg coloured background?).

**Comment by johnvanbreda** [comment]
I've added the columns, using a tick where a group qualifies. I also experimented with where to put the total value - using a box above the columns felt a bit "lost". How about a big dial for each target like this:
![image](https://user-images.githubusercontent.com/2392594/152763747-5fbc198a-ca34-4123-94aa-fa8248594bbe.png)

**Comment by davidnicholls125** [comment]
I like the dials and the columns. Could we centralise the figures in each column?

**Comment by johnvanbreda** [comment]
Like this?
![image](https://user-images.githubusercontent.com/2392594/152798066-db5ad533-2984-48f0-a9f6-4fffa66a7313.png)

**Comment by davidnicholls125** [comment]
Yes looks good. I think the 100 species and 10 wildlife groups columns should be coloured in preference to the others - perhaps use the grey for these as applied to the first column?

**Comment by johnvanbreda** [comment]
I tried grey but it looked odd to me, since a grey background is often used to indicate a header cell (the group names are row headers effectively). Since you are trying to highlight the data values that actually count, how about a soft grey for all the data cells, with those that actually count highlighted in green? E.g.
![image](https://user-images.githubusercontent.com/2392594/152962673-05e945d6-545a-4d54-aa78-dfded1dcc2a8.png)

**Comment by davidnicholls125** [comment]
I slightly prefer to colour just the two score columns. Will I be able to add some intro/explanatory text on the tab? (Preferably editable by me!). The header row might be better if made bold, particularly the 'Group' header doesn't stand out from the list below. If it can go live asap it would help. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've added the Identify 100 species tab to My Dashboard, with a few more colour tweaks which I think cover all your concerns.

**Comment by davidnicholls125** [comment]
That looks really good, thanks John. We have around 6 people signed up for a trial so can you set up the automated welcome email next please? (2b above).

**Comment by davidnicholls125** [comment]
The course will be publicly launched in about a months time so we need to push on with the remaining development. Next step is a page listing all participants and their current score, also the automated welcome email. We can go with the html certificate you suggested. I'm working up a few design ideas. Are you OK get the set up tasks done in the next two weeks or so?

**Comment by johnvanbreda** [comment]
Yes, will try to get onto this tomorrow.

**Comment by johnvanbreda** [comment]
@davidnicholls125 The welcome email is done and there is a configuration form for the email content at https://www.naturespot.org.uk/admin/config/100_species/settings.

Next task is the background calculations of user's progress towards the scores.

**Comment by davidnicholls125** [comment]
Thanks John. Regarding the certificate design, here is one I quite liked together with some proposed text. Is this sufficient for you to work something up? I'm not sure yet what wording will be required to recognise the partners/funders but we can refine this later.
[100 Species Certificate.docx](https://github.com/johnvanbreda/naturespot-d8/files/8248411/100.Species.Certificate.docx)

**Comment by johnvanbreda** [comment]
Thanks - yes, I'm sure I can work from that. Though I'm going to work on the other aspects of the workflow first if that's OK.

For now - here's a new report that you can view as an admin, just to review the progress of the members: https://www.naturespot.org.uk/100-species/members-list. Also, note that if you edit a user profile, there is now an extra box at the bottom you need to tick to get them to be included in this report. That's a duplicate of the existing role field - but the role is for Drupal access, whereas the extra tickbox is to tell the Indicia reports to include the person.

**Comment by davidnicholls125** [comment]
Thanks for the list. Would it be possible to add their email and also have a download function? We will be emailing participants about courses so we need a way of gathering the addresses and also monitoring invites/attendance, etc. I can do this in Excel with a csv download.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've done the following:
1. Add a download link to the members list.
2. Add the member email address.
3. If you have passed the challenge then on the 100 Species tab you now get a link to a first draft of the certificate as a PDF.

For the certificate - will need some form of logo to fit in the bottom right of the certificate, plus to review all fonts and other layout decisions.

**Comment by davidnicholls125** [comment]
The email isn't displaying nor is it showing in the download. Would it also be possible to add the date when they were signed up to 100 species? Also I'm signed up but not on the list???
Thanks for the certificate, I'll get back to you on the details.

**Comment by johnvanbreda** [comment]
Email fixed for the David Nicholls account. I've also added a date joined field (which is the date the box at the bottom of the user profile form was ticked which is not necessarily correct for the existing members since I added the box after you added the role, but will be correct going forward).

It doesn't look like your account has the Species 100 role ticked (or the box at the bottom)?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I'm just looking at the practicalities of sending out an email on achieving the goals. The warehouse's milestones facility would appear to be ideal for this except that it doesn't support custom logic for when a milestone is passed (the rules around passing in this case are quite complex).

The "triggers" system in the warehouse is different to the milestones system - it does allow changes to data state to be detected by custom rules. They can either have a set of email recipients who have to be added to the trigger in the warehouse configuration, or they can generate notifications for a dynamically selected list of users generated by the query. So, in this case we can have a custom report that detects newly achieved 100 species participants and raises a notification for them. Notifications are only turned into emails if the user has subscribed to receive them as digest emails (which won't normally be the case for NatureSpot users), which means that the user won't see the notification. This approach would only work on iRecord where there is a fully-fledged notifications system including a way of configuring which types of notification are sent as emails.

For the Species 100 system, a thought is that I can configure the triggers tool to generate an email which is sent to a single fixed email account (the NatureSpot one), giving the username of the user who just achieved the goals. This would allow you to send an email from the NatureSpot account (which might be preferable to one from the warehouse) and to potentially personalise it. Does this solution sound acceptable? It also means that you would have full visibility of which users have achieved the goals and when they receive the email.

**Comment by davidnicholls125** [comment]
Thanks John. Its not ideal to have to manually send a congratulatory email as there may be hundreds of participants (we hope!). We really want it to be as automated as possible. How is the welcome email triggered? Is this affected if the user hasn't signed up for notifications?
On a separate but related point, we really would like all users to receive notifications as a default setting, even though they can choose to change this if they like. We wrote the terms with this in mind (section copied below).
![image](https://user-images.githubusercontent.com/80914584/162001678-5c9ce296-752b-4f8c-b811-aabed1adff18.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 that's OK, I was just looking for an easy way to implement the email by using an existing mechanism on the warehouse. The existing welcome message is sent via the Drupal code which is triggered when you save an account profile having added the 100 species role. We can't use exactly the same mechanism, since the account won't be saved to trigger the code, and the information about whether they've achieved the goals is on the warehouse, not on Drupal. But I can use a report to obtain the information and use the background cron task (which runs every 3 hours on Drupal) to check for new achievers.

Please can you let me have the email text? I'll put it into a configuration form so you can tweak it.

Regarding the last point, is it OK to raise this as a separate issue?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've now written the code required for the email but left it disabled until you've got the email text sorted. You can configure the text at https://www.naturespot.org.uk/admin/config/100_species/settings in the same way as the welcome email.

When the code is enabled, 1 user will immediately get an achievement email.

**Comment by davidnicholls125** [comment]
Thanks John. I've added some text to the congratulatory email.

**Comment by johnvanbreda** [comment]
Thanks. Presumably it would be best to wait till the certificate is finalised before enabling the emails?

Should the first sentence be "Well done on achieving *the* 100 Species Challenge!"?

**Comment by davidnicholls125** [comment]
Yes that seems sensible. I've corrected the first sentence! Thanks.

**Comment by davidnicholls125** [comment]
A few comments/additions/questions for the certificate:
1. Look at the 100 Species pages on the website (top menu) and include the blue/orange colours, perhaps just in the text?
2. I've used papyrus for the 'Identify 100 Species' title, perhaps use this on the certificate too?
3. Just checking that the name is the person's full name and not their NS username?
4. Place all the logos along the bottom, NS on the left (in the green column), then the GRCF logo, attached, then the text about Saving the Saffron Brook - as used on the web pages.
5. Centre the signature above the name and title of Sue (I've asked Sue to send me a digitised signature).
6. The text in the circle to be: "Congratulations. You have proven your skills as an amateur naturalist and made a valuable contribution to local wildlife recording."
7. Centre text: "This certificate has been awarded in recognition that 100 wildlife species in Leicestershire and Rutland have been correctly identified and recorded on NatureSpot."
8. Is it possible to add a background graphic (such as dragonfly outline)? There was a butterfly outline in the original template certificate I suggested and I think something like this would help the overall look. If so, I'll look to find something relatively simple! I've attached the frog outline in case this could be of use!
![COLOUR GRCF logo landscape PNG](https://user-images.githubusercontent.com/80914584/162781050-71e1984c-adb6-4313-9f57-8bda5e8003d0.png)
![NatureSpotLogo](https://user-images.githubusercontent.com/80914584/162781216-51cb8f7f-b54d-48b5-8c14-1f9d5ae92312.jpg)
![Frog10_Outline](https://user-images.githubusercontent.com/80914584/162781507-d009eacd-783f-4884-9c3c-c1a1d1b87461.jpg)

**Comment by davidnicholls125** [comment]
Hi John, the 100 Species project has been launched today so the certificate is now pretty urgent to finalise..... Thanks.

**Comment by johnvanbreda** [comment]
Sorry - was away for a few days last week. 

> Look at the 100 Species pages on the website (top menu) and include the blue/orange colours, perhaps just in the text?

I found the blue didn't work well as a font colour so used it as the inset bubble background and used the orange for part of the title.

> I've used papyrus for the 'Identify 100 Species' title, perhaps use this on the certificate too?

I had to use a slightly different font called Parchment MF as it is a freeware font (Papyrus would require a licence to link it properly to the PDF).

> Just checking that the name is the person's full name and not their NS username?

Correct.

> Place all the logos along the bottom, NS on the left (in the green column), then the GRCF logo, attached, then the text about Saving the Saffron Brook - as used on the web pages.

Done. Note the NS logo is a reconstruction made using the Parchment font, since if I use the original on a printable PDF the quality wouldn't be high enough (the text would look blurry).

> Centre the signature above the name and title of Sue (I've asked Sue to send me a digitised signature).

Done - awaiting signature

> The text in the circle to be: "Congratulations. You have proven your skills as an amateur naturalist and made a valuable contribution to local wildlife recording."

Done

> Centre text: "This certificate has been awarded in recognition that 100 wildlife species in Leicestershire and Rutland have been correctly identified and recorded on NatureSpot."

Done

> Is it possible to add a background graphic (such as dragonfly outline)? There was a butterfly outline in the original template certificate I suggested and I think something like this would help the overall look. If so, I'll look to find something relatively simple! I've attached the frog outline in case this could be of use!

The frog is already used in the logo on the bottom left. We can put some additional graphics in the background though I'd suggest keeping it very subtle.

**Comment by davidnicholls125** [comment]
Thanks John. Sue's signature attached. Can the text (bottom right) have a colour box as it looks a bit odd floating free. Also can we move this and the logo alongside down to the bottom, ideally all the logos/text in a level row along the bottom.

**Comment by johnvanbreda** [comment]
I've added the signature and added a box to the text. I'm not sure what you mean about aligning to the bottom though as the logos and text are already along the bottom?

**Comment by davidnicholls125** [comment]
Thanks. It looks like the GRCF logo block had a gap beneath it, but it looks fine now the text is in a box. I was also thinking it would look better if the NatureSpot in the green column was at the same height as the GRCF logo. One last thing - the frog isn't centred in the column.

**Comment by johnvanbreda** [comment]
I've moved the NatureSpot text and centred the frog. 

If all OK, shall I enable the emails?

**Comment by davidnicholls125** [comment]
Great, thanks. Yes go ahead with the email.

**Comment by johnvanbreda** [comment]
Email done.

**Comment by davidnicholls125** [comment]
Thanks.

**Comment by davidnicholls125** [comment]
Can you check the certificate please, the NatureSpot wording no longer fits on the page....
![image](https://user-images.githubusercontent.com/80914584/169820904-43762efa-950d-4462-be62-3c86c493b7f0.png)

**Comment by johnvanbreda** [comment]
For some reason, the Parchment font is not loading correctly for the left column, even though it does for the right column. It works fine in the debug view of the PDF and as the problem lies deep in the PDF generator code it is difficult to fix. I have reduced the font size so at least it fits, but may need to return to look at this another time if we want the Parchment font back.

**Comment by davidnicholls125** [comment]
That's fine, thanks.
