### ISSUE TITLE
Adding a Wild Places list to the parish page

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#8]
We would like to add a block to parish pages that lists links to all the Wild Place pages within that parish. This could perhaps use the code that we already have on the Wild Place map page when the parish is entered into the filter box.

Some parishes have a lot of Wild Spaces so maybe we need to just list the titles and not the description - or have the option to expand the list to include the summary as shown on the Wild Place map page.

**Comment by johnvanbreda** [comment]
2-3 hours effort.

**Comment by davidnicholls125** [comment]
Thanks.

**Comment by davidnicholls125** [comment]
We'd like to go ahead with this please.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've now done this. It fitted in nicely only if I don't include the descriptions.

**Comment by davidnicholls125** [comment]
Great, thanks.
