### ISSUE TITLE
Elastic-search problem?

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#80]
There seems to be a problem with elastic-search not reflecting recent changes. There are 11 queried records (from a pending download) but only 3 of these are displayed on the elastic-search verification page. Searching 'all records' (eg 21142033) for the missing records brings a blank return. Most of these records were redetted a couple of days ago. Also I've checked the record audit trail you developed and these redets are not showing.

**Comment by johnvanbreda** [comment]
I've requeued these records so they should appear in the Elasticsearch data within a few minutes.

**Comment by davidnicholls125** [comment]
Thanks. What was the issue?

**Comment by johnvanbreda** [comment]
For some reason, when the redetermination was applied it didn't update a flag that indicates it needed to be refreshed on Elasticsearch. I've tested a  redet and it seems to work OK, but if you let me know next time you redet something I can check it worked OK.,
