### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#82]
We have had a few comments on the forum about images being rotated and displaying either upside down or on their side. Can this be resolved? (See https://www.naturespot.org.uk/node/241977)

**Comment by johnvanbreda** [comment]
The plupload software is supposed to automatically handle rotation in the EXIF data. A few years ago there were some reports on iRecord but I haven't heard of problems recently. Can you obtain the original photo and a record ID that shows this problem please so I can look at the EXIF data?

**Comment by davidnicholls125** [comment]
Thanks. We've contacted the person who had the problem but checking at our end the images all seem OK. I'll park this and reopen it if we get any further examples.
