### ISSUE TITLE
Annual data download

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#86]
I'm about to start processing the 2021 records ready for distribution. My notes from last year say to ask you for a report that includes the NS taxon groups, user email addresses, etc. Please can you send this to me? (Can I not get this information myself?). The data range for 2021 is 18548830 to 23392163. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've sent the data by email. Although I could give you a report that accesses this data, as it's a dump of email addresses I'd want to put some extra precautions in place, so as it's only annual I am not sure it's worth the additional effort.
