### ISSUE TITLE
Location details

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#88]
The LRERC would like the location entered for a record to start with the nearest town or settlement. We do urge this on the guidance but not everyone does this. We have just spent a tedious 3 days manually standardising the downloaded 2021 location data and are looking for a better solution. Two ideas spring to mind:
1. automatically assign each record to the parish it falls within (we think this would satisfy LRERC but would need to check). We have the parish boundaries loaded but is this possible? (similar perhaps to how the VC is assigned...)
2. add a second location box on the form that asks for the nearest settlement to be entered. Presumably this would be reasonable straightforward?

**Comment by johnvanbreda** [comment]
1. Yes, this would be possible, but if it is automated what are the benefits? The LRERC could easily use GIS to automatically assign a parish name or nearest town name, but if automated (either during data entry or later) then the benefits of having a location name to check the record position against are lost. If a grid square borders 2 town/parish boundaries then the given place name can be useful for disambiguation, but not if we do this automatically. 
2. Yes, this is an easy solution.

**Comment by davidnicholls125** [comment]
I wasn't thinking that the parish entry would replace the location text detail, but would instead be an admin process behind the scenes and added into the data download (just as the VC assignment works I think). This would then be an additional field which could possibly be joined to the main location entry as needed. I hadn't appreciated that LRERC could do this themselves, is the software to it freely available? Could we set it up anyway as it would be useful to us to be able to analyse record numbers by parishes?

**Comment by johnvanbreda** [comment]
@davidnicholls125 it's not my main area of expertise, but a GIS system should be able to do this. The free QGIS software is widely used and well respected and I found the following link that indicates it is capable of this sort of thing: https://gis.stackexchange.com/questions/258101/joining-attributes-from-points-to-polygons.

**Comment by johnvanbreda** [comment]
Another possibility would be to install PostgreSQL with PostGIS (the main database used on the server). You can then use the database to import a layer of Parish data and the downloaded data, then you can run queries which join the 2 together. This would be the same process as I'd use if we did this on the server - my main worry about doing it on the live server is that it is a fairly CPU intensive process so I'd rather not impact the other projects running on the same server.

**Comment by davidnicholls125** [comment]
Thanks John. I'll discuss this with LRERC.
