### ISSUE TITLE
Indicia TVK changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#89]
Reviewing the 2021 data has highlighted a number of mismatches between the species we are trying to use and the species the TVK brings up - mainly around ss and sl entries. I think this is our error in selecting the wrong TVK when the species was set up. An example is Bombus lucorum which should be sl but the TVK is actually for the ss entry. There are 252 records for this taxon. If I correct the TVK on Indicia, I don't think it updates these 252 records to the new TVK. The prospect of redetting and then reverifying all of them manually (plus 20-30 other species too) seems a lot of work - what is the best way for us to deal with this?

**Comment by davidnicholls125** [comment]
John, I'd appreciate a quick response to this as we are being chased by CRs for the data. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 if you do the TVK changes, then just keep a list of the IDs of the taxa that you changed (from the URLs on the warehouse). I can then a quick query to update all the record TVKs to match.

**Comment by davidnicholls125** [comment]
OK, thanks John.
