### ISSUE TITLE
Export data error

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#90]
We are unable to download the species page details from the link below and get this error.
https://www.naturespot.org.uk/all-species-account-details/export.csv
![image](https://user-images.githubusercontent.com/80914584/150796400-86410091-3a14-4ce8-b68d-da16aa7c2fcf.png)

**Comment by johnvanbreda** [comment]
I've fixed that - there was a missing library, probably required since the Drupal 9 upgrade.
