### ISSUE TITLE
Verifier comment

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#91]
The verifier's comments aren't included in the download but LRERC are anxious to include these (which makes sense as they add important information). How can we get these?

**Comment by davidnicholls125** [comment]
This is now urgent as the data needs to go to LRERC. Please can you respond? Thanks.

**Comment by davidnicholls125** [comment]
Closed in error! Please respond.

**Comment by johnvanbreda** [comment]
Is a separate download of verifier comments for each record acceptable? We can't easily include these in the existing Elasticsearch download unfortunately.

**Comment by davidnicholls125** [comment]
Yes no problem, thanks.

**Comment by johnvanbreda** [comment]
I've sent a first draft by email.

**Comment by davidnicholls125** [comment]
Thanks.
