### ISSUE TITLE
new Wild Place error

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#92]
I've just tried to set up a new Wild Place page from a kmz file sent to me. I converted it to a shp zip file as usual and loaded it into Indicia which seemed fine. However the Drupal page is giving an error. What needs amending?
https://www.naturespot.org.uk/Lady_Hay_Wood

**Comment by johnvanbreda** [comment]
Duplicate of #93 - now fixed
