### ISSUE TITLE
Badger records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#94]
The downloaded badger records have blurred details so are useless as actual data. How do we get the actual grid refs and location details so these can be passed over to the County Recorder for badgers?

**Comment by davidnicholls125** [comment]
I've just received an email from the CR seeking the badger location details - please can you respond to the question above?

**Comment by johnvanbreda** [comment]
The Elasticsearch download page now provides a full precision download. https://www.naturespot.org.uk/download-data-v2
