### ISSUE TITLE
TVK changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#95]
You recently offered to change the TVKs on existing records where we have amended the species entry on TVK. Please could you update all the records for the following taxa? If a spreadsheet is easier just let me know. Thanks.
Also, please can you look at #87. 
![image](https://user-images.githubusercontent.com/80914584/152119542-dcdfff3e-ac12-4a5d-b55a-c15eeafbb892.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 it's slightly easier if I receive the values in text form (text file or spreadsheet) rather than an image, to save a bit of typing, but not a big issue if there are only a few values. I've run the following query which will queue these records for updating in the next hour or so:
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', o.id, null, 100, 2, now()
from cache_occurrences_functional o
join cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
where o.website_id=8
and cttl.external_key in ('NHMSYS0020936546','NHMSYS0021486732','NHMSYS0021233768',
					'NBNSYSxxx061','NBNSYSxxx062','NBNSYSxxx063','NBNSYSxxx064','NBNSYSxxx065',
					'NHMSYS0001477394','NHMSYS0020061875','NBNSYS0000031889')
```
