### ISSUE TITLE
User registrations - edit not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#99]
I'm getting this error message when I try to edit a user registration:
![image](https://user-images.githubusercontent.com/80914584/158848548-581ef006-a0fa-41ff-a555-89f905509545.png)

**Comment by johnvanbreda** [comment]
Which account are you using? I think the warehouse is thinking you don't have rights to edit the user accounts.

**Comment by davidnicholls125** [comment]
Tried David Nicholls and david nicholls (not sure if there is a difference?), neither allow edits.

**Comment by johnvanbreda** [comment]
Now fixed
